### ISSUE TITLE
request code to visualize policy

### ISSUE THREAD

**Issue by rguptatx** [JuliaPOMDP/POMDPs.jl#100]
at this webpage
https://github.com/JuliaPOMDP/POMDPs.jl/blob/master/examples/GridWorld.ipynb

under Out[36]
there is a gui that displays value of being in each state and optimal action.
I would like to access code to generate this visualization. Code in different 
langauge or matlab is fine.

**Comment by zsunberg** [comment]
Hi @rguptatx, I think the code is here https://github.com/sisl/aa228-notebook/blob/master/gridworld.jl

Correct me if I'm wrong, @etotheipluspi

**Comment by etotheipluspi** [comment]
Yes, the code is currently not part of POMDPs.jl. But you should be able to use the link @zsunberg provided to do a similar visualization.

**Comment by rguptatx** [comment]
In the gridworld example there is size_x, size_y etc. in type GridWorld.
In visualize code at https://github.com/sisl/aa228-notebook/blob/master/gridworld.jl
there is S which is vector of Int in type GridWorld. Which of the two definitions 
should be kept?

**Comment by zsunberg** [comment]
I think I would be ok with either size_x, size_y or a Pair or NTuple, but I
don't like using a Vector. Probably just easiest to keep size_x and size_y

**Comment by rguptatx** [comment]
this particular code runs and prints 
plot (generic function with 5 methods)
it does not ouput any plot or file.
When I tried to add the solver the MDP definitions were conflicting
It would be great to get a sample visualizer with an MDP solver.

**Comment by zsunberg** [comment]
Yeah, we should definitely get this working before AA 228
