### ISSUE TITLE
de-vectorizing states or observations

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#101]
We have the function vec() to return a float array version of a state or observation. Shouldn't we also have a function for converting back? Or should it just be `convert(Type{MyState}, ::Array{Float64,1})` for that?

**Comment by etotheipluspi** [comment]
I like the idea of `convert`, but if we adopt it makes sense to also get rid of `vec()`. We then would have two convert functions for states and observations:
```
convert(::MyState, ::Vector{Float64})
convert(::Vector{Float64}, ::MyState)
```
I'm fine with that. Is anyone opposed to the idea?

**Comment by tawheeler** [comment]
Looks good to me.
We may want to have a `copy!(::Vector{Float64}, ::MyState)` to reduce memory allocation.

**Comment by etotheipluspi** [comment]
After some discussion, @zsunberg and I settled on this:
```julia
convert(::Type{Array{Float64}}, s::MyState, p::Union{POMDP,MDP}) # convert to float array
convert(::Type{MyState}, s::Array{Float64}, p::Union{POMDP,MDP}) # convert to problem specific state
```
This also works for observations if the problems are POMDPs, and resolves any ambiguities that might come up if different problems use common state or observation types. 

Added to interface in dc1daa6a3feafb07a4f63254c008bbd7b5efb2f7
