### ISSUE TITLE
Encourage use of importall

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#104]
Did you guys know about the `importall` directive (http://docs.julialang.org/en/release-0.4/manual/faq/#what-is-the-difference-between-using-and-importall)? Perhaps we should encourage that for POMDPs and use it for examples. It might alleviate some of the angst in errors having to do with importing.

**Comment by rejuvyesh** [comment]
I agree that `importall` is a good choice for `POMDPs.jl` especially because it is implementation free.

**Comment by zsunberg** [comment]
I added this suggestion to the error message macro.
