### ISSUE TITLE
Visualization interface

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#107]
Eventually it might be nice to have a standard interface for visualizing states, etc.

If I understand correctly, the julian interface for visualizing object `x` is

``` julia
show(::IOStream, ::MIME, x::Any)
```

This doesn't really work that well for us because we will want to show (mdp, state) or (mdp, state, action) or (mdp, state, action, state) or maybe (mdp, observation, state') tuples. For machine learning interfaces like AI Gym, the mdp and state are contained within the same "environment" object, and a render function is used on that object.

Any thoughts on what an interface for POMDPs.jl should look like?

I am implementing a grid world visualization for the grid world model in POMDPModels.jl, so that can be a prototype.

**Comment by cho3** [comment]
I like (mdp, state, action, state). 

I think having it be a little more transparent makes more sense in Julia. The other reason is that this way it would mimic the signature for the reward function, which ultimately tells us how well our policies are doing, which is basically what we care about in visualizations (in addition to the current state and what the agent is actually doing, which is contained in the signature).

**Comment by ChrisRackauckas** [comment]
The visualization is done through dispatches on show and mimetypes for the REPL, but note that if you want to control the visualization in Juno, you need to define a `render` using Juno.jl (a small dependency for package authors to link to Juno)

**Comment by odow** [comment]
Terribly hacky (I'm not a JS dev) but here's something that might be interesting https://github.com/odow/SDDP.jl/tree/master/src/visualiser

It builds visualisations like https://odow.github.io/talks/assets/stock-example-visualisation.html

**Comment by zsunberg** [comment]
After writing a bunch of problems, here is my recommendation:

Either here or in POMDPToolbox, *we* provide the following type and default implementation of show()
```julia
POMDPVis{P<:POMDP}
    p::P
    s::Nullable
    a::Nullable
    r::Nullable
    sp::Nullable
    b::Nullable
    o::Nullable
    bp::Nullable
    info::Nullable
end

POMDPVis(p; b=Nullable{Any}(), s=Nullable{Any}(), a=Nullable{Any}(),  #=etc=#) = POMDPVis(p, s, a, r, sp, b, o, bp, info)

function render end

show(io::IO, mime::MIME, v::POMDPVis) = show(io, mime, render(v))
```

then, the problem writer of the pomdp `ExamplePOMDP` would be responsible for implementing either 
```julia
render(v::POMDPVis{ExamplePOMDP})
```
which would return something like a plot or a tikzpicture or something from images or an `HTML` object - something that can be shown.

AND/OR if they want more control over how it is shown with some mime `examplemime`, they can implement
```julia
show(io::IO, mime::MIME"examplemime", v::POMDPVis{ExamplePOMDP})
```

This should make it possible to implement, for instance, a simulator that outputs a gif, or a simulator that pops up in a blink window.

What do people think?

**Comment by zsunberg** [comment]
We could suggest that people use plots recipies within `render`.

**Comment by zsunberg** [comment]
A few potential shortcomings:
1. This has no provision for rendering histories (we could support a `render(hist::SimHistory)` method with a default to call render at each step)
2. It doesn't support separate method dispatch for different belief types (I think the added complexity for this would not be worth it)

**Comment by MaximeBouton** [comment]
I like the idea of having an interface for rendering and separating `render` and `show`. What is the motivation behind the `POMDPVis` type? 
The problem writer would most likely implement render function for states, beliefs, observations or other objects.

**Comment by zsunberg** [comment]
The reason for the POMDPVis type is to handle all the potential different combinations of problem, state, action, observation, belief, info, etc. that you might be asked to render. The alternative would be to ask problem writers to implement something with keyword arguments, i.e.
```julia
render(p::MyPOMDP; s=nothing, a=nothing, b=nothing....)
```
or 
```julia
render(p::MyPOMDP; kwargs...)
```

Is it easier to explain this or to have a POMDPVis type?

**Comment by zsunberg** [comment]
Another question is where this should go.

I think it should go in a new (registered) package called POMDPVisualization.jl

**Comment by zsunberg** [comment]
And another question is should `render` take a mime type as an optional argument? We could have the default
```julia
render(p::POMDPVis, mime::MIME) = render(p)
```
and they could write special renders for special mime types if they want.

**Comment by zsunberg** [comment]
Alright - I think this is it:
```
render(mdp, t)
```
where `t` is a *named tuple* containing `s`, `a`, `b`, etc.
