### ISSUE TITLE
Prior Knowledge

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#109]
We may want to provide a consistent interface to allow people to seed solvers with prior knowledge. This could provide functions like `init_N` and `init_Q` and `estimate_value` as in MCTS for all solvers to use. It should probably be broken off into a side package `PriorKnowledge.jl` seems like kind of a generic name though.

**Comment by ebalaban** [comment]
I like the idea. `DomainKnowledge.jl` might be another naming option, but I think `PriorKnowledge.jl` would work fine.

**Comment by zsunberg** [comment]
I like DomainKnowledge. A few questions to think about:

1. Should this include rollout policies? (I think yes)
2. Should this subsume POMDPBounds since bounds are a form of domain knowledge? (I think yes)

**Comment by rejuvyesh** [comment]
I would be against merging in `POMDPBounds`. Although technically it's true, from dependency management perspective, it's nicer to have smaller packages. We can re-export `POMDPBounds` from `DomainKnowledge` if it's useful.

**Comment by mykelk** [comment]
I like DomainKnowledge. Agreed with @rejuvyesh on POMDPBounds.

**Comment by zsunberg** [comment]
So, if we keep POMDPBounds separate, we are going to have to pass to the solver an object representing the bounds and another object representing other domain knowledge? In that case it would also seem consistent to pass in the rollout policy separate from the other domain knowledge. It sounds like there will be a lot of concepts to understand/document. If it is more unified, it may be simpler to understand.

**Comment by rejuvyesh** [comment]
Domain knowledge is a fairly abstract concept. There will always be details :disappointed:. Not sure how that would make it simpler?

**Comment by mykelk** [comment]
Hmm... Can we enumerate a set of standard pieces of domain knowledge that would be relevant to all the standard solvers? If so (and the list is not very long), we might consider just having one package that handles it all.

**Comment by ebalaban** [comment]
I am also not necessarily opposed to keeping all of the domain knowledge pieces in one package. I'll start the list and let's see how long it gets:

- Value initializers
- Value estimators
- Value bounds
- Rollout policies
- Domain-specific belief estimators/updaters

**Comment by zsunberg** [comment]
So I thought about this a lot last night and about some of the things the students are finding confusing and I think I have a solution. I no longer thing we need a DomainKnowledge package. I am implementing my idea in MCTS on a branch right now - will report back with details this afternoon.

After talking with students who are trying to use this (and @mykelk) - I think the easiest way for people new to julia to pass this kind of domain knowledge is by directly giving functions like `init_Q` and `init_N` to the solver. But this can't be the only option because functions are not easily serializable. We need to support passing both custom objects and functions to the solver. It turns out this is pretty easy.

**Comment by zsunberg** [comment]
Naming tho... so difficult

**Comment by zsunberg** [comment]
Alright, I have my new approach for domain knowledge in MCTS implemented in the `new_domain_knowledge` branch of MCTS.jl. The idea is that, for each of the domain knowledge elements (`init_Q`, `init_N`, `estimate_value`, and `next_action` for now), the experimenter can pass either a function or an object (or a number in some cases). The dpw solver now looks like this:

```julia
"""
MCTS solver with DPW

Fields:

    depth::Int64:
        Maximum rollout horizon and tree depth.
        default: 10

    exploration_constant::Float64: 
        Specified how much the solver should explore.
        In the UCB equation, Q + c*sqrt(log(t/N)), c is the exploration constant.
        default: 1.0

    n_iterations::Int64
        Number of iterations during each action() call.
        default: 100

    rng::AbstractRNG:
        Random number generator

    k_action::Float64
    alpha_action::Float64
    k_state::Float64
    alpha_state::Float64
        These constants control the double progressive widening. A new state
        or action will be added if the number of children is less than or equal to kN^alpha.
        defaults: k:10, alpha:0.5

    rng::AbstractRNG:
        Random number generator

    estimate_value::Any (rollout policy)
        Function, object, or number used to estimate the value at the leaf nodes.
        If this is a function `f`, `f(mdp, s, depth)` will be called to estimate the value.
        If this is an object `o`, `estimate_value(o, mdp, s, depth)` will be called.
        If this is a number, the value will be set to that number.
        default: RolloutEstimate(RandomSolver(rng))

    init_Q::Any
        Function, object, or number used to set the initial Q(s,a) value at a new node.
        If this is a function `f`, `f(mdp, s, a)` will be called to set the value.
        If this is an object `o`, `init_Q(o, mdp, s, a)` will be called.
        If this is a number, Q will always be set to that number.
        default: 0.0

    init_N::Any
        Function, object, or number used to set the initial N(s,a) value at a new node.
        If this is a function `f`, `f(mdp, s, a)` will be called to set the value.
        If this is an object `o`, `init_N(o, mdp, s, a)` will be called.
        If this is a number, N will always be set to that number.
        default: 0

    next_action::Any
        Function or object used to choose the next action to be considered for progressive widening.
        The next action is determined based on the MDP, the state, `s`, and the current `DPWStateNode`, `snode`.
        If this is a function `f`, `f(mdp, s, snode)` will be called to set the value.
        If this is an object `o`, `next_action(o, mdp, s, snode)` will be called.
        default: RandomActionGenerator(rng)
"""
type DPWSolver <: AbstractMCTSSolver
    depth::Int
    exploration_constant::Float64
    n_iterations::Int
    k_action::Float64
    alpha_action::Float64
    k_state::Float64
    alpha_state::Float64
    rng::AbstractRNG
    estimate_value::Any
    init_Q::Any
    init_N::Any
    next_action::Any
end

"""
    DPWSolver()

Use keyword arguments to specify values for the fields
"""
function DPWSolver(;depth::Int=10,
                    exploration_constant::Float64=1.0,
                    n_iterations::Int=100,
                    k_action::Float64=10.0,
                    alpha_action::Float64=0.5,
                    k_state::Float64=10.0,
                    alpha_state::Float64=0.5,
                    rng::AbstractRNG=MersenneTwister(),
                    estimate_value::Any = RolloutEstimate(RandomSolver(rng)),
                    init_Q::Any = 0.0,
                    init_N::Any = 0,
                    next_action::Any = RandomActionGenerator(rng))
    DPWSolver(depth, exploration_constant, n_iterations, k_action, alpha_action, k_state, alpha_state, rng, estimate_value, init_Q, init_N, next_action)
end
```

I will work on a tutorial notebook later tonight, and may merge these changes into master tonight or tomorrow. The implementation for this is actually not too complicated (see domain_knowledge.jl in MCTS).

Does anyone have any comments or feedback on this approach?

**Comment by mykelk** [comment]
Wow, this is quite nice. Are there any performance considerations to be aware of? Also for things like `f(mdp, s, depth)`, why pass in the MDP? Shouldn't the caller have access to that anyway?

**Comment by zsunberg** [comment]
There are potential performance problems because there are a lot of Any type annotations, so the compiler may have trouble inferring the types. A quick test of a few minutes duration in GridWorld problems shows little difference in speed between this version, the current master, and v0.1.0 though. If we find performance problems due to type inference difficulties in the future, we may be able to solve them by parameterizing the policy type.

I think that passing in the mdp is the best practice since f is passed to the *solver*. When solve() is called, the solver is then introduced to the mdp, and can then pass that mdp to f. This allows one to use the same solver *object* with different mdps with minimum confusion. (the person who writes f can of course choose to ignore the mdp argument). (I'm also not 100% sure I understand who "the caller" is in your question. Of course the code that calls f will have it - did you mean the person who writes f?)

**Comment by mykelk** [comment]
Yeah, I was referring to the person who wrote f. Passing in domain knowledge typically means that at the very least they know the MDP/POMDP, but I'm okay with keeping it the way you have it.

**Comment by zsunberg** [comment]
Oh, I should be clear that they will definitely know the TYPE of mdp when writing f, but they will often not know the PARAMETERS or will want to use f for the same mdp type with many different parameters. For example, they may want to use the same solver and f for driving on a four lane road and a five lane road - it will be less confusing and error prone if they don't hard code the number of lanes into f or create a new anonymous function for every number of lanes.

**Comment by zsunberg** [comment]
Alright, I think I'm going to cross my fingers and push those MCTS changes to master because it will be much easier for the students to understand. This doesn't necessarily mean we're committing to anything long term, but it will be good to have the students test it.

**Comment by zsunberg** [comment]
Here is the notebook describing how to use MCTS's new interface: https://github.com/JuliaPOMDP/MCTS.jl/blob/master/notebooks/Domain_Knowledge_Example.ipynb

**Comment by zsunberg** [comment]
Handling domain knowledge with solver-specific interfaces like the one described above for MCTS has worked really well so far. No need to formalize a rigid central interface. Though new solvers should probably try to do things similar to how they have been done in other solvers as a courtesy to the user
