### ISSUE TITLE
Switch to Empty Generic Functions

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#110]
Several of the students in CS238 have had some trouble picking up POMDPs.jl. It is a pretty complex interface right now, so I have been thinking about ways of simplifying it.

I talked to @juliom about it some, and he mentioned that `create_state`, `create_action`, etc., and the optional trailing arguments are confusing and unnecessary for simple problems. It has also been a burden for me to explain these things to other new users.

Moreover @juliom noted that he was surprised by the @pomdp_func macro, and that thing is a little bit clunky.

I also recently learned about some tools for checking what methods are implemented (most importantly `method_exists`) http://docs.julialang.org/en/release-0.5/stdlib/base/#generic-functions, and empty generic functions http://docs.julialang.org/en/release-0.5/manual/methods/#empty-generic-functions.

**What if we just replace all of the @pomdp_func methods in POMDPs with empty generic functions?** Then solvers and simulators can check whether methods are implemented, throw useful errors (we could even have some handy macros for that), and even change behavior slightly depending on whether certain methods (most importantly `create_state` and friends) are available.

Of course, then we would have to *rely on documentation alone* to define the interface. This is terrible if we're constantly making changes, but now that the interface is stable, maybe it is fine.

**Comment by mykelk** [comment]
I'm open to this idea.

**Comment by zsunberg** [comment]
by "throw useful errors", this is what I mean:

POMDPs has something like this defined in it:
```
function require_pomdp_func{S,A,O}(s::Solver, f::Function, p::POMDP{S,A,O})
    # check whether f is defined for typeof(p), S, A, O using method_exists
    # if appropriate method does not exist, throw an error
end
```

and then in the solver package
```
function solve(s::Solver, p::POMDP)
    ...
    require_pomdp_func(s, discount, p)
    require_pomdp_func(s, transition, p)
    ...
end
```

**Comment by juliohm** [comment]
I believe this is the right path :+1: Concepts defined in some sort of documentation with empty generic functions and solver implementations checking the concepts with `method_exists`, `applicable`, etc.

**Comment by juliohm** [comment]
Another alternative a la C++ traits is https://github.com/mauro3/SimpleTraits.jl

This is being discussed on discourse: https://discourse.julialang.org/t/how-to-find-if-a-method-is-implemented-for-an-interface/636.

**Comment by rejuvyesh** [comment]
In principle, yes, something like `traits` or `interface` is the correct construct for defining these. However, since they are not first class primitives in Julia, I think `SimpleTraits` would be an overkill. We don't need the compile time guarantees and type safety offered by another dependency which is honestly not any easier to understand for someone new to the language.

**Comment by juliohm** [comment]
I fully agree, SimpleTraits is overkill, at least for now that we don't have them built-in into Julia.

**Comment by rejuvyesh** [comment]
I guess we could provide a `@pomdp_func` like macro to automate defining these constraints. I believe that we used it in the first place so that solver writers could avoid writing boilerplate error handlers.

**Comment by juliohm** [comment]
It is a matter of deciding who is to write boilerplate code, solver developers or end users. I believe developers writing solvers following `POMDPs.jl` interface shouldn't have a hard time. As a final user, I just care about the solver working with minimum code.

**Comment by zsunberg** [comment]
One thing to keep in mind is that we also want it to be relatively easy to
write solvers, i.e. the final "user" may be a solver writer, so simpler is
better.

I think that empty generic functions, well-maintained docstrings, and good
examples are probably the simplest and most robust way of doing this.

**Comment by zsunberg** [comment]
I looked at SimpleTraits.jl today and it wasn't actually clear to me exactly how we would use this given that different solvers need different functions to be defined. Would we define a trait for each function in the interface and then have a solver assert that the problem writer's POMDP has all the traits? Won't that require the problem writer to understand traits? Can someone offer a better explanation of how we would use traits?

In any case, traits does not appear ready at this point and we should wait until it becomes part of the language to use it.

**Comment by mykelk** [comment]
I'm okay with holding off on traits as you suggest.

**Comment by ChrisRackauckas** [comment]
>Would we define a trait for each function in the interface and then have a solver assert that the problem writer's POMDP has all the traits? Won't that require the problem writer to understand traits? Can someone offer a better explanation of how we would use traits?

It wouldn't require that the problem writer understands traits at all. If you use the method I described here:

https://discourse.julialang.org/t/how-to-find-if-a-method-is-implemented-for-an-interface/636/6?u=chrisrackauckas

the traits are applied automatically at compile-time depending on the methods which are available. There is no user-facing traits at all.

**Comment by zsunberg** [comment]
@ChrisRackauckas thanks. I admit that I kind of skimmed over your answer the first time because it seemed like overkill, haha. If I understand correctly, new types are automatically added to a trait based on whether the required function is implemented (__has_jac() checks whether the function is available in your case), then you can just check the trait and branch code accordingly.

In most cases, we don't have a way of recovering if one of the methods is not implemented - we just have to tell the user that they need to implement it. So instead of moving work to compile time, our challenge is more one of documentation and throwing friendly errors and explaining this all to a class of 200 who barely know how to use julia :). So I think checking methodexists and throwing some nice errors about requirements is sufficient for us.

Thanks for sharing the idea with us - will definitely keep it in mind (and DifferentialEquations.jl looks pretty awesome btw).

**Comment by zsunberg** [comment]
As @rejuvyesh pointed out to me the other day, what we really need is a static analysis tool to automatically extract the requirements for a solver.

**Comment by ChrisRackauckas** [comment]
>In most cases, we don't have a way of recovering if one of the methods is not implemented - we just have to tell the user that they need to implement it. 

Well, once you have the trait set, then you have a function which uses trait dispatch to check for its existence. That's the

```
has_jac{T}(f::T)   = istrait(HasJac{T})
```

which will work at compile-time. But as you say, this may be overkill for your setup. It was developed for the case where you use one code path based on whether the Jacobian exists or not. But if you're just doing a one time check for a method to throw an error, then hitting the methods table directly may not impact performance much at all.

>As @rejuvyesh pointed out to me the other day, what we really need is a static analysis tool to automatically extract the requirements for a solver.

Oh I so wish... maybe someone can make a macro.

**Comment by zsunberg** [comment]
Since this is happening in our version 0.4 and I have implemented it in the version_4 branch, I am closing it.
