### ISSUE TITLE
Rethinking optional final arguments.

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#111]
As I have worked with AA228 students on their projects with POMDPs.jl, I have noticed that our current habit of having optional final arguments and `create_` functions contributes to making POMDPs.jl rather confusing to use.

Here are the reasons that I have noticed:

1) it is difficult to explain to people new to julia who only want to use immutable states.
2) an interface that requires users to implement functions with optional arguments does not feel very crisp
3) it's hard to visually parse functions with long optional argument strings
4) debugging is difficult with more methods to keep track of
5) the default implementations with optional final arguments can lead people to think they need to implement functions that they actually don't need to.
6) It messes up the flow of documentation/learning. We would like to be able to first explain the interface, and then only later talk about optimization, but with the optional final arguments, we have to talk about optimization from the beginning. Since this is partly an educational tool, this is important.
7) It puts the burden of complexity on the problem writer who is usually the least experienced of the types of people using the interface.

Now that we have more experience, I think we should take some time to think about this and see if there is a better way. Does anyone have any thoughts?

**Comment by zsunberg** [comment]
My only idea so far is to work by the following maxim:

If the states/actions/observations are immutable, *always only ever call the version of the function without the preallocated argument*. If the states/actions/observations are mutable, *always only ever call the version of the function with the preallocated argument*.

It's not clear how to easily implement this in solvers/simulators, but it may be possible. Also, it's common for new users to want to use vectors and these are mutable (I guess it's ok for them to learn about pre-allocation from the beginning).

Other issues not resolved by this maxim are what to do about distributions and whether the functions that are always called with a preallocated argument should have a `!`.

**Comment by zsunberg** [comment]
Actually I think the way that we have been doing it so far is essentially useless. See this gist: https://gist.github.com/zsunberg/38142fc6ce46a463788ae64cae76ca31

This was the example that I could think of that would make the most difference, and the time saving from pre-allocating was only 2.8%!!

The reason can be seen here:
```
function generate_sr(mdp::ImageMDP, s::Matrix{Int}, a::Int, rng::AbstractRNG, sp::Matrix{Int}=create_state(mdp))
    copy!(sp, s)
    sp[rand(rng, 1:mdp.size[1]), rand(rng, 1:mdp.size[2])] += a
    return sp, sum(sp)
end
```
Since `sp` is allocated by the caller, there are NO GAURANTEES about it's value, so the `copy!` line is absolutely necessary (and something equivalent will *always* be necessary if the state stores its information efficiently). The copy takes way longer than the allocation, so no gains can be realized.

The only way to get effective performance gains is to **modify** a variable that has a known value when it is given to the function, so something like `step!(s, mdp, a, rng)` that is guaranteed to modify it's first argument is the only thing that makes sense.

**Comment by rejuvyesh** [comment]
Yay! Finally heeding to "premature optimization is the root of all evil".

**Comment by zsunberg** [comment]
Yeah... man... it really is. Wow. can't believe we went this long without realizing that.

using step!() instead takes 0.25 seconds instead of 39.1 seconds with generate_sr... so we do need this.

https://gist.github.com/zsunberg/38142fc6ce46a463788ae64cae76ca31

**Comment by zsunberg** [comment]
Maybe we should just focus on immutables now, and wait for someone (@juliohm maybe) who needs to use big states to figure out how to approach it.

**Comment by tawheeler** [comment]
StaticArrays.jl allows for immutable arrays

**Comment by mykelk** [comment]
Sorry, can you elaborate on why the copy is required? I can think of cases where you might just allocate once, eg in a rollout solver. Right?

**Comment by zsunberg** [comment]
@mykelk if the problem writer has chosen to use a matrix representation for her state, it means that most of the entries in the matrix contain important information (if this is not true, she should have chosen to use a sparse matrix). Since `sp` can be straight from `create_state()` or be reused from somewhere else, there are no gaurantees on what its value will be. Thus, `generate_sr` must set the meaningful entries of it in some way (most entries are meaningful because of the justification above; `copy!` sets every entry of it).

With our current setup, we actually have to allocate twice and then switch between the two states (unless we intended for `s` and `sp` to be the same object... but this introduces tons of other things to think about). See https://github.com/JuliaPOMDP/POMDPToolbox.jl/blob/master/src/simulators/rollout.jl

If we want to switch to only allocating once, we need a function like `step!(s, mdp, a, rng)` where modification of the state object is explicit, and we need to prohibit functions that depend on s and sp like `reward(s, a, sp)` and `observation(mdp, s, a, sp)`.

**Comment by mykelk** [comment]
@zsunberg Got it. Thanks.

**Comment by zsunberg** [comment]
@etotheipluspi, @ebalaban, do you have any objections or misgivings about this?

**Comment by zsunberg** [comment]
To be clear, if this is decided upon, I am thinking of removing the final arguments of `transition()`, `observation()`, `action()`, `rand()`, `actions(mdp, s, acts)`, `update()` and `solve()`, and removing all of the `create_` methods.

**Comment by mykelk** [comment]
I like removing stuff.
