### ISSUE TITLE
Version 0.4

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#112]
Hi guys,

I am thinking that we should make some changes based on what we have learned from having AA228 students use the package and release the changes as version 0.4 in December. In particular, I think 

1) there is no reason not to switch to empty generic functions (#110)
2) and I think, since we don't have a great solution for supporting pre-allocated states, we should not support them for this release (#111).

I'm going to start a branch to work on these changes. Right now is the time to comment on/discuss them. I think it would be good to target getting these changes done by around the new year.

**Comment by mykelk** [comment]
Cool. Thanks for pursuing this.

**Comment by zsunberg** [comment]
I started branches called version_4 in some of the repos to work on this

**Comment by zsunberg** [comment]
OK, I think I am going to merge these changes later this week once the documentation is done. I'll submit PRs to all the solvers to be merged once POMDPs v0.4 drops. These PRs will not contain requirements though - I'll add issues so people remember to do that later.

**Comment by zsunberg** [comment]
Well, at the end of the week, the documentation for this is not quite all done, so I'll actually be merging it after Christmas.
