### ISSUE TITLE
Get rid of AbstractSpace and AbstractDistribution

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#115]
This is pretty radical, I know, but I think I am in favor of getting rid of AbstractSpace{T} and AbstractDistribution{T}.

The two purposes I see for these abstract types are 1) Documentation, and 2) being able to infer the type of the elements by looking at the parameter.

But there is a huge downside to this: You can't use built-in types like vectors for spaces or distributions from Distributions.jl (if JuliaStats/Distributions.jl#436 is ever fixed) directly.

Consider the following code from the Tiger example:
```
type TigerStateSpace <: AbstractSpace
    states::Vector{Bool}
end
states(::TigerPOMDP) = TigerStateSpace([true, false])
iterator(space::TigerStateSpace) = space.states
function rand(rng::AbstractRNG, space::TigerStateSpace, s::Bool)
    p = rand(rng)
    p > 0.5 ? (return true) : (return false)
end

type TigerActionSpace <: AbstractSpace
    actions::Vector{Int64}
end
actions(::TigerPOMDP) = TigerActionSpace([0,1,2])
actions(pomdp::TigerPOMDP, s::Bool, acts::TigerActionSpace=actions(pomdp)) = acts
iterator(space::TigerActionSpace) = space.actions
function rand(rng::AbstractRNG, space::TigerActionSpace, a::Int64)
    a = rand(rng, 0:2)
    return a
end
```

This could all be replaced by
```
states(::TigerPOMDP) = [true, false]
actions(::TigerPOMDP, s::Bool=false) = [0,1,2]
```

Problem writers would still have the exact same flexibility of using any custom type, even distributions from other packages that aren't `AbstractDistribution`s. We could also get rid of the `iterator` function.

This might hurt self-documentation a little bit, since we can't annotate class field names or function arguments to indicate that they are distributions or spaces, but I have actually only used this rarely. Instead, we can document by describing informal interfaces, as in the Julia manual http://docs.julialang.org/en/release-0.5/manual/interfaces/.

Inferring the type could be handled by using `eltype` as julia does optionally with iterators.

What does everyone think?

**Comment by mykelk** [comment]
Cool idea. I'd want consensus from @rejuvyesh @etotheipluspi @tawheeler @ebalaban etc.

**Comment by tawheeler** [comment]
Oh man. If it gets rid of all that extra code that would be wonderful.
I'd say write prototypes for various POMDP problems that we have in the docs to get a sense as to whether something was overlooked.

**Comment by zsunberg** [comment]
From Piazza:

> Sorry, one other thing we've run into - when we run simulate, we get an error about:
>
> Cannot `convert` an object of type Array{Shot,1} to an object of type POMDPs.AbstractSpace{T}
> This is happening in line 35 of POMDPs.jl/src/actions.jl, in the next_action function. Is there an easy fix > for this?

This kind of thing happens all the time and it costs me some explanation time every time. It would not happen if we got rid of these abstract types.

**Comment by zsunberg** [comment]
Hearing no objections, I am going to start getting rid of this for version 0.4. If you are feeling uneasy about it, please speak up, even if the reasons aren't fully formulated yet.

**Comment by zsunberg** [comment]
This is done - PRs coming

**Comment by ebalaban** [comment]
My apologies for commenting on this so late. Was away when this was discussed an am still catching up on some things. I never really liked abstract spaces and distributions, so I am in general supportive of this change. Don't quite remember now why we decided to use them in the first place. Has anyone noticed any adverse performance effects after the switch, however?
