### ISSUE TITLE
Method Requirement Specification

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#117]
Hey guys, cool news: switching to empty generic functions (#110) makes it pretty easy for a solver to check whether the methods it needs are present. I have implemented a way to do this. A solver can check for required functions at solve time as follows (`solve()` just returns true if the requirements are met here):

```julia
module MyModule
    using POMDPs
    
    export CoolSolver, solve

    type CoolSolver <: Solver end

    function POMDPs.solve{S,A,O}(s::CoolSolver, p::POMDP{S,A,O})

        # register requirements
        reqs = RequirementsList("CoolSolver")
        push!(reqs, discount, Tuple{typeof(p)})
        push!(reqs, states, Tuple{typeof(p)})
        push!(reqs, actions, Tuple{typeof(p)})
        push!(reqs, transition, Tuple{typeof(p), S, A})

        # determine the distribution type and register the requirement for rand
        @try_with_reqs begin
            s = first(states(p))
            a = first(actions(p))
            t_dist = transition(p, s, a)
            push!(reqs, rand, Tuple{AbstractRNG, typeof(t_dist)})
        end reqs

        # check requirements and output list if any are missing
        return check_requirements(reqs, output=:ifmissing)
    end
end
```

This will output lists of implemented and missing functions like this:

![image](https://cloud.githubusercontent.com/assets/4240491/20994065/f99fc018-bca2-11e6-94ae-e364065fe5dc.png)

The following screenshot shows a longer example. First the problem writer only implements `discount` (`actions` is already implemented for problems with boolean actions) and tries to run the solver. It tells him that he needs to implement `states` and `transition`, so he implements those. Now the solver knows enough to determine that he also needs `rand` and informs him of this.  Finally once `rand()` has been implemented, all the requirements have been met.

![image](https://cloud.githubusercontent.com/assets/4240491/20994016/b36fb2ba-bca2-11e6-959c-4524850258d8.png)

This is only my first pass, so what feedback do y'all have? Does this seem intuitive enough?

**Comment by mykelk** [comment]
That's pretty cool. But, I think it would be nice to use a macro or something for this to get rid of all the boilerplate stuff. We might want an option to turn off all the debug printouts.

**Comment by zsunberg** [comment]
What do you think the code to specify the requirements should look like? I'm not sure we can eliminate very much boilerplate without requiring a pretty complicated macro. I'm in favor of simplicity for now.

Which of the "debug printouts" do you think we should turn off? I think all of the output is pretty useful.

**Comment by mykelk** [comment]
For batch mode, you should be allowed to turn off all output, even though in general it is helpful.

Maybe something like:
```julia
@POMDP_requirements begin
    discount(::POMDP)
    states(::POMDP)
    actions(::POMDP)
    transition(::POMDP, ::Float64, ::Bool)
end
```

**Comment by zsunberg** [comment]
Oh, yeah, by default there is *only* output if a method is missing (and in that case the solver should fail anyways), and there is an argument in the check_requirements function to completely disable it.

Yes, a macro like that would be easy to write and would get rid of the boilerplate `push!(reqs ...)` lines, but, just to be clear, for a lot of solvers, there will be a great deal more complexity than just one block like that. For example you have to be able to infer the distribution types by calling problem functions as I did above, and you might have different requirements based on different solver types.

**Comment by zsunberg** [comment]
You also might need to infer required functions for another sub-module like the rollout simulator you use in your tree-search solver

**Comment by zsunberg** [comment]
Ok, now specifying requirements looks like this

```julia
function POMDPs.solve{S,A,O}(s::CoolSolver, p::POMDP{S,A,O})

    PTYPE = typeof(p)

    # register requirements
    reqs = RequirementSet("CoolSolver")
    @push_reqs! reqs begin
        discount( ::PTYPE)
        states( ::PTYPE)
        actions( ::PTYPE)
        transition( ::PTYPE, ::S, ::A)
    end

    @try_with_reqs begin
        s = first(states(p))
        a = first(actions(p))
        t_dist = transition(p, s, a)
        @push_req! reqs rand( ::AbstractRNG, ::typeof(t_dist) )
    end reqs

    # check requirements and output list if any are missing
    return check_requirements(reqs, output=:ifmissing)
end
```

And there are other variations:
```julia
# you can use expressions like typeof(p) directly
@push_reqs! reqs begin
    actions( ::typeof(p))
end

# alternative way to push requirements
push!(reqs, @req actions(::typeof(p)) )
```

What do people think?

**Comment by zsunberg** [comment]
Actually, I think we can do it like this
```
function POMDPs.solve{S,A,O}(s::CoolSolver, p::POMDP{S,A,O})

    # register requirements
    @POMDP_requirements begin
        @req discount(::PTYPE)
        @req states(::PTYPE)
        @req actions(::PTYPE)
        @req transition(::PTYPE, ::S, ::A)
        s = first(states(p))
        a = first(actions(p))
        t_dist = transition(p, s, a)
        @req rand( ::AbstractRNG, ::typeof(t_dist))
    end

end
```
and that seems much better. Will take me a little bit of time to implement

**Comment by zsunberg** [comment]
Ok, this is now implemented in the version_4 branch, except that `@POMDP_requirements` actually just returns a `RequirementSet` object that you can check later or pass to someone else. `@check_requirements` automatically performs the check, so it would probably be the appropriate thing to use in the solve() function.

One *slightly* confusing thing about this is that *if you know the details about julia macros*, `@req` doesn't actually function as a macro. In fact if it is expanded or occurs outside of a `@POMDP_requirements` block, it will throw an error. This is because macros "inside" other macros are not expanded by default. All `@POMDP_requirements` does is look for `@req` calls and parse their arguments and create code to appropriately push them to the `RequirementSet`. I think this is fine, just possibly worth noting.

**Comment by zsunberg** [comment]
Eventually we need to create an interface for getting requirements from another dependency. For example if a solver uses a `RolloutSimulator` it should be able to do something like
```julia
my_reqs = @POMDP_requirements "MySolver" begin
    # ...
end

merge!(my_reqs, requirements(RolloutSimulator, pomdp)
check_requirements(my_reqs, output=:ifmissing)
```

**Comment by zsunberg** [comment]
This requirements thing turned out to be a whole lot more complicated than I thought, but I think it is very important from a usability standpoint because the first thing everyone asks when using the interface is "what functions do I need to implement?"

I now have a working system, so we can decide whether we are happy with it.

I think that the only sane way to talk about requirements is actually in terms of function calls. So, requirements are declared by defining a `get_requirements(f::Function, args::Tuple{...})` function. There is a convenience macro called `@POMDP_require` for doing this. A real-world complete example (for DiscreteValueIteration.jl) looks like this:

```julia
@POMDP_require solve(solver::ValueIterationSolver, mdp::Union{MDP,POMDP}) begin
    P = typeof(mdp)
    S = state_type(P)
    A = action_type(P)
    @req discount(::P)
    @req n_states(::P)
    @req n_actions(::P)
    @subreq ordered_states(mdp)
    @subreq ordered_actions(mdp)
    @req transition(::P,::S,::A)
    @req reward(::P,::S,::A,::S)
    @req state_index(::P,::S)
    as = actions(mdp)
    ss = states(mdp)
    @req iterator(::typeof(as))
    @req iterator(::typeof(ss))
    s = first(iterator(ss))
    a = first(iterator(as))
    dist = transition(mdp, s, a)
    D = typeof(dist)
    @req iterator(::D)
    @req pdf(::D,::S)
end
```

The `@show_requirements` macro can then be used to check requirements. For a complete problem, it will look like this:

![image](https://cloud.githubusercontent.com/assets/4240491/21336924/b66dbc26-c61d-11e6-87d8-efff33bce3f0.png)

For an empty problem, it will look like this:

![image](https://cloud.githubusercontent.com/assets/4240491/21336991/3e70e166-c61e-11e6-8b02-9358dbd782c2.png)

What do you guys think? Do you have any questions? Is this good enough for the version 0.4 release?

**Comment by mykelk** [comment]
I like it.
