### ISSUE TITLE
Really slick policy interface

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#129]
Check this out: a quick and dirty (but very lucid) syntax for specifying and simulating a policy could be

```julia
mdp = GridWorld()
sim(mdp) do s
    # code that calculates action a based on s - this is the policy
    return a
end
```

That way, you can get to hacking without defining a policy object or action function. pretty slick, right?

This wouldn't mean any changes to the current interface, and `sim` would just reside in `POMDPToolbox`. I think `sim` would return an object with the history.

The implementation would be something like
```julia
sim(policy::Function, mdp::MDP, is=initial_state(mdp, GLOBAL_RNG))
    pol_obj = FunctionPolicy(policy)
    sim = HistoryRecorder()
    return simulate(sim, mdp, pol_obj, is)
end
```

We could also have a `val(::Function, ::MDP)` that could return the value. I also foresee that people will want to do visualization in the do block, and this is actually a very convenient way of exposing the ability to do that at every timestep.

Anybody have any comments/objections?

**Comment by zsunberg** [comment]
I always feel like there is a need for a way to "hook into" the simulation from the outside, and I think this is it!

**Comment by mykelk** [comment]
This is nice!

**Comment by zsunberg** [comment]
For POMDPs, I guess the input to the do block should be `o` and they can do belief updates in the do block. That's sketchy because they will have their belief as a global variable persisting between function calls, but this is just hacky syntactic sugar anyways - if they want to write good, safe, reusable code, they should use the full low level original interface.

**Comment by zsunberg** [comment]
This has been implemented, will update some documentation so people can find it

**Comment by zsunberg** [comment]
FYI I added a few lines to show people this interface in the README. I think it adds a really clear way to interact with a POMDP, but we also need to keep the README as concise as possible. Does anybody think it does not belong in there?
