### ISSUE TITLE
Someday... Documentation/warnings about missing functions and explicit importing

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#13]
Printing an error when a function is not implemented for a POMDP model is good, but we need to make sure that we have clear documentation about explicitly importing the functions that you are implementing - it is rather confusing if you have, for example, `reward()` clearly written in CustomPOMDP.jl, but you are getting the error `CustomPOMDP does not implement reward` because you didn't explicitly import `POMDPs.reward`.

In addition to documentation, we might also improve the error messages (e.g. by printing out the currently available methods of the function) or even implement a simple lint-like tool to help users.

I realize this is down the line a ways, but writing this out in an issue makes me feel more at peace that it will get done in the future.

**Comment by etotheipluspi** [comment]
It seems like @zsunberg took care of this in ccc969947bcb42cceab5f4ac43ceede62ce8dc7e. Closing this issue.
