### ISSUE TITLE
Do not add unregistered packages via Pkg during Pkg.test("POMDPs")

### ISSUE THREAD

**Issue by tkelman** [JuliaPOMDP/POMDPs.jl#130]
`Pkg` should never be invoked by package code, only by users. Dependencies should be declared in `REQUIRE` or `test/REQUIRE`, and unregistered packages should not be cloned. You can download them as local resources, but particularly since unregistered packages don't do versioning, you're not going to get reproducible behavior and nothing will get cleaned up properly if POMDPs gets removed.

Pkg3 will have better support for local registries and sets of packages, but for now anything that's a regular test dependency that's needed for `Pkg.test("POMDPs")` to pass should be restricted to registered packages and use REQUIRE files.

**Comment by zsunberg** [comment]
Hi @tkelman , is this just an issue with the testing, or would you prefer that we remove all use of Pkg for adding solvers (not automatically when you install POMDPs, but later as they are needed)?

If we moved away from that, we would need to either register all of the solvers or create some other mechanism for installing them.

I am working on fixing the testing part now.

**Comment by tkelman** [comment]
It's fine to have opt-in for now.

**Comment by zsunberg** [comment]
Ok I removed the dependencies from the test. Can't wait for Pkg3! is there any central place we can track development of that feature? The Julep doesn't seem to talk about a timeline (sorry if this is obvious).

**Comment by tkelman** [comment]
Good question. Not sure exactly where the repo's going to go while it's being worked on, but check every so often whether https://github.com/StefanKarpinski/Pkg3.jl becomes not-a-404 maybe?

**Comment by zsunberg** [comment]
Ok, thanks, we'll be on the lookout.
