### ISSUE TITLE
Add ParticleFilters.jl, get rid of particle filter in POMDPToolbox

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#132]
Hey guys, I made a ParticleFilters.jl package here https://github.com/zsunberg/ParticleFilters.jl Does anyone object to adding it to the JuliaPOMDP organization and getting rid of the old particle filter in POMDPToolbox?

**Comment by mykelk** [comment]
Wow. This is lovely. I'm supportive of this idea. Is anyone using the old particle filter? Should we stick in some kind of deprecation warning or error?

**Comment by zsunberg** [comment]
I added a warning saying that the old one is deprecated
