### ISSUE TITLE
Adding LightDarkPOMDPs.jl

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#133]
I created a set of LightDark problems here https://github.com/zsunberg/LightDarkPOMDPs.jl . Should we add it to JuliaPOMDP? And should we add it as a separate package or fold it into POMPDModels.jl I think I am in favor of starting to add problems as separate packages.

**Comment by zsunberg** [comment]
Of course there should be some simple documentation in the README before adding it.

**Comment by mykelk** [comment]
It could be its own separate package. If you do that, then it might be good to add a table to the POMDPs.jl readme listing the various model packages.

**Comment by etotheipluspi** [comment]
This looks great! I'm glad we're getting more continuous domains as examples. 

I am against having separate packages for each individual model (at least for now). Decomposing POMDPModels would require 7 new packages :O 

I do think that it might get unsustainable to keep adding new problems to POMDPModels. An alternative idea would be to group problems into packages depending on the problem type. For example, `DiscreteMDPProblems`, `ContinuousPOMDPProblems`, etc.

**Comment by ebalaban** [comment]
Thanks, @zsunberg, for adding this. I like @etotheipluspi's idea of starting to group problems by their types, while perhaps keeping a full list of them in the POMDPs.jl documentation.

**Comment by zsunberg** [comment]
Put this in POMDPGallery
