### ISSUE TITLE
Get rid of POMDPBounds?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#134]
Does anyone object to getting rid of POMDPBounds? AFAIK, the only solver that uses it right now is MCVI.

Even though I was a strong proponent of it originally, I now think that it doesn't solve a pressing problem and in fact introduces some unnecessary complexity. In particular, since Julia does not allow multiple inheritance, introducing new abstract types for secondary concepts usually makes it harder to write code. I can elaborate more if necessary, but if everyone agrees, I don't want to spend the time laying it out in detail.

I think solver-specific (but as uniform as possible) domain knowledge interfaces, as described in #109 are perfectly adequate, and bounds are not special enough to warrant their own package.

**Comment by ebalaban** [comment]
I am not opposed to shelving POMDPBounds and DomainKnowledge for now. We can revisit in a few months and see what patterns are emerging for our various solvers.

**Comment by zsunberg** [comment]
I'm going to do this on Friday (get rid of the package, and remove MCVI's dependence on it) unless anyone has objections. If anyone wants more time to think about it, let me know.

**Comment by etotheipluspi** [comment]
Just a heads up, @apoorva-sharma noticed that LightDark in `POMDPModels` also has a POMDPBounds dependency.
