### ISSUE TITLE
Add a Reinforcement Learning Tutorial

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#138]
I just added [TabularTDLearning.jl](https://github.com/JuliaPOMDP/TabularTDLearning.jl) to the supported packages list. Deep reinforcement learning is next!

It would be great if we could have a notebook that shows how to define a problem in the `GenerativeModels.jl` format and use it with `TabularTDLearning`.

**Comment by MaximeBouton** [comment]
Should we add a link to [this tutorial](https://github.com/JuliaPOMDP/POMDPs.jl/tree/master/examples/rl-tuto) in the readme and close this issue?

**Comment by zsunberg** [comment]
Yeah, sounds good. Might be worth quickly verifying that it still works
first. - Zach

**Comment by zsunberg** [comment]
#182
