### ISSUE TITLE
POMDPReinforce is Here!

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#142]
Hi Everyone,

I threw together a wrapper of the following form `POMDPs.jl` -> `Reinforce.jl`. You can find it [here](https://github.com/JuliaPOMDP/POMDPReinforce.jl). The idea is to unify Reinforce.jl (for which deep reinforcement learning algs will be implemented) and POMDPs.jl. This will allow users who've written their problems in our POMDPs.jl format to use deep reinforcement learning (cause why not?). Zach and I had an in depth discussion about this, and we think that if any of us (POMDPs.jl devs) write a DRL solver we should do it in the Reinforce.jl format. IMO this is the best way forward and gives more users access to our solvers. 

The wrapper is fairly simple, and makes use of the generate interface. Please take a look, and let me know if something doesn't make sense. 

I will say that there are a few issues with the `Reinfroce.jl` package and the wrapper that I would like some opinions on. Here they are:

1. Interface inconsistencies: Reinforce.jl has some minor inconstancies with the OpenAI gym interface, see JuliaML/Reinforce.jl#10. Resolving these inconsistencies would prevent confusion for users coming over from gym.
2. Policy: the `action` method has the following form: `a = action(policy, r, s, A)` where `r` is the current reward and `A` is the action space. I'm a purist, and don't agree with the action being dependent on the reward. I can live with passing in the action space `A` into the `action` method. 
3. Clashing method definitions: both `POMDPs` and `Reinforce` export `reward`, `actions`, `action` and `update` functions which leads to warnings when both are exported. 
```
WARNING: both Reinforce and POMDPs export "actions"; uses of it in module Main must be qualified
``` 
I'm not sure what the best way to resolve this warning is without requiring one package to depend on another.

**Comment by zsunberg** [comment]
@etotheipluspi excited to take a look at this - I'll probably get to it on Tuesday.

**Comment by JobJob** [comment]
Haven't looked at this or POMDPReinforce but just regarding 2. above - I think `action(...)` is the only interaction point between the env and the policy, so any policy training method that needs the reward from the previous step, e.g. to update its internal parameters, has to get that `r` somewhere, and to me, passing it there seems reasonable. Though maybe you have another idea in mind?

**Comment by zsunberg** [comment]
Hi @JobJob, thanks for the comment. In the task of solving an MDP, we assume that the policy is either a static mapping from states to actions, or, in the case of an online planner like MCTS, the planner has a (possibly incorrect) model of the MDP within it, so the reward can be calculated from the state. This is different from the task of a reinforcement learning problem. In POMDPs.jl I think a reinforcement learning problem would be best coded as a POMDP where the observation contains the reward.

I think that the way we have it is the best way in terms of educating and doing research on solving MDPs, but this would perhaps be annoyoing/confusing to new users coming from an RL perspective. Anyone have any other thoughts?
