### ISSUE TITLE
add observation(pomdp::POMDP, sp::S)

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#143]
In some cases, e.g. MCVI (https://github.com/JuliaPOMDP/MCVI.jl/blob/master/src/subspace.jl#L35), it seems we need to know the observation distribution given only a state (without an action).

If this is the case we should add `observation(pomdp::POMDP, sp::S)` to the interface.

Are there any objections/does anyone see any problems with this?

**Comment by etotheipluspi** [comment]
I'm ok with this. 

Would there be a default call in `POMDPs.jl` like
```julia
observation(pomdp::POMDP, a::A, s::S) = observation(pomdp::POMDP, s::S)
```

or would the user be required to specify both the `observation(pomdp, a, s)` and the `observation(pomdp, s)` methods?

**Comment by ebalaban** [comment]
I am fine with this also. In fact, we should have had it from the start. Either the definition suggested by @etotheipluspi or a requirement to implement both methods are ok with me.

**Comment by zsunberg** [comment]
Yes, @etotheipluspi  there would be a default. The only downside to this is that solver writers will tend to want to use it when they don't have to - we need to really encourage solver writers to use the methods with the most arguments to make them as broadly compatible as possible.
