### ISSUE TITLE
Conflict POMDPs.jl and @manipulate

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/POMDPs.jl#144]
Hello,
I have experienced a conflict between the two package above. I think it is due to the name confilct with the function value. I am not sure what would be a good solution.

This is the message I got when running @manipulate on a IJulia notebook with POMDPs.jl in my workspace:
```

WARNING: both Reactive and POMDPs export "value"; uses of it in module Main must be qualified
UndefVarError: value not defined

 in display_dict(::Reactive.Signal{Any}) at C:\Users\Maxime\.julia\v0.5\Interact\src\IJulia\setup.jl:97
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at C:\Users\Maxime\.julia\v0.5\IJulia\src\execute_request.jl:187
 in eventloop(::ZMQ.Socket) at C:\Users\Maxime\.julia\v0.5\IJulia\src\eventloop.jl:8
 in (::IJulia.##13#19)() at .\task.jl:360
```

**Comment by zsunberg** [comment]
Yeah, that is kind of annoying; I have run into it too.

Easiest fix is to only import the specific functions you need from POMDPs,
e.g.
```
using POMDPs: simulate
using Interact
```

I suspect that the root of the problem has to do with poor macro hygiene in
Interact's @manipulate. You could file a bug at their repo or investigate
it yourself and make a pull request. I don't think there is any change to
POMDPs that can fix it easily.

**Comment by zsunberg** [comment]
Closing this because I don't think there is a way to fix it from the POMDPs side. Feel free to reopen if I am mistaken.
