### ISSUE TITLE
setrng!

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#145]
I have found it very common to need to set the random number generator for Simulators, Solvers, and Policies. I think we should add a standard way to do this:

```julia
setrng!(::Simulator, ::AbstractRNG)
setrng!(::Solver, ::AbstractRNG)
setrng!(::Policy, ::AbstractRNG)
```

There will be default implementations that silently do nothing. I think this is a better alternative to #105.

Does anyone have any objections or bad feelings about this?

**Comment by zsunberg** [comment]
I think I am going to put this in before Juliacon... ugh - it is really hard to predict what is a good idea and what is not

**Comment by zsunberg** [comment]
actually this isn't absolutely needed right now, so I am going to hold off for now.

**Comment by zsunberg** [comment]
`srand` would probably be better than setrng because then all these things could be immutable

**Comment by mykelk** [comment]
Seeding a random generator is not the same thing as setting a random number generator.

**Comment by zsunberg** [comment]
Yeah my point is that we should actually be seeding it instead of setting it

**Comment by zsunberg** [comment]
Since srand is in Base, it doesn't really need to go in this package. I recommend people implement it for solvers and policies that are nondeterministic, but it needn't be part of the official interface
