### ISSUE TITLE
Repository for problems

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#146]
I have developed a few models while working on POMCPOW that will be useful for demonstrations - they have gifs and everything. I think it would be useful to have a central list of these. Where should we put them? Should POMDPs.jl just have them in it accessible from POMDPs.add? or should there be POMDPGallery.jl that has visualizations and a brief description in the readme?

**Comment by mykelk** [comment]
They might go into their separate repos and then linked to from POMDPGallery.jl. And POMDPs.jl should link to POMDPGallery. I like the idea of visualizations.
