### ISSUE TITLE
"Probabilistic" instead of "Explicit" for interface with explicit probability distributions

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#148]
During juliacon, I was thinking that "Probabilistic" rather than "Explicit" might be a better word to use for the interface by which transition and observation probability distributions are defined explicityl.

I thought of this because it seems similar to probabilistic programming languages. However, I don't actually have much experience with probabilistic programming languages, and it may be misleading. For example, in the implementations we have written so far, the state is a value rather than a random variable, and I think in a PPL paradigm it would be an RV.

Just thought I'd throw this out there since there has been confusion about the terms.

**Comment by mykelk** [comment]
I think this is a good thing to discuss. I think what he have is pretty standard, even though some students might be confused at first. I would say that probabilistic is a general class that would include both what we call explicit and generative.

**Comment by zsunberg** [comment]
Sticking with explicit seems like it was the right thing to do
