### ISSUE TITLE
Got rid of Policy and Updater parameters

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#153]
Since the policy abstract type has a parameter (representing the state or belief type that it is designed to operate on), the following is no longer possible in 0.6:
```julia
struct MyPolicy <: Policy end
```

I don't think I have never actually used the parameter of Policy for anything, and most policies can handle multiple belief types, so I don't think the parameter is necessary. We removed it in the 0.6 branch.

Does anyone have any objections to this?

**Comment by zsunberg** [comment]
Same for Updater

**Comment by zsunberg** [comment]
This has been completed, but leaving open because I think the right thing to do would have been to have `Updater{B}` where B is the type of belief that the updater returns. But I am too unsure about this to go to the trouble of implementing it.

**Comment by MaximeBouton** [comment]
What is the advantage of having a parameter here?

**Comment by zsunberg** [comment]
We could have
```
belief_type(::Type{Updater{B}}) where B = B
```

**Comment by MaximeBouton** [comment]
Yes but where would you use this?

**Comment by zsunberg** [comment]
Maybe places like this?: https://github.com/JuliaPOMDP/POMDPSimulators.jl/blob/master/src/history_recorder.jl#L107

It also seems good for communication for everyone for an updater to declare what type of belief it intends to use.

It is definitely not strictly necessary though - I'm not sure what the right answer is.

**Comment by zsunberg** [comment]
It might be hard to have this parameter for certain updaters like the PreviousObservationUpdater or KMarkovUpdater

**Comment by lassepe** [comment]
Well if no one really missed it and we have a hard to time come up with a good use-case for this we should not bother about introducing it. I think for the few cases where this is desired, we can handle it differently and one can open an issue once there is a class of problems/solvers/updaters that really needs this.

I would vote for simplicity now. Having to set potentially redundant parameters when deriving a struct from these types is more annoying than the value that this adds.
