### ISSUE TITLE
Should n_actions and n_observations be functions of the state?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#154]
Since actions() and observations() can return different things for different states, should n_actions and n_observations also return different numbers depending on the state?

**Comment by mykelk** [comment]
I think it is really helpful to have different actions and observations available depending on the state. But, I don't know whether n_actions / n_observations are useful without knowing which actions and observations are available.

**Comment by zsunberg** [comment]
maybe we should just have `length` be part of the interface for space objects?

**Comment by zsunberg** [comment]
It's not actually that important. Probably will only rarely, if ever, get used. But it is a little inconsistent. Is it better for interface developers to pick and choose the functions they think will be useful, or make sure the interface is complete with every permutation of use cases?

**Comment by lassepe** [comment]
`n_actions` and `n_observations` deprecated starting from version 0.8. I'm closing this.
