### ISSUE TITLE
`generate_sor()` only works by composition?

### ISSUE THREAD

**Issue by ebalaban** [JuliaPOMDP/POMDPs.jl#155]
@zsunberg, looking at the code in `generative_impl.jl`, it appears that `generate_sor` will only work properly if `generate_so` or `generate_sr` (with the associated functions) are implemented. Am I misunderstanding something here? Do we not allow a user-implemented `generate_sor`? Have I, perhaps, missed a discussion on this?

**Comment by zsunberg** [comment]
The user should be able to implement generate_sor directly.

**Comment by zsunberg** [comment]
Is there somewhere where it's not working?

**Comment by ebalaban** [comment]
I got back to a piece of code where `generate_sor` is implemented (used to work fine) and after updating POMDPs.jl started getting the warning about `generate_sor` not found and not synthesized. Both methods (POMDPs.jl and mine) are visible from the calling location. Weird. Probably some oversight on my part. I'll dig around some more and close this issue if it turns out to be my fault.

**Comment by zsunberg** [comment]
@ebalaban Were you using 0.5 or 0.6 when this happened? I am encountering a possibly-related bug in some corner cases on 0.6.

**Comment by ebalaban** [comment]
I was using 0.5. Have not had a chance to fully track it down yet, but most likely the problem is somewhere on my end.

**Comment by ebalaban** [comment]
Turned out to be indeed an error on my part.
