### ISSUE TITLE
"no method matching generate_s"

### ISSUE THREAD

**Issue by bisraelsen** [JuliaPOMDP/POMDPs.jl#169]
Hey,

I'm trying to call `generate_s` manually in order to debug it. But when I try to do so using `MersenneTwister` or `Base.GLOBAL_RNG` I get the following error:

```
ERROR: MethodError: no method matching generate_s(::BabyPOMDP, ::Bool, ::Bool, ::Bool, ::MersenneTwister)
Closest candidates are:
generate_s(::BabyPOMDP, ::Bool, ::Bool, ::AbstractRNG) at home/brett/GitProjects/self_confidence/road_net/baby_problem.jl:18
generate_s(::Union{POMDPs.MDP, POMDPs.POMDP}, ::Any, ::Any, ::AbstractRNG) at /home/brett/.julia/v0.6/POMDPs/src/generative_impl.jl:18
```

I guess I'm not sure how to pass an `AbstractRNG`... probably a weakness in my Julia knowledge.

**Comment by zsunberg** [comment]
Hmm... can you show me the code where you call `generate_s`? The correct way to call it is, for example,

```julia
rng = Base.GLOBAL_RNG
pomdp = BabyPOMDP()
s = true
a = true
sp = generate_s(pomdp, s, a, rng)
```
It looks like you are passing three bools - not sure what the third one is.

**Comment by bisraelsen** [comment]
You're right. I was mixing up the call with another non-baby POMDP problem that has 3 bools.

Regardless, calling directly with `MersenneTwister` (in the baby problem or otherwise) does not work; `typeof(MersenneTwister)` is `DataType`. Whereas calling with `Base.GLOBAL_RNG` or `MersenneTwister(xxx)` (replacing `xxx` with some integer) does; `typeof(Base.GLOBAL_RNG)` and `typeof(MersenneTwister(xxx)` are `MersenneTwister`.

So it turns out the solution was being confounded because of two simultaneous problems.

Sorry for so many basic questions. Thanks!!

**Comment by zsunberg** [comment]
Cool - glad you figured it out!
