### ISSUE TITLE
Discrete Belief Rewrite

### ISSUE THREAD

**Issue by dressel** [JuliaPOMDP/POMDPs.jl#173]
After discussing with @zsunberg it seems like the current DiscreteBelief in POMDPToolbox does not conform to the package's general way of doing things. As it is currently set up, DiscreteBelief only works for problems where the state is an integer. But often you have a discrete state space and you'd rather represent the states as any type.

This should be a core feature of POMDPs.jl. I do not want to write a new belief type and updater for each problem I look at. Seeing as a ton of POMDP research uses discrete beliefs, this type should exist.

I wrote up what this might look like [here](https://gist.github.com/dressel/b5f44535df5c4ca244e6b8f733184769). Unfortunately we need to carry a list of states in each state, but @zsunberg thinks this won't be too bad because the reference will just be copied and we won't have to call ordered_states multiple times. 

I'm mostly looking for @zsunberg to verify that this is what we want so I can pull request on POMDPToolbox.

EDIT: Also, it is not immediately clear what needs to be implemented when defining your own belief and updater. I think having a concise list of the required methods in the documentation would be helpful. As is, it's a bunch of paragraphs with some methods mentioned but it does not give me a clear sense of what is needed.

**Comment by zsunberg** [comment]
Thanks for preparing this.

Just go ahead and submit it as a pull request to POMDPToolbox, and then request a review from me. The github PR interface has tools to leave line-by-line comments, etc. The informal convention is to put "WIP" for  "work in progress" if you don't think it's quite ready to merge yet.

**Comment by zsunberg** [comment]
And I'll update the updater docs tomorrow

**Comment by zsunberg** [comment]
@dressel , what do you think about these docs for belief updaters? http://juliapomdp.github.io/POMDPs.jl/latest/def_updater/ too verbose? Is the example OK without actual probability updates?

**Comment by dressel** [comment]
This looks a lot better! It gives me a clear view of what's needed by an updater/belief. I think it's ok like this (without updates).

**Comment by zsunberg** [comment]
Only thing that's needed left for this is to document the usage on POMDPToolbox.

**Comment by zsunberg** [comment]
Hey @dressel can you add a few sentences of documentation about DiscreteBelief to the POMDPToolbox README? Maybe just a quick usage example. Right now there's not really anything that shows how to use it. Thanks!
