### ISSUE TITLE
Documentation about running simulations

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#181]
There currently isn't really any documentation about running simulations. We should probably have this.

**Comment by zsunberg** [comment]
The simulators are implemented in POMDPToolbox, so one question is whether we should put the documentation there or here. I think it's fundamental enough to go here in POMDPs.

**Comment by rejuvyesh** [comment]
We should probably pull out simulators from the toolbox then. It already is pretty unwieldy. We can then potentially link to the documentation there.

**Comment by zsunberg** [comment]
I agree. POMDPSimulators.jl is probably in order
