### ISSUE TITLE
Comitted Tiger Example Notebook appears to have a problem

### ISSUE THREAD

**Issue by hoehleatsu** [JuliaPOMDP/POMDPs.jl#190]
I just read through https://github.com/JuliaPOMDP/POMDPs.jl/blob/master/examples/Tiger.ipynb and noticed, that the committed notebook somewhere down the line, where the SARSOP solver is used appears to have a problem. I'm too little knowledgable about the internals, so I'm unable to tell what's wrong, but since the example appears in different form somewhere else it might just needs some simple massing. Just wanted to point this out.

**Comment by zsunberg** [comment]
Hi @hoehleatsu , thanks for reporting this! Looks like @MaximeBouton had just run it with his local modified copy of POMDPToolbox, which caused errors. Rerunning seemed to fix the problem.

**Comment by hoehleatsu** [comment]
Great, thanks!
