### ISSUE TITLE
state-action value function

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#194]
Should we add a standard state-action value function `value(policy, s, a)`? I think we should add this.

**Comment by zsunberg** [comment]
Or should it be called `qvalue`? I think academics would like `value` more, but `qvalue` might help new users understand what it is more easily.

**Comment by mykelk** [comment]
[Here](http://incompleteideas.net/RL-FAQ.html#Q-value) is one opinion.

**Comment by zsunberg** [comment]
Ah yes, that's what I was remembering when I said academics would like `value`. The ambiguity that he complains about isn't really present here though because it's clear that it's the qvalue for that particular policy.

**Comment by MaximeBouton** [comment]
I am not sure if  `qvalue` is easier to understand than `value`. Adding it to the interface is a good idea!
