### ISSUE TITLE
New documentation strategy

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#205]
Now that things are more stable and we have broken things into smaller packages, I think it is time to up our documentation game.

Here is my proposal:
1. There should be an unregistered POMDPExamples package with many individual examples in ipython notebooks all in one place. There will be no tutorials hosted directly on POMDPs.jl
  Notes:
    - Some of these examples should be tutorials - however the tutorials should *only* cover POMDPs and *not* how to program in Julia; we should link to julia docs for that.
    - We should run travis testing on these notebooks to ensure that they always work
2. The components of each *registered* package should have appropriate docstrings, and individual documentation of each tool should be provided via Documenter.jl, however extended examples should be in POMDPExamples.jl
3. Each *unregistered* package (e.g. solver) is responsible for it's own documentation with examples, etc. Minimum is one usage example and solver docstring that gives options. Documenter.jl is recommended but not required.

Any comments?

**Comment by zsunberg** [comment]
How should we document POMDPModels?

**Comment by MaximeBouton** [comment]
I love this plan! 
One tricky thing might be the distinction POMDPExamples and POMDPModels.
What about your POMDPGallery?

Each model in POMDPModels should have: 
- A docstring explaining the parameters of the main POMDP/MDP type 
- A documentation on the state type and representation, not sure when and how?
- A few line describing the problem

I am not sure what is the best way to organize the documentation, is Documenter.jl relevant for this?

**Comment by zsunberg** [comment]
Yes!, but coming up with a good visualization interface seems very hard #107

**Comment by zsunberg** [comment]
Hmm... One problem with using Documenter.jl for everything is that cross-referencing between documentation in different packages might be a pain - I guess we should try to keep that to a minimum

**Comment by zsunberg** [comment]
What should the Examples consist of? Should they all be notebooks, or should we try something with Literate.jl so that we are not tied to notebooks?

**Comment by zsunberg** [comment]
This is being tracked in #208
