### ISSUE TITLE
Module `Random` not found in current path

### ISSUE THREAD

**Issue by bisraelsen** [JuliaPOMDP/POMDPs.jl#206]
I'm not sure what is happening, but I just ran into this error. I have run code from this path before. I am pretty sure I haven't updated anything recently (although I am beginning to second guess myself). Any ideas?
```julia
julia> using POMDPs
ERROR: LoadError: ArgumentError: Module Random not found in current path.
Run `Pkg.add("Random")` to install the Random package.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:435
 [2] require(::Symbol) at ./loading.jl:405
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] eval(::Module, ::Any) at ./boot.jl:235
 [5] _require(::Symbol) at ./loading.jl:490
 [6] require(::Symbol) at ./loading.jl:405
while loading /home/brett/.julia/v0.6/POMDPs/src/POMDPs.jl, in expression starting on line 6
```

Output of `Pkg.status()` and `versioninfo()`
```julia
julia> Pkg.status("POMDPs")
 - POMDPs                        0.7.1+             master

julia> versioninfo()
Julia Version 0.6.3
Commit d55cadc350 (2018-05-28 20:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by zsunberg** [comment]
Hi Brett, POMDPs.jl v0.7.0 and higher will only work on julia 0.7 or higher. That being said, you should not upgrade yet since we haven't finished updating the whole ecosystem.

```
julia> Pkg.free("POMDPs")
```
should downgrade you to a version of POMDPs compatible with julia 0.6

**Comment by bisraelsen** [comment]
As I suspected...I must have done a `Pkg.update()` without thinking of the consequences. Thanks!!

BTW, I'd like to help getting everything working with `v1.0.0` but am not sure where I can be helpful.

**Comment by zsunberg** [comment]
Thanks for volunteering to help with the upgrade - we are currently experiencing a lot of delays with registering packages to METADATA since we broke up POMDPToolbox into smaller packages. I'll let you know when all those are registered and maybe you can help with a solver package or two.

**Comment by zsunberg** [comment]
Hi Brett,

If you want to help with the upgrades to v1.0, there is now a checklist: https://github.com/JuliaPOMDP/POMDPs.jl/issues/207
(and one for documentation: https://github.com/JuliaPOMDP/POMDPs.jl/issues/208). If there is a solver that you'd like to work on, just put your username next to it - we'd love your help! (sorry that things are kind of a dependency mess right now)
