### ISSUE TITLE
Error POMDPs.add_all() and POMDPs.add("QMDP")

### ISSUE THREAD

**Issue by songanz** [JuliaPOMDP/POMDPs.jl#210]
Hi,
Thank you very much for providing this package~ I am new to Julia. 

When I am trying to run `POMDPs.add_all()` and `POMDPs.add("QMDP")`, it says:  GitError(Code:ERROR, Class:Merge, There is no tracking information for the current branch.). What should I do?

**Comment by rejuvyesh** [comment]
What julia version are you on?

**Comment by zsunberg** [comment]
Hey @songanz , sorry that you have run into all these challenges, haha, we are trying to upgrade to 1.0 and making all the changes
