### ISSUE TITLE
Change the distribution interface to be more julian?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#216]
Someone needs to review this section of the julia documentation: https://docs.julialang.org/en/v1/stdlib/Random/#Hooking-into-the-Random-API-1 and decide whether we should change the [POMDPs.jl distribution interface](https://juliapomdp.github.io/POMDPs.jl/latest/interfaces/#Distributions-1) accordingly. #214 is part of this.

**Comment by lassepe** [comment]
Has any work been started on this?

**Comment by zsunberg** [comment]
No, I don't think anyone has started working on this. I don't actually think there will be any changes to the code in POMDPs.jl for this. We just need to
1) Look at the julia docs and decide what people should implement for a new distribution - should it be `rand(rng, d)` or `Random.Sampler(d)`?
2) Document that in the POMDPs documentation
3) Fix core packages that define distributions

**Comment by zsunberg** [comment]
It looks like Distributions.jl just implements rand(rng, d) directly. so maybe we don't need to change anything other than #214

**Comment by zsunberg** [comment]
It is pretty unclear what to do here - the Distributions.jl interface is focused on numeric types, and the julia interface is very complicated. For now, I am leaning towards just saying that POMDPs.jl only uses one method of rand: `rand(rng, d)`, and that is the only method that distribution-writers need to implement.

**Comment by lassepe** [comment]
Agreed. It makes sense to keep the required interface as small as possible and wait for the smoke to clear.
