### ISSUE TITLE
observation-dependent action space

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#226]
It is often the case that the set of actions that one can take in a POMDP is dependent upon a fully-observable part of the state. It seems like it would thus be convenient to have an `actions` method that is dependent on the observation.

This is a bit of a complicated design choice because, in general, the action set could be dependent on the history of actions and observations or the current belief. Either of these is more complicated to implement though.

@Shushman is currently encountering this problem in his work.

**Comment by MaximeBouton** [comment]
If it is dependent on a fully-observable part of the state, doesn't `action(pomdp, s)` capture that behavior?

**Comment by MaximeBouton** [comment]
isn't this a solver writing issue more than an interface design?

**Comment by zsunberg** [comment]
It is an interface issue because a solver may have access to the
observation when deciding what actions to consider without knowing the true
state.

**Comment by zsunberg** [comment]
I wonder if this has issues similar to #48

**Comment by zsunberg** [comment]
@lassepe and I have been talking about this a fair amount.

Which of these seems best for accessing the last observation in the history that leads up to belief/belief node `b`?

1. `lastobs(b)` or `currentobs(b)`
2. `o_history(b)[end]`
3. `history(b, Val(:o))[end]`
4. `history(b)[end].o`

I think all of them could be implemented efficiently in the tree-based solvers - it's really a question of what is easiest to understand/remember and how we want to interact with histories in a broader sense.

**Comment by zsunberg** [comment]
I guess I kind of like 4 best - a "history" is an array-like structure made up of `NamedTuples`. This is similar to the history concept in POMDPSimulators.jl

**Comment by Shushman** [comment]
Will 1. allow the user to override it? In case they have a custom thing they want that is not necessarily the 'observation' but maybe a custom sub-component of the full belief state?. And it could default to 4? I don't know if that use case makes a lot of sense in general. But for my original use case, it was relevant.

**Comment by zsunberg** [comment]
`currentobs` would typically be implemented by a solver-implementer or updater-implementer rather than a problem implementer

So, for instance, since I wrote POMCPOW, I would write `POMDPs.currentobs(::POWTreeObsNode)`. It would look like this: https://github.com/JuliaPOMDP/POMCPOW.jl/blob/master/src/tree.jl#L62. Then, in POMCPOW, whenever I need the action space, I would call `actions(m, n)` where `m` is a `POMDP` and `n` is a `POWTreeObsNode`.

Then if a problem-writer has an observation-dependent action space, they would write something like
```julia
function POMDPs.actions(m::MyPOMDP, b) # b could be a POWObsNode or ARDESPOT.ScenarioBelief, or something else
  o = currentobs(b)
  return filter(a->isvalid(m, a, o), actions(m))
end
```

So the problem writer will not want to overload `currentobs` in any situation I can think of. Does this make sense with your original use case?

**Comment by Shushman** [comment]
Ah ok I see that now. That does make sense!

**Comment by lassepe** [comment]
> @lassepe and I have been talking about this a fair amount.
> 
> Which of these seems best for accessing the last observation in the history that leads up to belief/belief node `b`?
> 
>     1. `lastobs(b)` or `currentobs(b)`
> 
>     2. `o_history(b)[end]`
> 
>     3. `history(b, Val(:o))[end]`
> 
>     4. `history(b)[end].o`
> 
>     5. `ao = b[end]; o = last(ao)`
> 
> 
> I think all of them could be implemented efficiently in the tree-based solvers - it's really a question of what is easiest to understand/remember and how we want to interact with histories in a broader sense.

My thoughts on this:
Solvers should consistently use `actions(m, b)` where b is the most general belief that is available (e.g. for `POMCPOW` this is already implemented with `POWTreeObsNode`, `BasicPOMCP` should use `POMCPTreeObsNode` and so on). The `POMDPs.jl` interface should specify that solver writers should implement 4. (`history(b)`) if their belief type has a notion of a history. `POMDPs.jl` should then still provide `POMDPs.currentobs(b) = history(b)[end].o` as a convenience functions as this should cover most of the use-cases.

**Comment by MaximeBouton** [comment]
I like option 1 and option 4 that Zach proposed.  

If the solver internally uses `actions(m, b)` but really needs `actions(m, o)`  what is the correct way to handle the requirements? Should we provide convenience implementations like what was suggested:


> ```julia
> function POMDPs.actions(m::MyPOMDP, b) # b could be a POWObsNode or ARDESPOT.ScenarioBelief, or something else
>   o = currentobs(b)
>   return filter(a->isvalid(m, a, o), actions(m))
> end
> ```

**Comment by lassepe** [comment]
The fact that the solver should use `actions(m,o)` will depend on the problem, not the solver. If the problem writer want's the solver to use an action space only dependent on the last observation he should implement `POMDPs.actions(m,o)` and overload `POMDPs.actions(m, b) = actions(m, currentobs(b))` accordingly. I don't think that `POMDPs.jl` should provide any convencience implementation for `POMDPs.actions(m,o)` because it is not clear what this should be in general.

**Comment by zsunberg** [comment]
Leaning hard towards adding `history(b)` and `currentobs(b)`
