### ISSUE TITLE
Docs: only reward(m, s, a) shows up

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#235]
Only the docs for reward(m, s, a) show up on the API page. The docs for reward(m, s, a, sp) do not show up.

**Comment by lassepe** [comment]
This seems to be a broader issue. From looking at only [`space.jl`](https://github.com/JuliaPOMDP/POMDPs.jl/blob/8f425dbeb575c2a241043c5622e69fa33b19df5b/src/space.jl) as an example it seems to me as if `Documenter.jl` only creates documentation for abstract function declarations. Methods seem to be skipped. `POMDPs.actions`, `POMDPs.states`, `POMDPs.observation` all seem to have the issue.  Maybe this is intended behavior of `Documenter.jl`.
 
Interesting data point to add. If one uses Julia's help from the REPL, all relevant documentation seems to be displayed:
```
help?> POMDPs.reward
  reward{S,A,O}(problem::POMDP{S,A,O}, state::S, action::A)
  reward{S,A}(problem::MDP{S,A}, state::S, action::A)


  Return the immediate reward for the s-a pair

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  reward{S,A,O}(problem::POMDP{S,A,O}, state::S, action::A, statep::S)
  reward{S,A}(problem::MDP{S,A}, state::S, action::A, statep::S)


  Return the immediate reward for the s-a-s' triple
```
