### ISSUE TITLE
Consider moving `initialstate_distribution` to the common section in the documentation

### ISSUE THREAD

**Issue by lassepe** [JuliaPOMDP/POMDPs.jl#237]
When implementing the `POMDP` interface -- even when implementing the generative version -- it seems to me that there is barely anything that one can do with this model unless `initialstate_distribution` is implemented. E.g. when running a `HistoryRecorder`, even when using the `NothingUpdater` the code fails, since the initial belief distribution can not be determined (trying to call `initialstate_distribution`). So the common workaround seems to be to implement some custom distribution type and then define `Base.rand` on this type which simply calls `initialstate` from the generative interface.

Maybe `initiastate_distribution` should be moved to the "common" section of the POMDPs.jl API documentation? Or maybe one could place a hint somewhere that the above workaround exists. @zsunberg suggested that this workaround could be placed in [`POMDPModelTools.jl`](https://github.com/JuliaPOMDP/POMDPModelTools.jl) in a generalized form.

Feel free to come up with a better title for this issue.

**Comment by zsunberg** [comment]
Perhaps there should be

```julia
initialbelief(::Updater, ::POMDP)
```
 in the interface, with a default of
```julia
initialbelief(u::Updater, m::POMDP) = initialize_belief(u, initialstate_distribution(m))
```
Then things like particle filters can just use `initialstate()` directly.

**Comment by zsunberg** [comment]
Yes, it seems like this should be moved to the "Defining Basic (PO)MDP Properties" section.
