### ISSUE TITLE
@req does not handle `where` syntax

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/POMDPs.jl#238]
When specifying requirements using `where` , `@req` will break: 
Minimal example: 
```julia
using POMDPs
using POMDPModels

gw = SimpleGridWorld()

S = statetype(gw)
P = typeof(gw)

@req convert_s(::Type{V}, ::S, ::P) where V<:AbstractArray
```

Error message: 
```
ERROR: LoadError: LoadError: Malformed requirement expression: convert_s(::Type{V}, ::S, ::P) where V <: AbstractArray
Requirements should be expressed in the form `function_name(::Type1, ::Type2)`

Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] convert_req(::Expr) at C:\Users\Maxime\.julia\dev\POMDPs\src\requirements_internals.jl:90
 [3] @req(::LineNumberNode, ::Module, ::Any) at C:\Users\Maxime\.julia\dev\POMDPs\src\requirements_interface.jl:153
 [4] include at .\boot.jl:326 [inlined]
 [5] include_relative(::Module, ::String) at .\loading.jl:1038
 [6] include(::Module, ::String) at .\sysimg.jl:29
 [7] include(::String) at .\client.jl:403
 [8] top-level scope at none:0
in expression starting at C:\Users\Maxime\.julia\dev\LocalApproximationValueIteration\mwe.jl:9
```

**Comment by zsunberg** [comment]
Ah, interesting. What does it mean to @req a method with an argument that
is not a concrete type? Is the user supposed to implement convert_s for
every subtype of AbstractArray?

I'm not sure whether we should make it work for this or not.

What is the reason for using `where` instead of the concrete type that is
needed?

Really someone needs to rewrite the requirements code to analyze the solver
code and extract requirements automatically.

**Comment by MaximeBouton** [comment]
This issue occured in `LocalApproximationValueIteration.jl` but you are right, the requirement should really be 
```
@req convert_s(::Type{Vector{Float64}, ::S, ::P)
```
since the solver is only using that conversion. @Shushman 

However if the solver would support several array types, the requirement should check that `convert` is implemented for at least one of them. I don't know if there really is a use case for that though...

**Comment by zsunberg** [comment]
> However if the solver would support several array types, the requirement should check that convert is implemented for at least one of them. I don't know if there really is a use case for that though...

The solver should know which type it needs, so you could do something like

```julia
if solver.use_static_arrays
  @req convert_s(::Type{SVector{solver.state_dimension,Float64}}, ::S, ::P)
else
  @req convert_s(::Type{Vector{Float64}}, ::S, ::P)
end
```

I'm going to close this for now, but feel free to reopen if needed
