### ISSUE TITLE
List model packages in README

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#241]
Should we have a list of packages that implement models (e.g. https://github.com/JuliaPOMDP/RockSample.jl) on the README? Or should they be listed in another place?

**Comment by rejuvyesh** [comment]
Wasn't https://github.com/JuliaPOMDP/POMDPGallery.jl supposed to showcase all the available environments? We could just link that?

**Comment by zsunberg** [comment]
Well, it was supposed to show ones with visualizations. I guess if a problem is good-enough quality for others to use, it will probably have a visualization.

**Comment by zsunberg** [comment]
These are now listed in the README
