### ISSUE TITLE
Adding solvers in JuliaPro

### ISSUE THREAD

**Issue by RansML** [JuliaPOMDP/POMDPs.jl#249]
I'm trying to use POMDP.jl. 

`Pkg.add("POMDPs")`
`using POMDPs`
`POMDPs.add_registry()`
`Pkg.add("SARSOP")`

I get the following error when trying to add solvers. I can see the list of solvers with `POMDPs.available()`. I also tried to add different solvers. 

Specs: JuliaPro 1.0.4.1 on Ubuntu 18.04

![Selection_049](https://user-images.githubusercontent.com/12654454/61001555-b1d96a80-a314-11e9-85c6-a16068baca2f.png)

**Comment by zsunberg** [comment]
Hi @RansML , hmm... This appears to be a JuliaPro-specific issue. I'm guessing that they don't support our registry because having a custom registry is not a very common thing.

I'll try to reach out to them and see whether they are blocking external registries on purpose.

If you want to use POMDPs.jl now, you can download the normal (non JuliaPro) version of Julia and it should work.

**Comment by rejuvyesh** [comment]
Yeah. More likely this seems like a firewall issue with your corporate network.

**Comment by zsunberg** [comment]
@rejuvyesh I tried it on JuliaPro (on the Berkeley network) and I also got the same error.

**Comment by bmharsha** [comment]
> I'm guessing that they don't support our registry because having a custom registry is not a very common thing.

JuliaPro does support custom registries. 

You can follow below steps to resolve this issue, make sure you have executed following commands before trying these steps

```
Pkg.add("POMDPs")
using POMDPs
POMDPs.add_registry()
```

1) Open JuliaPro `startup.jl` file, you can find the path to this file by executing following command in JuliaPro REPL or IDE: 
 `normpath(Sys.BINDIR,"..","etc","julia","startup.jl")`
2) Comment following line in startup.jl
`ENV["DISABLE_FALLBACK"] = "true"`
3) Restart JuliaPro IDE and REPL instance and try executing `Pkg.add("SARSOP")`

**Comment by rejuvyesh** [comment]
@zsunberg Should we add these instructions to the docs?

**Comment by zsunberg** [comment]
That worked for me - yes, we should add them somewhere

**Comment by RansML** [comment]
Commenting out `ENV["DISABLE_FALLBACK"] = "true"` worked like a charm. Thanks all!

**Comment by zsunberg** [comment]
closing because we don't use the registry any more
