### ISSUE TITLE
Remove dependency on LiBGit2?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#250]
seems like we don't need this anymore?

**Comment by mykelk** [comment]
I don't think we need it. I'm trying to remember why we had it in the first place.

**Comment by rejuvyesh** [comment]
add Registry!

**Comment by zsunberg** [comment]
Since Pkg's registry functionality requires Julia v1.1 and we want to continue supporting Julia 1.0 LTS, we can't do this yet

**Comment by zsunberg** [comment]
(thank you @rejuvyesh for programming that custom function for us!!)

**Comment by zsunberg** [comment]
We can do this when we remove compatibility with Julia 1.0 #279

**Comment by MaximeBouton** [comment]
also related to https://github.com/JuliaPOMDP/POMDPs.jl/issues/303 
If we decide to register everything to general libgit2 is not needed anymore.
