### ISSUE TITLE
Get rid of `Policy`; policies are just `Function`s

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#252]
I often find myself thinking it would be nice to make writing policies as simple as anonymous functions.

Since
```julia
struct AlphaVectorPolicy <: Function
    ...
end

function (p::AlphaVectorPolicy)(b)
    ... # calculate the action here
end
```
is perfectly valid code, it might be reasonable to just get rid of `Policy` altogether.

Totally undecided on this, just thought I'd throw it out.

**Comment by mykelk** [comment]
Can this be said of other concepts as well? Might we want to do things like display a policy or reset a policy? I don't think we can do that if it is just a function, right?

**Comment by rejuvyesh** [comment]
It's useful to think of `POMDPs.jl` as defining a DSL for sequential decision making problem. A lot of these constructs can be the same thing as the host language. However we are trying to define a common API that a bunch of projects can use and be consistent while being easy to understand for a domain expert who may not be an programming expert.

**Comment by zsunberg** [comment]
> Can this be said of other concepts as well?

I can't think of any that map this cleanly. Many papers have the phrase "A policy is a function that maps...".

> Might we want to do things like display a policy or reset a policy? I don't think we can do that if it is just a function, right?

`showpolicy(::MDP, ::Function)` is still valid. I don't know what you mean by "reset", but, for instance `value(::AlphaVectorPolicy, b)` is still fine if `AlphaVectorPolicy <: Function`

Another option would be `abstract type Policy <: Function end`, but then it is kind of ambiguous when to use `Policy` and when to use `Function`.

Anyways `FunctionPolicy` is already there, so this is just a matter of aesthetics

**Comment by mykelk** [comment]
I think we can just use `FunctionPolicy` and keep the `Policy` type.

**Comment by zsunberg** [comment]
Final decision: No. `Policy` is separate from `Function`
