### ISSUE TITLE
Helpful error messages for v0.8

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#260]
I am quite pleased with how the version 0.8 dbn-centric code came out. Unfortunately, many of the helpful errors from version 0.7 have gone away. For example, if there is no implementation for `gen(::DBNVar{:sp}, m, s, a, rng)` the error will be a `MethodError` for `transition`, which can easily lead people down the road of thinking they need to implement `transition`.

This was primarily a problem for people starting out on the steep learning curve to using POMDPs.jl, and I don't think it is as big of an issue now because people can start with QuickPOMDPs (soon QuickPOMDPs will have convenient ways to define a much larger range of problems - they will look like [this](https://github.com/JuliaPOMDP/QuickPOMDPs.jl/blob/generative/examples/mountaincar.jl).)

Here are some possible ways forward:

1. Leave as-is; don't provide any special errors
    - Pros:
        - No more effort
    - Cons:
        - Can be super confusing for beginners
2. Provide default implementations of `transition` and `observation` that throw helpful errors
    - Pros:
        - No overhead
        - Ad-hoc and won't help for any dbn nodes besides :sp and :o
    - Cons:
        - would have to look at the stack trace to see if it was called from `gen`. This seems like it could be sketchy.
3. Throw an error in `gen(::DBNVar, ...)` if the node does not have an implementation
    - Pros:
        - Easy to understand
    - Cons:
        - Checking if the node has an implementation has overhead
4. Add type information to the DBN and do metaprogramming 
    - Pros:
        - Systematic
        - No overhead
    - Cons:
        - Not supposed to observe the method table in @generated functions, so it's not clear how to even do this
        - this makes specifying the DBN much more of a pain
        - We are essentially recreating a lot of the compiler's functionality, so this seems like a bad idea

I guess I think (2) is the best. Thoughts from anyone else are appreciated.

**Comment by mykelk** [comment]
Option (2) sounds good to me as well.

**Comment by MaximeBouton** [comment]
I like 2 as well, analyzing the stack trace sounds scary, it might not be needed if the error message is instructive enough?

**Comment by zsunberg** [comment]
>  it might not be needed if the error message is instructive enough?

I think the code will have to *analyze its own stack trace* in order to throw an error that is not misleading. If `transition` is called from within value iteration, we want it to throw a `MethodError` for transition. If it was called through `gen`, we want it to throw something more informative that lists more options.

**Comment by MaximeBouton** [comment]
If it turns too difficult to analyze the stack trace, an alternative is to explain that the problem writer can also define `gen` in the error message returned by `transition`?

**Comment by lassepe** [comment]
+1 for option (2).

**Comment by lassepe** [comment]
>  If `transition` is called from within value iteration, we want it to throw a `MethodError` for transition. If it was called through `gen`, we want it to throw something more informative that lists more options.

Can't you catch the `MethodError` in `gen` and rethrow with more information?

**Comment by zsunberg** [comment]
as far as I can tell, catching has overhead :(

**Comment by zsunberg** [comment]
https://discourse.julialang.org/t/how-to-create-more-helpful-errors-in-nested-interfaces/28380

**Comment by lassepe** [comment]
Ugly but no overhead: have a value type argument that can be used to communicate where transition has ben called from (sort of a manual depth-one stack trace).

**Comment by zsunberg** [comment]
Ended up implementing (2). The implementation works pretty well. For helping people it is OK-ish because it is still hard to understand. This might be made better when we decouple the DDN stuff a bit.
