### ISSUE TITLE
Is it ok that DBN nodes just correspond to symbols?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#264]
Right now in version 0.8, each DBN node just corresponds to a symbol. Is this ok? 

It is very handy in that it allows for a lot of convenient syntax with NamedTuples, but one problem is that there is no central authority that determines which symbols mean what. For example, someone could interpret node :c as the constraint cost and someone else could write a solver that interprets it differently.

I don't think this will be a huge problem, but maybe there is a better eventual solution. Fortunately, I think it should be relatively easy to replace if we come up with something better.

**Comment by lassepe** [comment]
I think there is no need for premature generalization to more than symbols here.

**Comment by zsunberg** [comment]
Haha, yeah, you're right - not going to worry about this now.
