### ISSUE TITLE
Naming for `gen`, `DBNVar`, and `DBNOut`

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#268]
In the review for #258 there has been some confusion with the new features. Better naming might be able to help.

There are 3 things that need to be named.

### 1. The DBN Structure
I think we have converged on Dynamic Decision Network for this.

### 2. `gen`
There are 3 versions of this function; perhaps they should have different names.

#### Alternatives for the `DBNVar` version
- `sample`
- `rand`
- `nodegen`

#### Alternatives for the `DBNOut` version
- `genout`
- `ddngen`

At the moment I am leaning towards keeping just one `gen` because the concepts are closely related and this clearly associates the function with the G in most papers, but I am open to considering others.

### 3. `DBNVar` and `DBNOut`
These are probably the hardest to understand.

#### Alternatives for `DBNVar`
- `DDNRef`
- `DDNNode` - this kind of clashes with the node implementation type names
- `NodeRef`
- `Node`

#### Alternatives for `DBNOut`
- `Return`
- `Out`
- `Select`
- `Val` (just use the builtin) - this is kinda ugly because you have to double the parentheses: `Val((:sp,:o,:r))`
- `DDNSubset`
- `Group`
- `Sample`

I guess my preferences are `DDNNode` and `DDNOut`

Please let me know if you have any preferences.

**Comment by lassepe** [comment]
For (2): Keeping just one `gen` makes sense to me. However, why abbreviate this? Couldn't we just use `generate` instead of `gen`?

For (3): I would also prefer `DDNNode` and `DDNOut`. This seems to provide the best clarification as to when to use which of these. All other options seem a bit ambiguous and potentially would annoy me as a user if they were exported by a package.

**Comment by zsunberg** [comment]
Clearly you weren't educated as an aerospace engineer - `gen` is more aerodynamic :stuck_out_tongue: 

Actually, I just thought it would make the lines a little shorter.
```julia
sp, o, r = gen(DDNOut(:sp,:o,:r), s, a, rng)
```
vs
```julia
sp, o, r = generate(DDNOut(:sp,:o,:r), s, a, rng)
```
and easier to pronounce when talking to people. The style guide says that abbreviations are bad because it's hard to remember when things are abbreviated (https://docs.julialang.org/en/v1/manual/style-guide/index.html#Use-naming-conventions-consistent-with-Julia-base/-1). I think this isn't too bad to remember.

**Comment by mykelk** [comment]
We are just sampling from a distribution here for gen. Shouldn't we use the same name here as we use for generating other samples from distributions? Is there a good reason not to?

**Comment by zsunberg** [comment]
@mykelk, you mean `rand`?

**Comment by mykelk** [comment]
Yeah

**Comment by zsunberg** [comment]
The difference is that the argument to `rand` is an actual distribution object while the arguments to `gen` are states, actions, or other input values. With `gen`, an object that represents the distribution is never created.

**Comment by mykelk** [comment]
True. Together, though, the other arguments implicitly define a distribution. That said, I don't feel strongly either way; I just figured I'd mention that.

**Comment by zsunberg** [comment]
Yeah, I think that difference is significant enough to warrant a new name. @mykelk if we really wanted to emphasize the idea of implicit distributions, we should do something like #269 . But I think I like `gen` better :)
