### ISSUE TITLE
Strange behavior `gen(DDNOut(:o), ...)`

### ISSUE THREAD

**Issue by MaximeBouton** [JuliaPOMDP/POMDPs.jl#272]
I got confused when updating RLInterface by the following: 
```julia
using POMDPModels, POMDPs, Random
pomdp = TMaze()
rng = MersenneTwister(1)
s = initialstate(pomdp, rng)
a = first(actions(pomdp))
gen(DDNOut(:o), pomdp, s, rng) # throws MethodError
gen(DDNOut(:o), pomdp, s, a, rng) #throws KeyError :o not found 
gen(DDNOut(:o), pomdp, s, a, s, rng) # throws MethodError
gen(DDNOut(:o), pomdp, a, s, rng) # throws KeyError :o not found
generate_o(pomdp, s, a, rng) # throws MethodError 
generate_o(pomdp, s, rng) # works 
generate_o(pomdp, s, a, s, rng) # works
```

Could someone explain those behaviors to me? 
What is the proper way to replace a call to `generate_o(pomdp, s, rng)` 

on POMDPs v0.7.3

Thanks!

**Comment by zsunberg** [comment]
`gen(::DDNOut, m, s, a, rng)` is the only valid signature for `DDNOut` as of now. Because, when `DDNOut` is used, the input arguments are the *inputs to the entire DDN*.

I did not design a solution for the initial observation case - we can either have a new function `initialobs` or use `gen(::DDNNode{:o}, m, s, rng)`

**Comment by MaximeBouton** [comment]
> `gen(::DDNOut, m, s, a, rng)` is the only valid signature for `DDNOut` as of now. Because, when `DDNOut` is used, the input arguments are the _inputs to the entire DDN_.

This behavior makes sense to me, shouldn't this work then? 
```julia 
gen(DDNOut(:o), pomdp, s, a, rng) #throws KeyError :o not found 
```

> I did not design a solution for the initial observation case - we can either have a new function `initialobs` or use `gen(::DDNNode{:o}, m, s, rng)`

this works: ` gen(DDNNode{:o}(), pomdp, s, rng)`

**Comment by zsunberg** [comment]
See my edited response above about the `KeyError`

**Comment by MaximeBouton** [comment]
Cool, I think I found the line: https://github.com/JuliaPOMDP/POMDPs.jl/blob/version-0.7/src/future.jl#L7

What would you suggest, should I go with `DDNNode` for now and update it once v0.8 is out?

**Comment by zsunberg** [comment]
I think we will always have to use `DDNNode` because we won't have an action to input into the `DDNOut` version.

**Comment by zsunberg** [comment]
see #274 for further discussion
