### ISSUE TITLE
Initial observations in POMDPs v0.8

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#274]
In some cases (e.g. RLInterface.jl), we need to get an initial observation with only a state input.

So far we have been using `gen(DDNNode{:o}, m, s, rng)`, but this is not very satisfying because it does not obey the steady-state DDN structure of the problem (because usually `s` and `a` are also inputs).

I think we should add `initialobs(m, s, rng)` to the interface for this case. Votes for/against?

**Comment by lassepe** [comment]
Just out of curiosity: Why does it need this observation? Does it need to be generated? Is there a reason why this can't be the previous observation from something like `BeliefUpdaters.PreviousObservationUpdater `?

**Comment by zsunberg** [comment]
for the first step, when there have been no actions taken and there is only the initial state

**Comment by lassepe** [comment]
How was this done before v0.8? `generate_s` always also depended on the action, right?

**Comment by MaximeBouton** [comment]
I realized when updating it that `RLInterface` was using two different things: 
- either calling `generate_o(pomdp, s, rng)` and the user would need to implement this for his model, I think this is preferable and could be easily handle by an `initialobs` function. 
- or calling `generate_o(pomdp, s, first(actions(pomdp)), rng)` which I think was bad 

What is wrong with `gen(DDNOut(:o), m, s, rng)` instead of `initialobs` ? It would be more consistent in terms of naming.

**Comment by lassepe** [comment]
I think in theory the problem with using `gen(DDNNode{:o}, m, s, rng)` is, hat it suggests that `o` can in general be generated from `s` alone and does not depend on the previous state and action. `initialobs(m, s, rng)` communicates more clearly that this is only used for initialization.

However, (in practice) if one can write down `gen(DDNNode{:o}, m, s, rng)` for the initial observation, do people actually make use of other dependencies of `o` (other edges in the DDN)?

**Comment by zsunberg** [comment]
> or calling generate_o(pomdp, s, first(actions(pomdp)), rng) which I think was bad

Haha yeah, that was really bad :man_facepalming: 

> What is wrong with gen(DDNOut(:o), m, s, rng) instead of initialobs ? It would be more consistent in terms of naming.

The current documentation says "The arguments [for `gen(::DDNOut{...}, ...)`] are values for the input nodes (currently :s and :a), treating the entire DDN as a single black box." This breaks that rule, and no where else do we advise the user to implement a `DDNOut` version.

[I have more comments, but have to go right now. Fundamentally, I think this is a special case because it does not follow the normal DDN structure, and we should recognize that by giving it a special name. We could also think about adding another type separate from `DDNNode` and `DDNOut`, like `gen(InitialObs(), m, s, rng)`]

**Comment by MaximeBouton** [comment]
I just realized that the connection is actually (:a, :sp) -> (:o) and that is why we need both :a and :s as input. 
In a lot of problems, the observation model is action independent, in the previous interface we would implement `generate_o(m, s, rng)` (no need to distinguish between `s` an `sp` for computing `o`)
How would it work now then?

**Comment by zsunberg** [comment]
@MaximeBouton I'm not sure exactly what you mean by the "it" in "How would it work now then?" do you mean "How would one implement an observation model that only depends on the state?"

### Here is my current proposal:
In POMDPs.jl:
```julia
initialobs(m::POMDP, s, rng) = rand(rng, observation(m, s))
```
(note: it may throw a more helpful error than just a `MethodError` for `observation`)

### Here's how one could implement a state-dependent observation model under this proposal

- If the problem writer implements `observation(m, s)`, then everything will work.
- There would be no way to implement a generative model that provides initial observations in one function; the problem writer would have to implement both `gen(::DDNNode{:o}, m, s, a, sp, rng)` and `initialobs` separately. (this is because `gen(::DDNNode, ...)` needs one argument for each incoming edge in the DDN

**Comment by lassepe** [comment]
In your proposed solution, what would be the right thing to do if the problem writer only can specify a generative model for `o`? Should they implement `initialobs` directly or make a dummy distribution type to define `rand` on that? I feel like both solutions are rather inconsistent with the idea of `gen`. I would prefer if the user could implement `gen(DDNNode{:o}, m, s)` for this case. 

Maybe `initialobs` can use `rand(rng, observation(m,s))` and if it does not exists, call `gen(::DDNNode{:o}, m, s)` directly (note that it calls the Node instead of the out version to avoid dependence on `a` and previous `s`).

But essentially this boils down to implementing a special version of `gen` for the root that reflects the correct dependencies. In fact, the real problem seems to be that the DDN at the root does not quite match `DDNStructure(m)`. Maybe there should be `DDNRootStructure` that defaults to `DDNStructure(m)` and is overloaded to reflect the correct dependencies for `RLInterface` problems?

That said, we should not over-generalize at this point. I could totally live with problem writers having to implement `initialobs` directly.

**Comment by zsunberg** [comment]
> In your proposed solution, what would be the right thing to do if the problem writer only can specify a generative model for o? Should they implement initialobs directly or make a dummy distribution type to define rand on that?

They would implement `initialobs` directly, similar to `initialstate`.

> I feel like both solutions are rather inconsistent with the idea of gen.

I used `initialobs` to be consistent with `initialstate`. I don't like `gen(::DDNNode{:o}, m, s, rng)` because, as you say, it doesn't really match the DDN. I would be more sympathetic to `gen(Initial{:o}, m, s, rng)`, but then we should also consider replacing `initialstate` with `gen(Initial{:s}, m, rng)` and having `InitialStepDDNStructure`.* Would you feel better about that?

*note: `InitialStepDDNStructure` might be confusing because it only uses this in the RL context and doesn't use it in the POMDP context where there is an initial belief instead of an initial observation.

**Comment by MaximeBouton** [comment]
I think introducing a lot of different structures will make things more confusing. 
Introducing `initialobs`  sounds reasonable. 

Just to clarify, right now if someone wants to implement a generative observation model that is independent of the action he should still implement `gen(::DDNNode{:o}, m, s, a, sp, rng)`? 
There are two things that I don't like with this: 
- the fact that we have to juggle between `DDNNode` and `DDNOut`, I think we should stick to exposing only one of those to problem writers. 
- We still need `s` and `a` in the function definition although they shouldn't affect the observation given `sp`. I understand that if we want to respect the structure of the DDN there might not be a good way around.

Finally, maybe this whole `gen(::DDNNode{:o}, m, s, a, sp, rng)` is not needed after all, as the user can just implement `gen(::DDNOut{:o, :sp}, m, s, a, rng)` and structure the internals of this function as he wants.

**Comment by lassepe** [comment]
The current of idea of the `gen` interface is that problem writers don't use the `DDNOut` version. They only ever implement `gen(m, s, a, sp, rng)` (for the entire black box) or `DDNNode` for special edges of the graph.  `gen( ::DDNOut...)` is created automatically by the `@generated` funciton and only used on the solver side. [From the docs:]()

**Comment by MaximeBouton** [comment]
That makes a lot of sense, thanks for the explanation! I should have given a more thorough read of the docs.
To go back to the original question, I vote for introducing `initialobs`.

**Comment by zsunberg** [comment]
Ok, I think I will add `initialobs` and release v0.8.1 with it. If there are any other changes that should go into 0.8.1, please file an issue.

@lassepe I assume your :+1: on [the comment above](https://github.com/JuliaPOMDP/POMDPs.jl/issues/274#issuecomment-536717646) means that you liked that `initialobs` is consistent with `initialstate`, **not** that you like `gen(Initial{...}, ...)`. Is that correct?

**Comment by lassepe** [comment]
Correct. The analogy to `initialstate` had me convinced.

**Comment by lassepe** [comment]
@zsunberg I created a milestone for v0.8.1. Do you already have a branch/code for the `initialobservations` implementation?

**Comment by zsunberg** [comment]
No, I don't have code yet. If you want, you can take a stab at it. I
probably won't get to it until after we submit this paper.

- Zach
