### ISSUE TITLE
Error installing packages

### ISSUE THREAD

**Issue by wbrannon** [JuliaPOMDP/POMDPs.jl#283]
I am having issues installing certain packages on Julia 1.2.0 with Mac OS 10.14.6. Even though I successfully ran `Pkg.add("SARSOP")`, I get the following error when using `Pkg.add("MCTS")`:

<img width="822" alt="Screen Shot 2019-12-13 at 10 11 20 AM" src="https://user-images.githubusercontent.com/39833759/70822292-084e4780-1d92-11ea-8fe7-3f633f219c3e.png">

**Comment by rejuvyesh** [comment]
Looks like last PR to update MCTS in our Registry had issues: https://github.com/JuliaPOMDP/Registry/pull/41/files . Will push a fix soon.

**Comment by zsunberg** [comment]
@wbrannon sorry! this was my mistake - forgot to push something I committed locally. Does it work now?

**Comment by wbrannon** [comment]
works now! Thanks for the quick fix guys!
