### ISSUE TITLE
Transition function error

### ISSUE THREAD

**Issue by kubicon** [JuliaPOMDP/POMDPs.jl#285]
Hello,
I have pretty large POMDP, and my transition function 
`function POMDPs.transition(pomdp::OriginalGame, s::JointState, a::JointAction)`
returns Array which has for every state probability. (Just 1D array with values, where probability of ending in state with index n is on n-th position)
Sadly when i try to run this POMDP through solver i get this exception

> ERROR: LoadError: 
> POMDPs.jl could not find an implementation for DDN Node :sp. Consider the following options:
> 
> 1) Implement POMDPs.gen(::OriginalGame, ::JointState, ::JointAction, ::AbstractRNG) to return a NamedTuple with key :sp.
> 
> Closest candidates are:
>   gen(::Union{MDP, POMDP}, ::Any, ::Any, ::Any) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\gen_impl.jl:82
>   gen(::GenericDDNNode, ::Any...) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\ddn_struct.jl:165
>   gen(::DistributionDDNNode, ::Any, ::Any...) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\ddn_struct.jl:117
>   ...
> 
> 2) Implement POMDPs.gen(::DDNNode{:sp}, ::OriginalGame, ::Any, ::Any, ::Any, ::AbstractRNG).
> 
> Closest candidates are:
>   gen(::DDNNode{x}, ::Any, ::Any...) where x at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\gen_impl.jl:67
>   gen(::GenericDDNNode, ::Any...) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\ddn_struct.jl:165
>   gen(::DistributionDDNNode, ::Any, ::Any...) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\ddn_struct.jl:117
>   ...
> 
> 3) Implement transition(::OriginalGame, ::Any, ::Any, ::Any).
> 
> Closest candidates are:
>   transition(::OriginalGame, ::JointState, ::JointAction) at C:\git\skola\bak_julia\BAKProj\src\OriginalGame.jl:81
>   transition(::Any, ::Any, ::Any) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\errors.jl:107
>   transition(::TigerPOMDP, ::Bool, ::Int64) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPModels\eCvzD\src\TigerPOMDPs.jl:29
>   ...
> 
> This error message uses heuristics to make recommendations for POMDPs.jl problem implementers. If it was misleading or you believe there is an inconsistency, please file an issue: https://github.com/JuliaPOMDP/POMDPs.jl/issues/new
> 
> Stacktrace:
>  [1] distribution_impl_error(::Symbol, ::Function, ::Type, ::Array{DataType,1}) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\errors.jl:77
>  [2] transition(::OriginalGame, ::Array{Float64,1}, ::JointAction) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\errors.jl:107
>  [3] macro expansion at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\ddn_struct.jl:119 [inlined]
>  [4] gen(::DistributionDDNNode{typeof(transition)}, ::OriginalGame, ::Array{Float64,1}, ::JointAction, ::Random.MersenneTwister) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\ddn_struct.jl:117
>  [5] macro expansion at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\gen_impl.jl:78 [inlined]
>  [7] macro expansion at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\gen_impl.jl:46 [inlined]
>  [8] macro expansion at .\none:0 [inlined]
>  [9] genout(::DDNOut{(:sp, :o, :r)}, ::DDNStructure{NamedTuple{(:s, :a, :sp, :o, :r),Tuple{InputDDNNode,InputDDNNode,DistributionDDNNode{typeof(transition)},DistributionDDNNode{typeof(observation)},FunctionDDNNode{typeof(reward)}}},NamedTuple{(:s, :a, :sp, :o, :r),Tuple{Tuple{},Tuple{},Tuple{DDNNode{:s},DDNNode{:a}},Tuple{DDNNode{:s},DDNNode{:a},DDNNode{:sp}},Tuple{DDNNode{:s},DDNNode{:a},DDNNode{:sp},DDNNode{:o}}}}}, ::OriginalGame, ::Array{Float64,1}, ::JointAction, ::Random.MersenneTwister) at .\none:0       [10] macro expansion at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\gen_impl.jl:19 [inlined]
>  [11] gen(::DDNOut{(:sp, :o, :r)}, ::OriginalGame, ::Array{Float64,1}, ::JointAction, ::Random.MersenneTwister) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPs\XDCTo\src\gen_impl.jl:4
>  [12] iterate(::POMDPSimulators.POMDPSimIterator{(:s, :a, :r),OriginalGame,RandomPolicy{Random.MersenneTwister,OriginalGame,BeliefUpdaters.NothingUpdater},BeliefUpdaters.NothingUpdater,Random.MersenneTwister,Nothing,Array{Float64,1}}, ::Tuple{Int64,Array{Float64,1},Nothing}) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPSimulators\V9qfg\src\stepthrough.jl:94 [13] iterate(::POMDPSimulators.POMDPSimIterator{(:s, :a, :r),OriginalGame,RandomPolicy{Random.MersenneTwister,OriginalGame,BeliefUpdaters.NothingUpdater},BeliefUpdaters.NothingUpdater,Random.MersenneTwister,Nothing,Array{Float64,1}}) at C:\Users\OndrejKubicek\.juliapro\JuliaPro_v1.2.0-1\packages\POMDPSimulators\V9qfg\src\stepthrough.jl:86 [14] top-level scope at C:\git\skola\bak_julia\BAKProj\src\test.jl:37
>  [15] include at .\boot.jl:328 [inlined]
>  [16] include_relative(::Module, ::String) at .\loading.jl:1094
>  [17] include(::Module, ::String) at .\Base.jl:31
>  [18] include(::String) at .\client.jl:431
>  [19] top-level scope at none:0
> in expression starting at C:\git\skola\bak_julia\BAKProj\src\test.jl:37
> 

Is this a bug or is my method wrong and should contain some fourth parameter as stated in point 3 (and what should this parameter be)?

Thanks for asnwer

**Comment by zsunberg** [comment]
Hi @kubicon it appears that there is an error in the error display :) Thanks for reporting! You should not have to implement a four-argument version of transition.

`transition` needs to return a [distribution object](), not just a vector of probabilities. You can make a distribution over your states with a vector of probabilities, `probs` with `SparseCat(states(m), probs)` (SparseCat is from [POMDPModelTools.jl](https://juliapomdp.github.io/POMDPModelTools.jl/latest/distributions.html#Sparse-Categorical-(SparseCat)-1).

Could you link to your code so that I can debug the error in the error message? Thanks!

**Comment by zsunberg** [comment]
Also, what version of POMDPs.jl do you have? (use `Pkg.installed()["POMDPs"]`)

**Comment by kubicon** [comment]
Hello @zsunberg, thanks for quick answer. My POMDPs.jl is v"0.8.1"

Here I will post the whole structure (just be noted it is far from complete and some things are there redundant or not optimal, it's still work in progress i just to see if it works). Observations for example are not complete at all.

`using Parameters
using POMDPs

mutable struct StatePOSG
    state::Int64
    followerActions::Array{Int64}
end

mutable struct PartitionPOSG
    partition::Int64
    states::Array{StatePOSG}
    leaderActions::Array{Int64}
end

mutable struct TransitionPOSG
    initialState::StatePOSG
    leaderAction::Int64
    followerAction::Int64
    observation::Int64
    finalState::StatePOSG
    probability::Float64
end

mutable struct RewardPOSG
    state::StatePOSG
    leaderAction::Int64
    followerAction::Int64
    reward::Float64
end

mutable struct ObservationPOMDP
    observation::Int64
    statesWithProb::Dict{Int64, Float64}
end

mutable struct ActionPOMDP
    action::Int64
    policy::Float64
    observations::Array{ObservationPOMDP}
end

mutable struct BeliefStatePOMDP
    beliefStateIndex::Int64
    possible_actions::Array{ActionPOMDP}
end

mutable struct JointState
    belief::Int64
    state::Int64
end

mutable struct JointAction
    leaderAction::Int64
    followerAction::Int64
end

mutable struct OriginalGame <: POMDP{JointState, JointAction, Int64}
    states::Array{StatePOSG}
    partitions::Array{PartitionPOSG}
    leaderActions::Array{Int64}
    followerActions::Array{Int64}
    observations::Array{Int64}
    transitions::Array{TransitionPOSG}
    rewards::Array{RewardPOSG}
    initialState::StatePOSG
    beliefStates::Array{BeliefStatePOMDP}
    jointStates::Array{JointState}
    jointActions::Array{JointAction}
end

POMDPs.states(pomdp::OriginalGame) = pomdp.jointStates
POMDPs.stateindex(pomdp::OriginalGame, s::JointState) = s.belief * length(pomdp.states) + s.state
POMDPs.actions(pomdp::OriginalGame) = pomdp.jointActions
POMDPs.actionindex(pomdp::OriginalGame, a::JointAction) = a.leaderAction * length(pomdp.followerAction) + a.followerAction
POMDPs.discount(pomdp::OriginalGame) = 0.95
POMDPs.observations(pomdp::OriginalGame) = [true, false]
POMDPs.obsindex(pomdp::OriginalGame, o::Bool) = o+1


function POMDPs.transition(pomdp::OriginalGame, s::JointState, a::JointAction)
    result = zeros(length(pomdp.jointStates))
    foundTransitions = []

    belief = pomdp.beliefStates[s.belief]
    println(belief)
    possibleBeliefs = []
    for i=1:length(belief.possible_actions)
        if (belief.possible_actions[i].action == a.leaderAction)
            println(belief.possible_actions[i].observations)
            foreach(f -> push!(possibleBeliefs, f.statesWithProb), belief.possible_actions[i].observations)
        end
    end
    if isempty(possibleBeliefs)
        return result
    end
    for i=1:length(pomdp.transitions)
        if (pomdp.transitions[i].initialState.state == s.state && pomdp.transitions[i].followerAction == a.followerAction && pomdp.transitions[i].leaderAction == a.leaderAction)
            push!(foundTransitions, i)
        end
    end
    if isempty(foundTransitions)
        return result
    end
    for i=1:length(possibleBeliefs)
        allKeys = collect(keys(possibleBeliefs[i]))
        for j=1:length(foundTransitions)
            for k=1:length(allKeys)
                index = allKeys[k] + (pomdp.transitions[foundTransitions[j]].finalState.state -1 ) * length(pomdp.beliefStates)
                result[index] = 1.0 #Todo neco jinyho
            end
        end
    end
    # do magic
    return result
end

# function POMDPs.observations(pomdp::OriginalGame)
#
function POMDPs.reward(pomdp::OriginalGame, s::JointState, a::JointAction)
    for i=1:length(pomdp.rewards)
        if (pomdp.rewards[i].state.state == s.state && pomdp.rewards[i].leaderAction == a.leaderAction && pomdp.rewards[i].followerAction == a.followerAction)
            rew = pomdp.reward[i].reward
            return rew
        end
    end
    return 0
end

function POMDPs.initialstate_distribution(pomdp::OriginalGame)
    result = zeros(length(pomdp.jointStates))
    result[1] = 1
end

function POMDPs.observation(pomdp::OriginalGame, a::JointAction, s::JointState)
    return BoolDistribution(0.5)
end

`

**Comment by zsunberg** [comment]
Hi @kubicon , I downloaded this to try and debug the bad error message today. However, there appears to be something missing around line 80. Could you add that when you get a chance?

**Comment by kubicon** [comment]
Hello @zsunberg, I changed quite a lot in code by now, so error message doesn't bother me anymore (It started working after I returned SparseCat instead of just Array).
However, I think the missing line is:
`
function transition(pomdp::OriginalGame, s::JointState, a::JointAction)`

**Comment by zsunberg** [comment]
This seems to be stale, so I am closing. Feel free to reopen.
