### ISSUE TITLE
better way to handle terminal states/reward

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#291]
One thing that is kind of a pain to represent in POMDPs.jl right now is terminal rewards.

I wanted to avoid a `terminalreward` function because it would be one more thing that solver-writers would have to remember and get right. But right now it is a pain to add in terminal reward as a model-writer because you have to either add a new specially-made terminal state to the problem or assign the reward when transferring *into* the existing terminal state.

I propose replacing `isterminal(m,s)` with a new function, `terminalvalue(m, s)`. If the state is not terminal `terminalvalue(m, s)` should return `nothing`. If it is terminal and has no terminal reward, it should return 0, and if it has a terminal reward, it should return that reward (since that is the value at `s`).

A rollout MDP simulation would look like this:
```julia
r_total = 0.0
while isnothing(terminalvalue(mdp, s))
    a = action(policy, b)
    s, r = gen(DDNOut(:sp,:r), mdp, s, a, rng)
    r_total += d*r
    d *= discount(mdp)
end
r_total += terminalvalue(mdp, s)
```

Any thoughts on this? The change probably wouldn't be implemented until the summer.

**Comment by mykelk** [comment]
Can you elaborate why it is hard to handle terminal rewards right now?

**Comment by MaximeBouton** [comment]
I definitely struggled more than once with terminal values. 
In almost all of my cases, defining a custom *absorbing* state and a reward for reaching it fixed it. 
Here are some of the causes: 
- some solvers are relying on `isterminal` (DiscreteVI) and some do not (SARSOP) 
- it is unclear if terminal states are absorbing, the model writer has to manually make them absorbing in the transition (at least if they want consistent behavior between the two solvers mentioned above). 
- some solvers enforce the value at terminal state to be 0. Theoretically correct for standard MDP planing but is annoying if one wants to stretch the library for e.g. model checking. 

Replacing `isterminal` would definitely help solving those problems. 
The new termination condition is less straightforward than `isterminal`, I am not sure how it would be perceived by a novice problem writer.

**Comment by rejuvyesh** [comment]
I can see the problem, but don't know if I agree with the solution. `isterminal` is a common API anyone who works in this domain coming from other packages would be aware of. `terminalvalue` introduces a new thing which is not commonly used in the textbooks or anywhere else. I would rather recommend figuring the consistency issues with the solvers and try to fix that. Maybe we can make defining the _absorbing_ state easier.

**Comment by zsunberg** [comment]
> Can you elaborate why it is hard to handle terminal rewards right now? (@mykelk)

Consider the task of programming the grid world problem that we always use, which terminates after collecting a reward in certain states. Suppose the only state with reward is [7,3]. Currently, you have two options for handling this:

### 1. Assign reward when you transfer INTO [7,3], and make [7,3] terminal

e.g. `reward(m, s, a, sp) = 10*(sp==[7,3]); isterminal(m, s) = s==[7,3]`

Difficulties:
a) How do you display this? Should [6,3], [8,3], [7,2], [7,4] be light green because R(s, a) is positive for them?
b) Thinking about discounting is tricky. This reward is discounted as if it were collected *before* getting to [7,3].
c) Will not work out of the box for solvers that just use R(s, a), although this should be fixed by making code that automatically calculates R(s,a) by taking the expectation of R(s, a, s').

### 2. Create a special terminal state and make [7,3] deterministically transition into it.

This is the current solution in POMDPModels. We use [-1, -1] as a terminal state.

Difficulties:
a) There is often not a convenient way to specify the special terminal state as the same type as the normal states (e.g. if the state space is R^2, you can't use [-1, -1] as the terminal state because it is a valid normal state). You can use `POMDPModelTools.terminalstate`, but then the state type for the problem is always `Union{ NormalStateType, TerminalState}`, which can cause type stability problems.
b) Whenever you are doing any kind of iteration through the state space, you run into this terminal state, which is often annoying/confusing

2 Is usually better, but neither is really that satisfactory and both are difficult to explain to new users.

> isterminal is a common API anyone who works in this domain coming from other packages would be aware of. (@rejuvyesh )

The idea of terminal rewards is also pretty standard - just choosing the right names and mechanism is a bit of a challenge. The fact that all terminal states must have value zero seems to be something that I am constantly telling/reminding people of; it doesn't seem to catch on that easily.

Anyways, yeah, I guess `terminalvalue` is probably not the best solution. Anyone have any other ideas? I guess `terminalreward(m, s)` might not be too bad - the main problem is that `isterminal` and `terminalreward` would contain conceptually redundant information, and there are pitfalls. e.g. if `isterminal(m, s)` returns `false`, but `terminalreward` returns 1.0, it is easy to imagine a case where one solver checks `isterminal` first, but another solver just queries `terminalreward` expecting it to be zero if the state is not terminal. Tests for some problems might pass, but for other problems, the solver could arrive at a wrong answer.

**Comment by mykelk** [comment]
I don't see 2 as too bad. I don't really see a better alternative.

**Comment by zsunberg** [comment]
Ok, we'll keep the status quo unless someone comes up with a better idea.
