### ISSUE TITLE
Fix DDN Structure mistake and move to SequentialDecisionBase.jl

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#292]
Another thing that I am thinking maybe we should change in the summer:

The DDN Structure design is not exactly right, as evidenced by the lack of success that we have had in creating a MOMDP interface (#282).

I think this mostly stems from trying to integrate too tightly with POMDPs and ending up with things like DistributionDDNNode(transition). (This is bad for reasons that I do not have time to explain at the moment.)

Instead, I think we should move the DDN structure code into another package, perhaps called SequentialDecisionBase.jl

**Comment by rejuvyesh** [comment]
That seems appropriate and might be useful for us in MAPOMDPs.jl as well. But this is still too vague to tell how different packages will integrate with it.

**Comment by zsunberg** [comment]
Does anyone have any preference on the name for this package. I am now leaning towards `DynamicDecisionNetworks.jl`

**Comment by zsunberg** [comment]
Thinking of a different approach for this #306

**Comment by zsunberg** [comment]
Moving forward with #306 instead of this.
