### ISSUE TITLE
Version 0.9 Meta Issue

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#297]
I'm going to start working on POMDPs 0.9 now. Feel free to comment if you'd like to help or have ideas/things to fix! I think this should actually be a fairly small change. I would say we could release it in a month or so, and then if there are no major problems, we could release POMDPs 1.0 by the end of the summer!

**Comment by mykelk** [comment]
1.0!

**Comment by rejuvyesh** [comment]
Although shouldn't really matter much for v0.9, but we have a few extensions for multi-agent problems in MAPOMDPs. Currently the algos implemented only work with MDPs, but should be easy to port over the ideas for POMCP etc.

**Comment by zsunberg** [comment]
@rejuvyesh cool! Yeah, I have seen MAPOMDPs pop up in my notifications, but I wasn't sure exactly what kind of multi-agent features you had added. Is there a specific place that I should look to see what the important parts of the package are? I actually may be working on a sort of multi-agent problem this summer so I am curious about it.

**Comment by rejuvyesh** [comment]
https://github.com/JuliaPOMDP/MAPOMDPs.jl/blob/master/src/MAPOMDPs.jl contains the extensions we made to POMDPs.jl interface to support team coordination problems. Algos implemented are [Independent Q Learning](https://github.com/JuliaPOMDP/MAPOMDPs.jl/blob/master/src/iql/iql.jl), [Centralized MCTS](https://github.com/JuliaPOMDP/MAPOMDPs.jl/tree/master/src/naive_mcts) and Factored Value MCTS [https://github.com/JuliaPOMDP/MAPOMDPs.jl/tree/master/src/fv_mcts]. We are working on the NeurIPS submission, so could you send you the paper draft.
