### ISSUE TITLE
Adding solvers to Julia general registry

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#303]
After some discussion on slack, it seems like most of the problems that we originally had with the julia registry are fixed, so perhaps it is time to add all of our packages and abandon our own registry.

**Comment by rejuvyesh** [comment]
POMDPs have lot of unusual abbreviation names that General Registry doesn't always like. Although I haven't seen what was discussed on the Julia slack channel.

**Comment by MaximeBouton** [comment]
Let's make sure that abbreviations are ok, if we have to rename all the solvers it would be a major pain. 
A part from that I would say let's use the general registry.

**Comment by MaximeBouton** [comment]
If we want to keep a history of versions, one possibility is to make a PR to general and merge all the toml files: 
https://discourse.julialang.org/t/lhe-biofast-benchmark-fastq-parsing-julia-nim-crystal-python/39747/36

**Comment by MaximeBouton** [comment]
With POMDPs.jl v0.9 I think it is time to revive the discussion in here. As we update the solvers, should we also register them to general?

**Comment by zsunberg** [comment]
Actually, my vote is to wait until later. The registry that the solvers are in is not tightly linked to the version number. Since we all have other important priorities, I think the best way to move forward is through small incremental changes.

To me, this is not as high a priority as getting the interface to a stable and concise point.

**Comment by zsunberg** [comment]
I've been thinking some more about this... what would happen if we just started registering new versions of the solvers in General? Like if we just updated the DiscreteValueIteration Project.toml to 0.4.4 and ran JuliaRegistrator. What happens if different versions of the same package are registered in two different registries? Pkg might be able to just handle that.

If this works, we can just have the versions going forward from now registered in General, and if people want the old versions, they can get the JuliaPOMDP registry.

**Comment by zsunberg** [comment]
Seems like it might work: https://discourse.julialang.org/t/using-multiple-registries/16370/2?u=zsunberg

**Comment by zsunberg** [comment]
More evidence that it will just work: https://github.com/JuliaLang/Pkg.jl/pull/884

**Comment by zsunberg** [comment]
I think it will work! https://discourse.julialang.org/t/decentralized-package-manager/20931/8?u=zsunberg

**Comment by zsunberg** [comment]
Ok, it works flawlessly. DiscreteValueIteration 0.4.4 is now registered in General. We should register all new solver versions in General. I will create a new issue to track this.
