### ISSUE TITLE
Role of `gen` and `@gen`

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#309]
Discussion in #308 has raised the issue of the role of `gen`.

I see the following requirements ([Req] denotes an absolute requirement, [Nice-to-have] is not necessarily needed):

## Requirements
1. [Req] A way to handle the case where `sp`, `o` and `r` are generated at the same time
2. [Req] An explicit interface
3. [Req] A way to specify a generative transition model and explicit observation model (for POMCPOW)
4. [Req] A way to specify a generative observation model and explicit transition model (for QMDP with a complex observation model)
5. [Nice-to-have] Concise syntax for specifying a completely generative model
6. [Nice-to-have] Concise syntax for calling the generative model

In my mind, `gen` satisfies 1 and 5, `transition`, `observation`, and `reward` (TOR) with optional implicit distributions satisfies 2, 3, and 4. `@gen` satisfies 6.

Previously, I thought we needed `gen(DDNNode, ...)` to handle 3 and 4, but now I think `ImplicitDistribution` is better.

The documentation could emphasize the "generative interface" less. Instructions for what model to implement could follow:
- If an explicit transition **or** observation model is available, implement TOR, possibly using `ImplicitDistribution` if one of the components is generative.
- If the entire model is generative, implement `gen`.

`gen` (or at least a function that returns `(sp= , r= )`) is a very nice syntax for QuickPOMDPs, expecially if people just want to use MCTS, so I think we should keep it.

I'm very open to changing this if we have a good reason and can support all of the requirements.

**Comment by zsunberg** [comment]
7. [Nice-to-have] A way to return extra debugging info.

`gen` also satisfies this because you can return `(sp= , o= , r= , info= )` and call `@gen(:sp, :o, :r, :info)`

**Comment by MaximeBouton** [comment]
8. [Nice-to-have] concise syntax for sampling initial state and observations e.g. `@gen(:s)(m, rng)`, `@gen(:o)(m, s, rng)`

**Comment by zsunberg** [comment]
Is it scarier than `gen(DDNOut(:sp, :o, :r), m, s, a, rng)`?

**Comment by MaximeBouton** [comment]
No ^^

**Comment by zsunberg** [comment]
I think we should limit `@gen` to just be used for complete dynamic steps that take `s` and `a` as inputs. (i.e. we don't need `@gen(:s)(m, rng)`, `@gen(:o)(m, s, rng)` because `rand(rng, initialstate(m))` is not too bad and `rand(rng, initialobs(m, s))` will only be used in the RL context.
