### ISSUE TITLE
better error messages

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#31]
Debugging would be a whole lot easier if we made the error messages more verbose, e.g.

```
MyPomdp does not implement reward for states of type MyStateType and actions of type MyActionType
```

instead of just

```
MyPomdp does not implement reward
```

This would help when diagnosing problems like `action` accidentally returning the wrong thing or returning `nothing`.

Can I go ahead and start adding things to the error messages? Has anyone else been thinking about this? Do we want to have some kind of standard format or base it off of some principles?

**Comment by zsunberg** [comment]
With the @pomdp_func macro, the error messages are now uniform and more informative, but we should definitely think about what they should look like. We can now change them all from one place, so changes should be easier.

**Comment by zsunberg** [comment]
Now we're in a position to implement some nice error messages.

The message currently looks like this:
```
ERROR: POMDPs.jl: No implementation of discount for pomdp::MyPOMDP.
 in error at ./error.jl:21
 in discount at no file
```

I'm thinking that they should look like:
```
ERROR: POMDPs.jl: No implementation of discount for pomdp::MyPOMDP.

For documentation, see https://github.io/JuliaPOMDP/POMDPs.jl/latest

Please implement the following function as part of the problem definition:
function POMDPs.discount(pomdp::MyPOMDP)
    # your implementation here
end

 in error at ./error.jl:21
 in discount at no file
```

or like
```
ERROR: POMDPs.jl: No implementation of discount for pomdp::MyPOMDP.
Did you forget to explicitly import discount from POMDPs?
For documentation, see https://github.io/JuliaPOMDP/POMDPs.jl/latest

 in error at ./error.jl:21
 in discount at no file
```

What do y'all think?

**Comment by etotheipluspi** [comment]
I like the idea of more verbose errors. We can also have a simple lint-like tool for each solver that does a simple method check for the pomdp type passed in by the user and throws errors from the POMDPs.jl module if a method is not found. It could look like:

```julia
check(solver, pomdp) # or consistancy_check or method_check
# or even
MCTS.check(pomdp)
```

**Comment by ebalaban** [comment]
Agree on the more verbose error messages. Method checking for POMDP types might be a bit of an overkill though...

**Comment by zsunberg** [comment]
It would be nice to leverage julia's built-in MethodError framework so that we can have better, more informative error messages; it would especially be nice to show the closest candidate.

Also, I think it would be useful for the error to be customized based on whether the function is usually associated with the solver, problem, or simulator. For example, the error message for `discount` should say that it belongs in the problem definition and should suggest that the problem writer use importall POMDPs.
