### ISSUE TITLE
Solver package update checklist

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#312]
To update a solver to v0.9, the following actions need to be performed:
- In Project.toml, update `[compat]` for `POMDPs` to include `0.9`
- Use `@gen` instead of `gen(DDNOut, ...)`
- Use `rand(rng, initialstate(m))` instead of `initialstate(m, rng)`
- Use `initialstate(m)` instead of `initialstate_distribution(m)`
- Use `rand(rng, initialobs(m, s))` instead of `initialobs(m, s, rng)`
- Check for deprecation warnings in tests
- If the solver specifies requirements, use the versions from `POMDPLinter` (probably by importing them explicitly)

------------

- [x] DiscreteValueIteration [@zsunberg]
- [x] LocalApproximationValueIteration
- [x] GlobalApproximationValueIteration [@zsunberg]
- [x] MCTS [@zsunberg ]

- [x] QMDP [@zsunberg]
- [x] FIB [@zsunberg]
- [x] BeliefGridVI [@MaximeBouton]
- [x] SARSOP (POMDPXFiles)
- [x] BasicPOMCP [@zsunberg] (waiting on ParticleFilters)
- [x] ARDESPOT [@zsunberg]
- [x] MCVI [@zsunberg]
- [x] POMDPSolve [@zsunberg]
- [x] IncrementalPruning [@zsunberg]
- [x] POMCPOW [@zsunberg]
- [x] AEMS
- [x] ParticleFilters [@lassepe]
- [x] RLInterface [@MaximeBouton]
- [x] DeepQLearning [@MaximeBouton]
- [x] TabularTDLearning [@MaximeBouton]
- [x] POMDPTesting

**Comment by MaximeBouton** [comment]
What about the new POMDPLinter? Should we use this for dependencies?

**Comment by zsunberg** [comment]
Good call. I will add it.

**Comment by MaximeBouton** [comment]
just a clarification for the `compat` , the `@gen` change is not backward compatible right? so should compat be: 
`POMDPs = "0.9"` in that case?

**Comment by zsunberg** [comment]
No, I put @gen in 0.8.4 actually

**Comment by zsunberg** [comment]
I mean it's fine to just update to only `POMDPs = "0.9"` if that is easiest, but it is also a possibility to do `POMDPs = "0.8.4, 0.9"` with `@gen`

**Comment by zsunberg** [comment]
Ok, I added a checked list to keep track of the solver updates. If you're willing to help, please put your name by an item and claim it!

**Comment by lassepe** [comment]
What about ParticleFilters.jl? Or is this tracked somewhere else (since it's not a solver)?

**Comment by zsunberg** [comment]
We should track it here.

**Comment by zsunberg** [comment]
@MaximeBouton thanks for doing SARSOP!

**Comment by zsunberg** [comment]
@lassepe a lot of the remaining solvers depend on ParticleFilters. did you have a chance to start updating it yet?

**Comment by lassepe** [comment]
Sorry for the delay guys. I got around to fix most of the things today but I am getting an error in two of the `@implemented` tests for `obs_weight`. I marked them as `@test_broken` for now. I'm not sure what is going on there. Did we change anything about the way `obs_weight` works?

 Everything else should be done.

I can have another look at it tonight and figure out what is going on. But if you are faster than me @zsunberg or know immediately how to fix the `obs_weight` issue, feel free to jump in!

**Comment by zsunberg** [comment]
Thanks - you can just leave it as a test broken for now, and I will take a look at it

**Comment by lassepe** [comment]
I got around to fix it. The issue was that as of https://github.com/JuliaPOMDP/POMDPModelTools.jl/commit/980076dbb367c4b26ed6eaa277ec16d9832e7577 there is only the 5 argument version of `obs_weight` provided by default now. Also it seems as if `@implemented obs_weight(::P,  ...)` returns true even if for `P <: POMDP` neither `observation` nor `obs_weight` is implemented (?). 

I removed the tests for the other methods of the `obs_weight` weight function.
Also, I found a bug in the travis config for ParticleFilters.jl (https://github.com/JuliaPOMDP/ParticleFilters.jl/issues/39) which caused it to only ever build the docs but never run the test. This has been around for a while and we may want to check whether this has happened with any other package.

**Comment by lassepe** [comment]
Should I already tag/release/register a new version for ParticleFilters.jl?

**Comment by zsunberg** [comment]
Yeah... implemented has been a mess since POMDPs 0.8. It was never really that clean to begin with. When in doubt, implemented should just return `missing`. Avoid relying on it outside of POMDPLinter.

Yes, please register a new version!

**Comment by lassepe** [comment]
Okay, all done!

**Comment by zsunberg** [comment]
Thanks @lassepe this is much appreciated!

**Comment by zsunberg** [comment]
OK, we're done with the solvers!
