### ISSUE TITLE
How to fix the initial state?

### ISSUE THREAD

**Issue by Chengyang-Wu** [JuliaPOMDP/POMDPs.jl#316]
What should I do if I want to fix the initial state, but keep the initial belief uniform on the whole state space?
The random initial state usually cause a high variance of the performance. A way to address it is to fix the initial state, but meanwhile I don't want the initial belief concentrate on the real initial state. How can I make this?

**Comment by Chengyang-Wu** [comment]
For someone who might have the same question, you can specify the initial state in POMDP.simulate()
` simulate(simulator, pomdp, policy, [updater [, init_belief [, init_state]]]) `

**Comment by zsunberg** [comment]
Thanks for providing the breadcrumb for people!
