### ISSUE TITLE
Why is POMDPs v0.9 lower bounded to Julia v1.1?

### ISSUE THREAD

**Issue by mossr** [JuliaPOMDP/POMDPs.jl#321]
Ritchie Lee is required to use Julia v1.0.3 for a project and wants to use POMDPStressTesting which requires the latest MCTS, yet POMDPs 0.9 is restricted to Julia 1.1 as a lower bound. If you "dev" POMDPs.jl you're able to bypass the Julia version requirement. I did that to test POMDPStressTesting and passed all of my tests.

I'm just curious what the rational was to add the Julia 1.1 bound.

**Comment by zsunberg** [comment]
Did all the POMDPs.jl tests pass? At some point I used something that was not in 1.0, I think in @gen, but I may have removed it in some type of cleanup.

**Comment by lassepe** [comment]
If I recall correctly, Julia 1.0.3 type inference could figure out the return type of `@gen` which made it essentially unusable.

**Comment by zsunberg** [comment]
That is true, but I am 90% sure that wasn't the reason that I did it. I
think there was something that just flat-out didn't work.

**Comment by mossr** [comment]
@zsunberg I'd imagine that it was originally because the POMDPs registry doesn't work for 1.0. While `@inferred` fails because it thinks `@gen` always returns `Any`, I'm still able to use `@gen` as expected in Julia 1.0 without issues.

If I ignore the `@inferred` tests and wrap `POMDPs.add_registry()` with `if VERSION ≥ v"1.1"`, all other tests pass.

**Comment by zsunberg** [comment]
Ah, yeah, I think it is because of those reasons. Would it be extremely helpful to you if we tagged POMDPs 0.9.2 that is compatible with Julia 1.0? It seems like anything built with Julia 1.0.3 would be compatible with POMDPs 0.8.

**Comment by mossr** [comment]
That would be very helpful!
