### ISSUE TITLE
Use POMDPs to solve a simple routine economics problem.

### ISSUE THREAD

**Issue by azev77** [JuliaPOMDP/POMDPs.jl#326]
Hi and thank you for this package!

How can I use this package to solve a very routine dynamic programming problem economists usually solve with value function iteration? 
Here is the problem (which happens to have a simple closed form solution, so we can check)
<img width="342" alt="image" src="https://user-images.githubusercontent.com/7883904/98152038-17a11c80-1e9f-11eb-99f4-fe9e200290db.png">

Using your terminology:
state variable: k
action variable: c
reward function: log(c)

**Comment by lassepe** [comment]
I am not sure, whether I'm understanding the problem. Maybe you can clarify:

1. It seems that the problem has deterministic dynamics k' = k ^ \alpha - c

2. The immediate reward seems to depend only on action c. If there are no additional constraints or a terminal reward that depends on the state, why is it not optimal to always choose c -> infinity regardless of the current state k? Am I misinterpreting the problem statement or is it missing additional information to make it well-posed?

**Comment by azev77** [comment]
@lassepe let me rewrite it w/ different notation:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/7883904/98174797-6cef2500-1ec3-11eb-83d9-2b2703094e7b.png">
Please let me know if this is clear.

**Comment by lassepe** [comment]
I guess that clarified things a little bit for me but still, I feel like this is missing a constraint. Are you maybe implicitly assuming that k must be non-negative for all time?

**Comment by azev77** [comment]
Yes: 
k_t >0. but you're starting w/ k_0 >0 and this constraint would never really bind
c_t>0. This wouldn't matter much b/c log(c)=-Infinity if c=0.

Here is how to do this w/ QuantEcon's solver:
```julia
using QuantEcon, SparseArrays;

α=.65; β=.95; f(k)=k.^α; u_log(x)= x > 0. ? log(x) : -Inf ;
n=500; grid = range(1e-6, 2.0, length = n);
C = f.(grid) .- grid'
#
coord = repeat(collect(1:n), 1, n)
s_indices = coord[:]
a_indices = transpose(coord)[:]
L = length(a_indices)
#
R = u_log.(C[:])
Q = spzeros(L, n) # Q = zeros(L, n)
for i in 1:L
    Q[i, a_indices[i]] = 1
end
ddp = DiscreteDP(R, Q, β, s_indices, a_indices)
r_pfi  = solve(ddp, PFI)
r_mpfi = solve(ddp, MPFI)
r_vfi  = solve(ddp, VFI)
```

**Comment by zsunberg** [comment]
Thanks for posting! It's good to get problems from different fields. It would be great to make this package easier to pick up for economists!

I think something like this works:
```julia
using POMDPs
using QuickPOMDPs: QuickMDP
using POMDPModelTools: Deterministic
using DiscreteValueIteration

const n = 500
const α = 0.65
const β = 0.95
const max_k = 2.0

const states = range(1e-6, max_k, length=n)
ceil_state(k) = states[searchsortedfirst(states, k)] # there is probably a better way, but this minimized thinking

valid_actions() = range(1e-7, max_k^α, length=100)    # all of the possible actions
valid_actions(k) = filter(<(k^α), valid_actions())   # all of the valid actions for k

m = QuickMDP(
    states = states,
    actions = valid_actions,
    transition = (k, c) -> Deterministic(ceil_state(k^α - c)),
    reward = (k, c) -> log(c),
    discount = β
)

solver = SparseValueIterationSolver(verbose=true)
policy = solve(solver, m)
@show value(policy, first(states))

ω = α*β
A1 = α/(1.0-ω)
A0 = ((1-ω)*log(1-ω) + ω*log(ω))/((1-ω)*(1-β))
@show A0 + A1 * log(first(states))
```

You may be able to do better with GlobalApproximationValueIteration or LocalApproximationValueIteration, but I did not have time to try. (@Shushman this might be an interesting toy problem to try on those)

**Comment by azev77** [comment]
@zsunberg thanks it works well!!!
1. I added code to my previous comment to simulate. 
How can I simulate this model? 
2. How can I solve a finite horizon version w/ T=120 & k_120=0.
3. how can I include an inequality constraint eg: `g(k,c) < = 0`? 
4. to make this friendlier to economists can we make a simple example-note on how to translate a "generic" dynamic programming problem into POMDP form? 
Here is the most [well known economist formulation](https://julia.quantecon.org/dynamic_programming/discrete_dp.html).

**Comment by azev77** [comment]
Here's a stab at a very basic case (sorry if I missed this in the docs):
<img width="157" alt="image" src="https://user-images.githubusercontent.com/7883904/98282358-1ee22c00-1f6c-11eb-9c4c-caa4b4f38f6b.png">

Now translated to POMDP.jl: 
```julia
using POMDPs
using QuickPOMDPs: QuickMDP
using POMDPModelTools: Deterministic
using DiscreteValueIteration

const n = 500
const β = 0.95
const max_s = 2.0
const max_a = 1.5
const states = range(1e-6, max_s, length=n)

ceil_state(s) = states[searchsortedfirst(states, s)]
valid_actions() = range(1e-7, max_a, length=100)    # all of the possible actions
# valid_actions(k) = filter(<(k^α), valid_actions())   # not sure, g(s,0) ?

m = QuickMDP(
    states = states,
    actions = valid_actions,
    transition = (s, a) -> Deterministic(ceil_state( g(s,a) )),
    reward = (s, a) -> r(s,a),
    discount = β
)

solver = SparseValueIterationSolver(verbose=true) # pick favorite solver
policy = solve(solver, m)
# simulate(m, initial_s)
```

**Comment by zsunberg** [comment]
Hi @azev77, did you figure out your questions?

1. You can use the simulators from [POMDPSimulators.jl](https://juliapomdp.github.io/POMDPSimulators.jl/stable/), probably the [stepthrough function](https://juliapomdp.github.io/POMDPSimulators.jl/stable/stepthrough/#Stepping-through) is most intuitive.
2. Right now we don't have an automated way to convert to a finite-horizon problem. There is a stub for a package that does that here: https://github.com/JuliaPOMDP/FiniteHorizonPOMDPs.jl . Currently, you have to manually modify the state space to include the time, so, for instance, each state could be a (k, time) tuple, and `isterminal` can be used to indicate that the problem ends after a certain time.
3. I think the constraint would have to be in the action space (i.e. `valid_actions`) rather than the transition function. If you are OK with defining a discretized action space, you could use `filter` to enforce the constraint.
4. Sadly, I don't have time for that, but I would definitely support its development if anyone can spend time on it.
5. There isn't a policy iteration package, but it would be easy to implement one.

**Comment by azev77** [comment]
Before I forget: 
6. does POMDPs.jl have continuous-time solvers? Is that something they want in the future? 
For deterministic continuous-time problems:
[NLOptControl](https://github.com/JuliaMPC/NLOptControl.jl).jl looked promising for non-stochastic (deterministic) problems, but isn't being maintained much.
[SciML/OptimalControl](https://github.com/SciML/OptimalControl.jl).jl wants to have this in the future but we're gonna have to wait...

**Comment by rejuvyesh** [comment]
https://github.com/RoboticExplorationLab/TrajectoryOptimization.jl and related projects might be of interest for continuous control problems. They integrate with IPOpt etc appropriately.

**Comment by zsunberg** [comment]
6: Currently POMDPs.jl does not have any continuous-time solvers :/ I think it would take some serious design work to fit that in, and I think it would probably be worth creating another package.
