### ISSUE TITLE
Link to Tiger example Down

### ISSUE THREAD

**Issue by caseykneale** [JuliaPOMDP/POMDPs.jl#347]
https://www.cs.rutgers.edu/~mlittman/papers/aij98-pomdp.pdf

Is down. Might be better to give the full reference? Or restate the problem explicitly.

**Comment by rejuvyesh** [comment]
Full citation is:
> Kaelbling, Leslie Pack, Michael L. Littman, and Anthony R. Cassandra. "Planning and acting in partially observable stochastic domains." Artificial intelligence 101.1-2 (1998): 99-134.

Alternative link is: https://people.csail.mit.edu/lpk/papers/aij98-pomdp.pdf

**Comment by rejuvyesh** [comment]
Fixed in 4845476.

**Comment by caseykneale** [comment]
No problemo feel free to close out the issue :D
