### ISSUE TITLE
Move to GitHub Actions CI

### ISSUE THREAD

**Issue by rejuvyesh** [JuliaPOMDP/POMDPs.jl#348]
travis.org is going away. Also IME GitHub Actions CI is much faster as well. More importantly it is way more flexible and we can setup integration and bechmarks tests using something like https://github.com/tkf/Run.jl as is done in https://github.com/JuliaFolds/Transducers.jl/tree/master/.github/workflows/ for example.

**Comment by lassepe** [comment]
I'm in favor of GitHub Actions, especially for the speed. I think the workflows that are enabled by Run.jl would also work on travis, wouldn't they? Maybe I don't really understand what this package does. Doesn't it just enable a share environment for some extra dependencies? I have looked at its README a couple of times in the past and I never really understood how this is different from just using the normal test facility supported by Pkg.

**Comment by rejuvyesh** [comment]
Oh, I agree Run.jl by itself is not necessary. Was just pointing at an example!

**Comment by zsunberg** [comment]
I have added Github CI on all the repos, but I haven't disabled travis or removed the badges yet.

**Comment by zsunberg** [comment]
I'm going to close this and open another issue for removing the old stuff
