### ISSUE TITLE
Package Maintenance Github Actions

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#356]
For each package, we should make sure that the *the latest version* of the following github actions are installed:
- Github actions CI
- TagBot
- CompatHelper

It should be possible to do this with a script, e.g. perhaps with https://github.com/julia-actions/MassInstallAction.jl

**Comment by lassepe** [comment]
There is also: https://github.com/davidanthoff/julia-pkgbutler

**Comment by zsunberg** [comment]
Thanks, @lassepe, I already have massinstallaction up and running for now so I'll probably stick to that for this round, but maybe this can help in the future.

**Comment by zsunberg** [comment]
Alright, I think this is done, though documenter is probably broken on packages that use it.
