### ISSUE TITLE
Documentation policy

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#36]
Hi guys, can we clarify our documentation policy?

Right now, I see documentation cropping up (or potentially cropping up in the future) in three places:

1. In the readme
2. In the source files
3. In the "Main Doc" mentioned in the JMLR roadmap #30

To me this seems like one too many places. Can we clarify which of these will be supported so that we can put a lot of work into making at least one or two of them really good and consistent, rather than sporadically making changes and forgetting to fix documentation everywhere?

Do we want to try to maintain all three? Maybe the README should just have the function names and documentation should be elsewhere? Is there a tool for automatically converting inline documentation in the source to become the skeleton of a main doc?

**Comment by ebalaban** [comment]
@zsunberg, it's a great idea to discuss this. Personally, I'd prefer autogeneration of README from the source comments and a separate, more detailed paper describing the design philosophy (i.e. the "Main Doc"). I looked around for just a few minutes and found Judo.jl so far that looks somewhat promising, albeit not actively developed (https://github.com/dcjones/Judo.jl). Perhaps others will know of similar packages that we could use.

**Comment by zsunberg** [comment]
It might be fairly simple to throw something together ourselves to autogenerate the readme, perhaps using a template engine like [Mustache.jl](https://github.com/jverzani/Mustache.jl) and macros or something

**Comment by mykelk** [comment]
How about [Docile.jl](https://github.com/MichaelHatherly/Docile.jl). It's active and supports 0.3 and 0.4.

**Comment by zsunberg** [comment]
Looks like we might need
http://sphinx-doc.org/tutorial.html
and/or
https://github.com/JuliaLang/JuliaDoc

**Comment by etotheipluspi** [comment]
There is native support for documentation in Julia 0.4 that looks exactly like Docile. I'm planning to update QMDP, Value Iteration and SARSOP with this format.
http://docs.julialang.org/en/latest/manual/documentation/

I'm still not sure what the best way to generate readthedocs type of documentation is, but I do think we should start using this format to document all other methods/functions/types. We should create a separate docs.jl file for each module where the documentation lives to avoid cluttering the code. 

What do you all think?

**Comment by mykelk** [comment]
+1 for suggestion by @etotheipluspi

**Comment by ebalaban** [comment]
Looks pretty cool. We can probably find a happy medium between documenting things in the code and having more detailed descriptions in something like docs.jl (and README.md).

**Comment by zsunberg** [comment]
FYI, Spent some (too much) time today looking into automatically generating documentation from source docstrings. Fortunately, it looks like someone is writing an autodoc generator for julia at https://github.com/bastikr/sphinx-julia . Unfortunately, it doesn't seem to be plug-n-play with readthedocs quite yet.

I'm going to try to talk to the developer of that package and see if I can figure out how to get it working.

**Comment by zsunberg** [comment]
Did some more looking into this: It looks to me like we have three options. First, a definition: "autodoc" is a Sphinx plugin that automatically extracts docstrings from julia code and creates html pages with the docstrings in them. There appears to be an autodoc implementation for julia that can run on a local machine, but the readthedocs build environment does not include julia, so it cannot build that documentation.

Our options are:
1. Write documentation completely separate from the code **without autodoc** and have it automatically built and hosted on readthedocs.org (yuck! I really don't want repeated documentation)
2. Host the docs on github.io (it will look exactly like readthedocs), but build the documentation locally using sphinx with autodoc (and additional documentation that we write) and then push it to a gh-pages branch (http://lucasbardella.com/blog/2010/02/hosting-your-sphinx-docs-in-github)
3. Automate the build on travis-ci and host on github.io (or somewhere else)

Does anyone have any preferences? I suggest we start with (2) and maybe one day move to (3)

**Comment by mykelk** [comment]
That's fine. We might want a very short README.md that gives a very quick introduction but then points to the manual for details. Most of the popular Julia packages work this way, I think.

**Comment by etotheipluspi** [comment]
Just to wrap this up, @zsunberg and I have settled on using [Documenter.jl](http://michaelhatherly.github.io/Documenter.jl/latest/). Instructions on how to set it up with a github repo are in docs. For examples, see SARSOP or POMCP.

In general, the docs for each repo should contain:
- a home page that describes the role of the package
- a brief manual that contains install instructions (this should be easy) and a usage example
- the package API -  this can be built by Documenter if the code already contains docstrings
- any package specific docs 

Feel free to edit if I missed something.

**Comment by zsunberg** [comment]
As we just discussed, I would much rather put the docstrings in the source and get rid of docs.jl

**Comment by etotheipluspi** [comment]
Sounds good

**Comment by ebalaban** [comment]
Sure, let's try this. I too very much prefer keeping strings in the source.

**Comment by zsunberg** [comment]
Seems like we've settled on a good system with Documenter.jl
