### ISSUE TITLE
Documentation urls leading to missing page

### ISSUE THREAD

**Issue by Omastto1** [JuliaPOMDP/POMDPs.jl#360]
I have been looking for documentation on a generative interface and found that https://juliapomdp.github.io/MCTS.jl/latest/ and https://github.com/JuliaPOMDP/POMDPExamples.jl/blob/master/notebooks/Defining-a-POMDP-with-the-Generative-Interface.ipynb both have two URLs that should lead to the wiki page with the generative or explicit interface. Unfortunately, those pages no longer work, and I am unsure where updated links should lead.
Can somebody fix that?

**Comment by zsunberg** [comment]
Sorry, yes we will get to it eventually - about to do an overhaul of the docs though, so it will come after that.

**Comment by dylan-asmar** [comment]
URLs should be fixed in the documentation (check latest) after #539. If you find any more remaining issues, please reopen this issue.
