### ISSUE TITLE
Point to `SymbolicMDPs.jl` for PDDL support

### ISSUE THREAD

**Issue by rejuvyesh** [JuliaPOMDP/POMDPs.jl#379]
https://github.com/JuliaPlanners/SymbolicMDPs.jl

**Comment by zsunberg** [comment]
@ztangent FYI we linked to your package in 990f272  . Do you think we should say anything else about what SymbolicMDPs can do? My understanding is that it provides a way to create a POMDPs.jl MDP model from a PDDL model. Is there anything else that we should mention?

Thanks for your work on symbolic planning - looking forward to working with you to support the planning community!

**Comment by ztangent** [comment]
Yes, I think that's enough -- thank you for linking! :)
