### ISSUE TITLE
Upgrade AdaOPS to use POMDPTools

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#408]
See instructions at https://sites.google.com/view/pomdps-hackathon/pomdptools-upgrade-instructions

**Comment by dylan-asmar** [comment]
Pending PR merge of https://github.com/LAMDA-POMDP/AdaOPS.jl/pull/10

**Comment by dylan-asmar** [comment]
Completed with https://github.com/LAMDA-POMDP/AdaOPS.jl/pull/10
