### ISSUE TITLE
Upgrade POMDPSolve to use POMDPTools

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#410]
See instructions at https://sites.google.com/view/pomdps-hackathon/pomdptools-upgrade-instructions

**Comment by lkruse** [comment]
Might need to update POMDPFiles.jl first

**Comment by dylan-asmar** [comment]
Completed with https://github.com/JuliaPOMDP/POMDPSolve.jl/pull/23
