### ISSUE TITLE
Upgrade IncrementalPruning to use POMDPTools

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#411]
See instructions at https://sites.google.com/view/pomdps-hackathon/pomdptools-upgrade-instructions

**Comment by dylan-asmar** [comment]
https://github.com/JuliaPOMDP/IncrementalPruning.jl/pull/36

**Comment by zsunberg** [comment]
You can go ahead and merge that PR and close this.

**Comment by dylan-asmar** [comment]
Completed with https://github.com/JuliaPOMDP/IncrementalPruning.jl/pull/36
