### ISSUE TITLE
Transition from `LightGraphs.jl` to `Graphs.jl`

### ISSUE THREAD

**Issue by vancleve** [JuliaPOMDP/POMDPs.jl#424]
It seems like there isn't much code in `POMDPs.jl` that relies on `LightGraphs.jl`:
https://github.com/JuliaPOMDP/POMDPs.jl/blob/c4ce1190eddb1b0a23998b1843932465f88bf9ab/src/gen_impl.jl#L78

Maybe this works without modification using the updated `Graphs.jl` package? Would be nice to move to this since `Graphs.jl` is the replacement for `LightGraphs.jl`.

**Comment by zsunberg** [comment]
Honestly, this is a leftover artifact from POMDPs.jl v0.8. We should just hardcode it. PR welcome.

**Comment by zsunberg** [comment]
Actually, it's not very trivial to do something simpler than a topological sort there. If someone makes a PR to switch to Graphs, I'm happy to accept it.

**Comment by zsunberg** [comment]
nvm, this was actually easy to switch

**Comment by vancleve** [comment]
cool!
