### ISSUE TITLE
'POMDPTools' is not installable via general registry  

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaPOMDP/POMDPs.jl#437]
I can see the [POMDTTools has been registered](https://github.com/JuliaRegistries/General/pull/64708), but package manager says it isn't on the registry 
![image](https://user-images.githubusercontent.com/7087745/199240198-9c156b7e-0f5e-4b1b-86d0-9af4739be0ad.png)

I'm on Julia 1.8.2

**Comment by zsunberg** [comment]
That is strange - it currently works for me and my students. Perhaps your registry has not been updated in a while?

**Comment by YongHee-Kim** [comment]
Strange... registry is automatically updated. Since issue is with general registry, I will create issue there and close this one 

![image](https://user-images.githubusercontent.com/7087745/200827539-ff5f5528-9f65-40e4-943a-99bcb1d4da9f.png)

**Comment by zsunberg** [comment]
Thanks - hope this gets resolved!
