### ISSUE TITLE
SparseTabularMDP doesn't support initialstate

### ISSUE THREAD

**Issue by fredcallaway** [JuliaPOMDP/POMDPs.jl#444]
If I define an MDP with QuickMDP, I can specify an initialstate distribution which is automatically used in e.g. RolloutSimulator. But when I convert the QuickMDP to a SparseTabularMDP (for faster rollouts) the initialstate is lost. Any particular reason for this?

**Comment by zsunberg** [comment]
This seems like a bug. It should not be lost. Do you have a minimum example that will cause the problem

**Comment by zsunberg** [comment]
Upon looking, I see that `SparseTabularMDP` does not even have a field for representing the initial distribution.

**Comment by zsunberg** [comment]
Someone should make a pull request to add this. The probable reason that this was not added was that usually the sparse tabular representation is used for value iteration or similar offline methods that do not need an initial state distribution. But someone should add it for simulation purposes

**Comment by fredcallaway** [comment]
Cool, I'm on it
