### ISSUE TITLE
Support Hooks ?

### ISSUE THREAD

**Issue by NeroBlackstone** [JuliaPOMDP/POMDPs.jl#505]
Is there any counterpart of [Hooks](https://juliareinforcementlearning.org/docs/How_to_use_hooks/#What-are-the-hooks?) in `POMDPs.jl`?
As I know the only way to get information from `pomdps.jl` solver, is to copy and edit the solver source code. (it's my solution...
It's hard to plot if we don't have hooks.

I don't know if the maintainer of `POMDPs.jl` also thinks this is a useful feature.

And I wonder how to implement it.

**Comment by zsunberg** [comment]
So far, we have left the question of accessing additional information up to solver writers. The `solve_info` and `action_info` functions in POMDPTools sometimes output additional information.

Can you describe what information you are trying to get out of what solver, and perhaps we can think about generalizing from that point.

**Comment by NeroBlackstone** [comment]
Thanks for your reply.
For example, solvers in TabularTDLearning.jl, the solver will evaluate trained policy every `eval_every` episode. We want to get the [average reward](https://github.com/JuliaPOMDP/TabularTDLearning.jl/blob/df9af5929f56dd5342abd8ed77260c9a9ce370a5/src/q_learn.jl#L72) of the trained policy trajectory.

**Comment by NeroBlackstone** [comment]
[render](https://juliapomdp.github.io/POMDPs.jl/stable/POMDPTools/visualization/#Visualization) function has a similar concept, but it's for the problem.

**Comment by zsunberg** [comment]
I think it's best to try adding some hooks to that particular package and then generalize from that if we can find a way.

In general one challenge is that we have fairly different types of solvers in the POMDPs.jl ecosystem
1. Offline optimization solvers like SARSOP
2. Online tree search solvers like POMCP and DESPOT
3. Reinforcement Learning solvers like tabular td learning

The hooks for these different types might be very different.

**Comment by NeroBlackstone** [comment]
Yes, I agree with @zsunberg , since different types of solvers exist, maybe we never have a unified solution.

But when I was going to bed last night, I got some inspirations.

We could pass a callback function to `solve` function.

like:
``` julia
 function solve(f::Function,solver::QLearningSolver, mdp::MDP)
    # codes....

    f(episode,average_reward)

    # codes...
end
```

``` julia
solve(qsolver,mdp) do episode,average_reward
    # collect data!
end
# plot!
```

Unfortunately, it's a break change. Maybe we could define callback as optional args.

But I still think at least we could propose a "solver convention".

**Comment by zsunberg** [comment]
> But when I was going to bed last night, I got some inspirations.

@NeroBlackstone , thanks for using your bedtime thoughts to try to improve this package! :)

In general, I like this proposal, but there is one hard question related to the diversity of solvers: What arguments should be passed to the callback?

I also think that a better first step would be to add callbacks to individual solvers as solver options, for instance, it could be used like this
```julia
solver = NativeSARSOP.SARSOPSolver() do tree, alphas
    # print statistics from the tree or something
end
solve(solver, m)
```

One more note:

> Unfortunately, it's a break change.

I don't think this is actually a breaking change, because we could define `solve(f, solver, m) = solve(solver, m)` as a fallback.

**Comment by zsunberg** [comment]
closing for now since this seems to be a solver-specific issue.
