### ISSUE TITLE
value() arguments

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#52]
The `value()` function is supposed to return an unbiased estimate of the value of executing a policy from a belief state. One way to do this is to perform a rollout simulation.

POMCP uses value estimates based on the actual state in addition to the belief state. i.e. `value(policy, b, s)` should return an estimate of the reward accumulated by executing `policy` on belief `b` given that the actual state is `s`.

Does it make sense to add `value(::Policy, ::Belief, ::State)` to the interface? or should this just be a POMCP-specific thing?

Also, to perform a rollout, one needs a belief updater. Should the belief updater be an argument to `value()`, or should the updater be created from the policy via the `updater()` function?

**Comment by ebalaban** [comment]
I can see the utility of having `value(::Policy, ::Belief, ::State)`. As for the belief updater, my preference would be to supply the updater as an argument to `value()`. This way a non-default updater can be used or the default updater can be configured with optional parameters before being used for rollouts.

**Comment by etotheipluspi** [comment]
Would having ```State``` as an optional argument make sense for this type of function? If state is not passed, you can sample your initial state from the belief. If the user wants to specify a starting state then they can.

I vote against adding the belief updater into the function call. The belief updater can be passed with the policy type if needed. This will keep the interface cleaner in my opinion.

**Comment by mykelk** [comment]
I agree with @etotheipluspi.

**Comment by etotheipluspi** [comment]
I think we settled on the form `value{S}(::Policy, ::S)`
