### ISSUE TITLE
Listed version of Julia (i.e. 1.3) in Project.toml fails CI

### ISSUE THREAD

**Issue by dylan-asmar** [JuliaPOMDP/POMDPs.jl#532]
The current compat requirement of Julia is listed as 1.3 in the Project.toml ([link](https://github.com/JuliaPOMDP/POMDPs.jl/blob/c7ed59cc2f7d9901d18f035da9f5128cc0c3356e/Project.toml#L20C1-L20C14)). However, this version currently fails: https://github.com/JuliaPOMDP/POMDPs.jl/actions/runs/7256047786

I think we should change the compat requirements to the official LTS version of Julia, which is 1.6 ([Long-term support (LTS) release: v1.6.7 (July 19, 2022)](https://julialang.org/downloads/#long_term_support_release)) and modify the CI to include this min supported version as well to help us catch these potential issues in the future.

These are simple changes, but wanted the thoughts/opinions of the community.

**Comment by mykelk** [comment]
Yes, I think this is sensible.

**Comment by zsunberg** [comment]
Yep, that's a great plan!
