### ISSUE TITLE
slack link in README broken

### ISSUE THREAD

**Issue by FlyingWorkshop** [JuliaPOMDP/POMDPs.jl#542]
When I try to clink the [link](https://slackinvite.julialang.org/) in the readme, I get a site can't be reached error. 

PS: Sorry for raising so many small issues! I wanted to join the slack so I could address the issues there rather than on GitHub.

**Comment by dylan-asmar** [comment]
This should be fixed with #543. 

No need to apologize at all!!! Issues are the best way and preferred way to communicate problems like this.
