### ISSUE TITLE
Convert POMDPs.jl to use parametric abstract types?

### ISSUE THREAD

**Issue by ebalaban** [JuliaPOMDP/POMDPs.jl#56]
Should we make the major abstract types in POMDPs.jl parametric? These include POMDP, Solver, Belief, etc. They would be parametrized with state, action, and observation types, as appropriate. For example:
```julia
abstract POMDP{S, A, O}
```
Here are the pros and cons of this transition, as I see them:

Pros:
- Potential performance benefits for solvers and belief updaters that could now be compiled and optimized for the concrete types
- Simplified API: we would no longer need either `State`, `Action`, and `Observation` types or `create_state()`, `create_action()`, and `create_observation()` functions
- States, actions, and observations would now be representable by simple bits types (e.g. Int64), as they would no longer need to be subtypes of  `State`, `Action`, and `Observation`, respectively

Cons:
- A bit of a learning curve for problem and solver writers not familiar with templates / parametric types
- Modifications are required for all existing solvers, belief updaters, simulators, and, possibly, problems

This would be a fairly major API change, so please let me know if you see any other implications of it that I may have overlooked.

**Comment by ebalaban** [comment]
Ok, I added `templated` branch (for the lack of a better term), where virtually all of the types and function definitions are now parametrized. Please take a look. This version did improve DESPOT's performance by at least a factor of 2. I also think that templates make code more readable.

In addition to testing on a version of RockSample with immutable state, action, and observation types, I also created one with plain integer types (now that it's possible to do so). Both performed about the same, so problem creators would have two reasonably good choices when it comes to modeling their problem:

- If the problem is relatively simple and can be modeled with plain bits types (e.g. integers or floats), they can do that and keep their code clean and compact;
- If they need to express something a little more elaborate, they can use immutable composite types and get similar performance, but at the expense of perhaps having to write more lines of code.

There are a couple issues that we would need to resolve:

- 'isterminal' for states and observations needs to have different names (Julia can't tell the templated versions apart). For now I named them `isterminal` and `isterminal_obs`, but `is_state_terminal` and `is_obs_terminal` might be better. I am open to other ideas as well.

- I'd like to add templated `index` for actions and observations (in addition to states). These would, again, need to have different names, perhaps `state_index`, `action_index`, `obs_index`. Not very "Julian", but what can you do.

**Comment by mykelk** [comment]
I like `state_index`, `action_index`, and `obs_index` (or `observation_index`). Besides being a better design, do you get an additional speed improvement with this?

**Comment by ebalaban** [comment]
I saw a speed improvement of maybe a few percent after templating these functions. Not huge, but I'll take it.

**Comment by zsunberg** [comment]
I think that the fact that this reduces (or even eliminates?) the performance penalty for using POMDPs means that we *need* to adopt it.

I also think the support for non-composite state, observation, and action types will make the code for simple problems much more concise, which will be really useful for introducing newcomers to the framework and for testing solvers.

@ebalaban, thanks so much for taking the time to investigate this thoroughly! I was really nervous about the fact that we did not yet have a thorough test of the performance of POMDPs.

**Comment by ebalaban** [comment]
No problem, the performance hit was really bothering me. I see no downside of implementing these changes, except for users needing to understand a little bit about how templates work (not a big deal, in my opinion, just an additional set of parameters).

I would suggest that each one of us does some benchmarking before and after (if we decide to transition). This way we can validate the speed improvements I am seeing on a more diverse set of solvers/problems. I'll also do some more testing later today with larger problems. I've been keeping track of my benchmarking results in DESPOT.jl/test/perflog.md, by the way, in case you are interested.

**Comment by ebalaban** [comment]
I benchmarked DESPOT with larger RockSample problems and as the problem size increases and tree building starts to take a greater share of run time relative to bounds estimation (the latter is loop-intensive), the performance gap narrows:

RockSample(4,4): 24%
RockSample(7,8): 22%
RockSample(11,11): 9%

The full results are in [perflog.md](https://github.com/sisl/DESPOT.jl/blob/master/test/perflog.md). Has anyone else had a chance to look at the new code? Any comments?

**Comment by zsunberg** [comment]
FYI I'm going to start spending a little time every day working on converting stuff to the parametric interface. (the more projects I start working on that use POMDPs.jl, the more important it is to get the interface up to a stable version). I will do this by creating a `parametric` branch for each repository. Then, when we're ready, we can merge all of the parametric branches to master.

**Comment by zsunberg** [comment]
FYI, a performance data point:
For 100,000 simulations of the crying baby problem with the feed-when-crying-policy (see POMDPModels/test/crying_speed_test.jl)
old mutable types:
 26.538341 seconds (39.70 M allocations: 1.279 GB, 3.01% gc time)
parametric:
  7.478745 seconds (19.70 M allocations: 349.423 MB)
3.5x speed up

**Comment by mykelk** [comment]
Yay!

**Comment by zsunberg** [comment]
Perhaps just as importantly, the problem definition is now less than 100 lines (and could be shortened by moving some things to common packages), whereas before it was nearly 140.

**Comment by mykelk** [comment]
Love it.

**Comment by ebalaban** [comment]
Very nice, @zsunberg! Glad to see you also got a sizable performance improvement. Hopefully we can settle on a stable parametric interface soon.

**Comment by zsunberg** [comment]
Another really good upside to this is that problem-writers can use their state and action types from other projects with POMDPs.jl *without* having to declare them as or wrap them in subtypes of `State`, `Action`, and `Observation`. This makes POMDPs much more friendly to other packages.

(@rejuvyesh and @etotheipluspi , I forgot to mention this in our discussion yesterday)

**Comment by zsunberg** [comment]
Today in the meeting we resolved all the issues to merging this into master. Will probably merge the parametric branch into master tomorrow morning.

I will also create a tag called v0.1 with the repository as it is now.

v0.2.0 will be tagged after parametric is merged
