### ISSUE TITLE
Docs Failing Test

### ISSUE THREAD

**Issue by dylan-asmar** [JuliaPOMDP/POMDPs.jl#562]
The docs are failing (caught with our weekly automatic run).

I have included the error below. There were [some changes](https://github.com/JuliaLang/julia/blob/release-1.11/NEWS.md#random) with Random in the 1.11 release. However, I didn't dig too deeply into the changes.

If this part of the docs is testing functionality, then I think we can remove the test for the exact value?

```
┌ Error: doctest failure in src/def_pomdp.md:218-228
│ 
│ ```jldoctest
│ using Random: MersenneTwister
│ using POMDPTools: ImplicitDistribution
│ 
│ rng = MersenneTwister(1)
│ 
│ d = ImplicitDistribution(rng -> (-0.2*rand(rng), 0.0))
│ rand(rng, d)
│ # output
│ (-0.047206669[13](https://github.com/JuliaPOMDP/POMDPs.jl/actions/runs/11318604248/job/31596414110#step:5:14)240939, 0.0)
│ ```
│ 
│ Subexpression:
│ 
│ using Random: MersenneTwister
│ using POMDPTools: ImplicitDistribution
│ 
│ rng = MersenneTwister(1)
│ 
│ d = ImplicitDistribution(rng -> (-0.2*rand(rng), 0.0))
│ rand(rng, d)
│ 
│ Evaluated output:
│ 
│ (-0.019827940275727363, 0.0)
│ 
│ Expected output:
│ 
│ (-0.04720666913240939, 0.0)
│ 
│   diff =
│    Warning: Diff output requires color.
│    (-0.04720666913240939, (-0.019827940275727363, 0.0)
└ @ Documenter src/def_pomdp.md:2[18](https://github.com/JuliaPOMDP/POMDPs.jl/actions/runs/11318604248/job/31596414110#step:5:19)
```

**Comment by mykelk** [comment]
Unless we want to switch to StableRNGs, I think we should probably relax the exactness.

**Comment by dylan-asmar** [comment]
I'm ok with any change. I didn't write this test so I defer to others that might have insight.

**Comment by mykelk** [comment]
Cool. Which way should we go @zsunberg ?

**Comment by zsunberg** [comment]
We should use the stable rng. That is what it's meant for.
