### ISSUE TITLE
Travis and coveralls broken

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#61]
This seems to be the only breaking change when moving to the new organization. I will add all the existing repos to travis and coveralls.

@zsunberg and @ebalaban do you guys mind adding travis and coveralls to your solver repos as well now that we are in the new organization.

**Comment by zsunberg** [comment]
Hi Max, yeah, I will do that within the next week (I don't really know how
either of those things work, so I need to read up on it).

**Comment by ebalaban** [comment]
Same here. Been swamped with things, but will try to get to this in the 
next couple of days.

**Comment by zsunberg** [comment]
refiled this as an issue in DESPOT.jl
