### ISSUE TITLE
typealias Reward Float64

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#62]
Hi all,

what is the thinking behind having a Reward type aliased to Float64? In what cases is this useful? Will it lead to problems/confusion if some people use Reward and some people don't?

Just trying to decide whether it is a good idea to have it in there. Thanks!

**Comment by mykelk** [comment]
I think there were some reasons:
1. It makes the semantics more explicit. For example f(x::Reward) is more informative than f(x::Float64).
2. Maybe someone might like to change this to a Float32 for some reason in the future.
3. Writing 64 all the time feels funny. Even though a 64-bit float is a sensible representation, there's nothing canonical about that representation.

**Comment by zsunberg** [comment]
Hmmm... I guess I don't like this idea because there is no way to enforce its use. I think there are three paths forward (I have admittedly exaggerated the outcomes, but I think there is truth in them):

a) We keep Reward in the interface and don't document it well. It gets used haphazardly and inconsistently, and everyone who uses our interface has to take a few seconds to understand it.
b) We keep Reward in the interface and say that it should be used everywhere and document it well. It gets used haphazardly and inconsistently. We have to maintain the extra documentation, and this distracts from other core concepts.
c) We get rid of Reward and never look back.

The reasons 1, 2, and 3 given by @mykelk above are valid, but I personally think the cost outweighs the benefits. I don't think we need it, so I vote to remove it.

Some brief comments on the reasons given above:
1. I think f(reward) or f(r::AbstractFloat) or even f(r) is clear enough in most contexts.
2. I don't see a way for `typealias Reward Float64` to allow for a change to 32-bit without editing that line *within* the POMDPs.jl package, so I'm assuming that's what you mean. First, editing the code in someone else's package isn't a very elegant solution. Second, unless Reward is used *everywhere* (including in literals, e.g. Reward(0.0)), simply changing this one line won't automatically convert everything to 32 bit. Third, i find it pretty unlikely that someone is going to resort to using lower precision rewards for performance (is that really the bottleneck) and, if they do, they will already probably be pretty deep into editing other code already, so a convenient switch probably won't be that helpful.
3. If you want to avoid 64, using `AbstractFloat` in methods or even leaving the type annotation out completely seems just as good. If you want to create composite bitstypes, you *need* the 64 anyways.

**Comment by mykelk** [comment]
A few responses:

1. It is true that the difference in performance between using 64 bits and 32 bits is typically not significant. But, if you are storing a bunch of them in memory, it might mean using have the memory.
2. My previous bullet point might not apply to some kinds of architectures. You can probably envision some architectures (maybe very low power embedded processors) where 32 or 16 bit operations are much more optimized.
3. You are right. If you wanted to change Reward to be Float16 or Float32 or whatever, you would need to change the source.
4. I wouldn't recommend doing Reward(0) since it feels to heavy. I would just use 0 or 0.
5. I think the interfaces can have Reward in it. It takes one sentence to explain that it is just typealiased as a Float64. If the user uses Float64s internally or whatever, nothing breaks.
6. The problem with AbstractFloat is that using an array of AbstractFloats is very inefficient. Reward would be a concrete type. Of course, you could use templating, but that feels like overkill.
7. I suppose my (very slight) opinion is mostly shaped here by the feeling that Float64 feels a little ugly in the interface since it is tied to an arbitrary representation.
8. Again, my preference is very slight, and I'm happy to go with the majority view.

**Comment by zsunberg** [comment]
1. Ok, that is a valid use case, but again, it relies on consistent usage
throughout all packages (which we can't enforce, and I don't really want to
keep reminding people)
4. Right... we have to make sure no one ever uses unadorned 0.0 though
5. This is exactly the problem! :-) Some people will just use Float64 in
their solvers and it will be inconsistent. It takes multiple sentences
(that people might miss) to explain that it is here in case someone wants
to change to a different precision, and you should use it in every place
that deals with a reward, and you should never use 0.0
7. Ooooohhhh, ok, now I see why it's ugly - because Float64 is used in the
actual interface, not because Float64 is in solvers or problems. If that is
the main concern, then we should just use AbstractFloat. Having concrete or
abstract types in method signatures makes no difference in performance
(AFAIK), and I don't think we have anything in the interface with arrays or
composites that are supposed to be bitstypes.

I guess my real argument is that I want everything in the interface to have
concrete justification. I think we are overplanning by saying one day
someone might want to change precision and would use this. I think we
should cross that bridge when we get to it and have a better idea of the
details.

If we do keep it, I think we should establish expectations: e.g. Should it
be used in all solvers?

Sorry if this is a lot to parse. This is mostly experimental. I'm testing
my prejudices to see if they're right or wrong.

**Comment by zsunberg** [comment]
Actually, I don't really see what you mean in (7) - the only places that Reward and Float64 occur in the interface are in the typealias line. The interface itself is already 64-free. The only place Reward would get used is in solvers and problems.

**Comment by mykelk** [comment]
Sounds good. You can get rid of it.

**Comment by zsunberg** [comment]
I'll leave this open for a while longer just in case anyone has any other reasons

**Comment by tawheeler** [comment]
I agree with @zsunberg. Whenever I see `::Reward` my first response is "what is thus custom type?". I would only typealias if the type were very long, such as with a vector of vectors, or a complicated Distribution.

When the input is ambiguous (`foo(r::Float64)`) I would use `foo(reward::Float64)` instead.

**Comment by etotheipluspi** [comment]
I'm ok with no type alias to Reward in the interface.
