### ISSUE TITLE
State, Action, Observation types in parametric interface

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#63]
Hi all,

In the parametric branch, I got rid of State, Action, and Observation types because, if someone uses them in a solver or simulator, that solver or simulator would not be compatible with POMDPs that have built in bits types for states.

The other option would be to keep them for clarity, but just typealias them to Any.

Does anyone have any opinions on this?

**Comment by mykelk** [comment]
Yeah, get rid of them. They will be parametric types in the new design.
