### ISSUE TITLE
parametric: allocating bitstype states

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#64]
Before switching to the parametric type scheme, we had `create_state` etc. to allocate an empty state object. I was assuming that for the parametric interface, we would just use `S()` for that, but common bitstypes like `Int` don't have a zero argument constructor. (Obviously, we don't get any performance gain by preallocating immutable types, but it is nice to write code that works efficiently with both mutable and immutable)

I see a few options:

1. In POMDPs.jl write default constructors for common types, e.g. `Base.Int() = zero(Int)`
1. having a `create(T::Type)` function in the interface that defaults to `zero(T)`
1. requiring users to implement `zero()` for their state types (or is there some other function that I don't know about that does what we want?)
1. dropping support for using preallocated objects
1. writing code that branches based on whether the types are mutable using `isimmutable`
1. writing different code for immutable and mutable states (don't know how this would look exactly)
1. always creating states, actions, etc by using one of the interface functions with optional arguments, i.e. having a lot of code like
```julia
        if step == 1
            a = action(policy, b)
        else
            a = action(policy, b, a)
        end
```

Did anybody already find a way around this (@ebalaban, what did you do?)? Any preferences. I guess I think option 1 is the best perhaps.

**Comment by mykelk** [comment]
I vote for 1.

**Comment by tawheeler** [comment]
1 seems cleanest and easiest to reason about.

**Comment by zsunberg** [comment]
going with option 1 for now. Re-open if there are problems
