### ISSUE TITLE
Reasons for supporting mutable states, actions, observations

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#65]
Hi all,

I was thinking the other day that supporting mutable types makes things rather more complicated (i.e. there are all these optional final arguments, I worry about making copies sometimes, you have to reason about both mutables and immutables, is code optimized for one efficient for the other?, what about #64, etc.). What if we were to only support immutable types? (of course big things like distributions could still be mutable)

The biggest caveat that I see to this is that people might get confused if they use vectors either within their custom types or use vectors themselves as states. One could use [FixedSizeArrays](https://github.com/SimonDanisch/FixedSizeArrays.jl) to get around this.

So what are the reasons that we support mutable states, actions, and observations? Do these reasons outweigh the extra complexity?

**Comment by mykelk** [comment]
I think the idea was that sometimes states/actions/observations can be pretty big (e.g., a point cloud) and you want to avoid doing a bunch of memory allocations.
