### ISSUE TITLE
POMDP functions should *NOT* be gauranteed to modify their final arguments

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#66]
(note the all-caps and asterisks are for emphasis, not frustration)

Today I came across the following code in POMDPModels:
```julia
function rand(rng::AbstractRNG, space::GridWorldStateSpace, s::GridWorldState=GridWorldState(0,0))
    state = space.states[rand(rng, 1:end)]
    copy!(s, state)
end
```

the only reason to have the copy line is if the caller should expect that `s` will be modified. I was under the impression that the caller of any function in the interface should *always* use the value returned by the function, and the person who implements the function may or may not modify the optional final argument.

So, the function above can be implemented as
```julia
rand(rng::AbstractRNG, space::GridWorldStateSpace, s::GridWorldState=GridWorldState()) = space.states[rand(rng, 1:end)]
```

Does anyone disagree with this? I think it's important to be on the same page about this type of thing - if we aren't uniform, it could mean that some problems don't work correctly with some solvers.

**Comment by mykelk** [comment]
I agree strongly with you on this.

**Comment by etotheipluspi** [comment]
I'm not sure I follow. Why have the optional pre-allocated argument if it won't get modified? Are you proposing a possible alternative to implementing the function or are you suggesting we should implement it the way you have it?

**Comment by mykelk** [comment]
It will modify the preallocated argument and return it if it is mutable. If it is immutable, it can't modify it, and so it will just return the new value.

**Comment by etotheipluspi** [comment]
Ok, I see. However, in the grid world example the states are mutable, so the input argument should be modified as in the original function. Or am I missing something here?

**Comment by zsunberg** [comment]
Yeah @etotheipluspi , that's exactly what I am saying.

@mykelk , above, when you say "It will modify...", I think it would be better to say "If computationally advantageous, it *may* modify..."

**Comment by mykelk** [comment]
You are correct.
