### ISSUE TITLE
Should Policy be parameterized?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#68]
In my experience working with the parametric interface so far, I have not come across a place where it is useful to have the `Policy` abstract type parameterized. Usually it is easier to just make my policies subtypes of `Policy` without any parameterization. I am not sure what ramifications this has.

Should `Policy` be parameterized?

**Comment by mykelk** [comment]
At the moment, I can't think of a reason to make it parameterized.

**Comment by etotheipluspi** [comment]
I think subtypes work well for this. There is a distinction between MDP and POMDP policies (belief vs state), so this may be something to think about. Although this would not fit into the current S,A,O parameterization model we have.

**Comment by zsunberg** [comment]
@etotheipluspi I'm not quite sure what you mean... Did you mean that subtyping an unparameterized abstract Policy type is adequate approach?

for now I'm getting rid of the parameterization

**Comment by zsunberg** [comment]
This same issue applies to `Simulator`. I think it might make sense for concrete subtypes of Simulator to be parameterized, but I don't think the abstract type needs to be parameterized, and I think using the framework will be easier without it.

I am removing the parameterization of `Simulator` for now

**Comment by zsunberg** [comment]
This is superseded by #71
