### ISSUE TITLE
Bringing back create_state(), create_action(), create_observation()

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#69]
Sometimes, the state structure depends on problem parameters. For example, in @cho3 's MultiLanePOMDP code, the state contains a vector of car states whose size depends on the number of cars in the problem

I see three options:
-> 1. Bring back `create_state(p::POMDP)`, `create_action(p::POMDP)`, and `create_observation(p::POMDP)`

In this case there would also be a default implementation for simple states such as Bool, Int, etc.
```julia
create_state{S}(p::POMDP{S<:Number}) = zero{S}
```

-> 2. Require that the state type has a 1 argument constructor that accepts a POMDP, i.e. `MyState(p::MyPOMDP)`

-> 3. Keep going with the zero-argument-constructor `S()` convention. If the problem-writer's state type depends on problem parameters, tough. They will just have to adjust the state later in other api functions when they have access to the problem.

I prefer option 1 for a few reasons
- There are other `create_` functions in the interface already, so this is uniform
- I never really liked the `S()` convention that much. The instructions "make sure your state type has a zero argument constructor" are less explicit than putting an explicit function in the interface.

Option 2 seems ok. Option 3 seems like a bad idea.

What does everyone else think?

**Comment by zsunberg** [comment]
I'm going to add the `create_` functions back into the parametric branch for now so that I can work with them.

**Comment by cho3** [comment]
I might be biased, but I think 1/2 makes more sense semantically. I agree in that option one seems to be a little more flexible, and fits in the current framework as I understand it. 

From the standpoint of actually writing a problem for this framework, I think 1/2 is also better just for the amount of information that you can use to initialize a state--it makes life much easier.

**Comment by etotheipluspi** [comment]
Just to be clear, the difference between 1 and 2 in code looks like this:

```julia
function transition{S,A,O}(pomdp::POMDP{S,A,O}, ...)
    s = create_state(pomdp) # 1
    # vs
    s = S(pomdp) # 2
    ...
end
```

I think 2 is a bit nicer since we don't have to add back additional functions to API. However, I am ok with either 1 or 2.

**Comment by tawheeler** [comment]
FWIW, `create_state(::POMDP)` makes more sense to me than both `MyState(::POMDP)` and `S()`.

**Comment by zsunberg** [comment]
Decided at the meeting to go with `create_`
