### ISSUE TITLE
removing ::Belief versions of action()

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#70]
When I de-parameterized Policy (#68), I got a bunch of ambiguous function warnings between

```
action(::Policy, ::Belief)
```
defined in POMDPs.jl and
```
action(::MyPolicy, ::Any)
```
defined in other packages.

To remedy this, I removed the declarations of
```
action(::Policy, ::Belief)
```
in POMDPs.jl and replaced it with
```
action(policy::Policy, state_or_belief)
```

I am not bound to this solution; this is mostly to get things to work for me for now. Is this OK as a permanent solution?

**Comment by mykelk** [comment]
This doesn't feel good at all to me. It seems like we want `action(::Policy, ::Belief)` in POMDPs.jl, and the definitions in the other packages should use a type other than `::Any`.

**Comment by zsunberg** [comment]
@mykelk I'm not sure how an MDP solver package can have a definition other than `action(::MyPolicy, ::Any)` (or `action{S}(::MyPolicy{S}, ::S)` if `Policy` is parameterized) in it.

Since we are going to support MDPs, we have to have `action(::Policy, ::Any)` in POMDPs.jl. Also having `action(::Policy, ::Belief)` in POMDPs.jl makes sense from a documentation standpoint, but it confuses LLVM.

**Comment by tawheeler** [comment]
I would think parameterizing Policy would be best, so Julia knows what state should be bound to a policy. `action{S}(::Policy{S}, ::S)` or `action{S,A}(::Policy{S,A}, ::S)`.

**Comment by mykelk** [comment]
I like your idea @tawheeler.

**Comment by zsunberg** [comment]
@tawheeler , thanks for the suggestion. I thought through that approach too, but unfortunately the same problem occurs:
```
julia> abstract Policy{S,A}

julia> abstract Belief

julia> action{S,A}(::Policy{S,A},::S) = error("not implemented")
action (generic function with 1 method)

julia> action{T<:Belief,A}(::Policy{T,A},::T) = error("not implemented")
action (generic function with 2 methods)

julia> type MyPolicy{S,A} <: Policy{S,A} end

julia> action{S,A}(::MyPolicy{S,A},::S) = 1
WARNING: New definition 
    action(Main.MyPolicy{#S<:Any, #A<:Any}, #S<:Any) at none:1
is ambiguous with: 
    action(Main.Policy{#T<:Main.Belief, #A<:Any}, #T<:Main.Belief) at none:1.
To fix, define 
    action(Main.MyPolicy{_<:Main.Belief, #A<:Any}, _<:Main.Belief)
before the new definition.
action (generic function with 3 methods)
```
From the compiler's perspective, it just doesn't make much sense to have a (::Policy, ::Belief) version declared when we already have a (::Policy, ::Any) version declared and we expect for (::MyPolicy, ::Any) versions to be declared by others. I think the fact that pomdp policies should use a ::Belief second argument should just be noted in the docstring. The question of whether Policy should be parameterized is a different issue.

**Comment by tawheeler** [comment]
I see. The problem is that `S` and `A` can inherently be anything, so even if we parameterize the policy we get the same error. Even parameterization has the problem of people using `Belief`s as states. (Not that they _should_, but they _could_).

Referring to issues #60 and #69, we may need problem definitions to create actions and we may be able to differentiate between MDPs and POMDPs, in which case we could use `action(::Policy, ::S, ::MDP)` and `action(::Policy, ::Belief, ::POMDP)`.

Alternatively, we could differentiate between `::Belief` policies and `::A` policies:

```
abstract AbstractPolicy
abstract POMDPPolicy <: AbstractPolicy
abstract MDPPolicy <: AbstractPolicy

action(::MDPPolicy, ::S)
action(::POMDPPolicy, ::Belief)
```

Another option is to use different function names.
Rather than having `action(::Policy, ::S)` and `action(::Belief, ::Policy)` or similar, we could have: `mdp_action(::Policy, ::S)` and `pomdp_action(::Policy, ::Belief)`.

**Comment by rejuvyesh** [comment]
Don't know if it has already been discussed, but doesn't it make more sense to define a quantity called say `PolicyState` so that we can write more general solvers that use:
1. Belief
2. Finite fixed length history of observations
3. RNNs
4. State (if reactive)
5. Finite state machine "state"

All these representations could be subtype of `PolicyState`

**Comment by tawheeler** [comment]
I spoke with @zsunberg and it sounds like the proposal is for:

```
action(policy::Policy, ::Any)
```

In POMDPs.jl with a documentation note that we use `Belief` for POMDP policies. If we don't restrict ourselves to `Beliefs` and can use things like `RNNs`, etc, then this makes even more sense. People can always have policy-specific calls: `action(policy::MyPolicy, ::RNN)` for instance.

**Comment by zsunberg** [comment]
Yeah @rejuvyesh , thanks for the suggestion. Having `PolicyState` unfortunately doesn't solve this issue because we want to support `Int` and `Bool` as state types and these can't be subtypes of `PolicyState`

My recommendation is to have this in POMDPs.jl:
```julia
"""
    action(policy::Policy, x::Any)
    action(policy::Policy, x::Belief)

Return the action specified by the policy for `x`

If an MDP is being simulated, `x` will be a state and hence can be any type. If a POMDP is being simulated, `x` will be a `Belief`.
"""
@pomdp_func action(policy::Policy, x::Any)
```

**Comment by mykelk** [comment]
@rejuvyesh , a Belief can be any of those things you listed. It doesn't have to explicitly represent a distribution over the current state.

@zsunberg , would you recommend that over Tim's suggestion of passing the POMDP or MDP in?

**Comment by zsunberg** [comment]
@mykelk , no, it doesn't solve the problem. As long as we are using the parametric scheme (which I think is really good, especially for [this](https://github.com/JuliaPOMDP/POMDPs.jl/issues/56#issuecomment-209542956) reason), `action(::Policy, ::Any)` must be part of the interface to handle MDPs. Since `PolicyState` is a subtype of `Any`, it will cause the same ambiguity warnings.

I honestly don't think this is a big issue at all, and [my recommendation above](https://github.com/JuliaPOMDP/POMDPs.jl/issues/70#issuecomment-209147576) is an adequate solution ( @tawheeler agrees).

I don't like passing the POMDP or MDP in. I would be OK with having both POMDPPolicy and MDPPolicy, but I think that a simple explanation in the docstring as I have above is completely adequate.

**Comment by zsunberg** [comment]
Note that, with the [above solution](https://github.com/JuliaPOMDP/POMDPs.jl/issues/70#issuecomment-209147576), the behavior of all programs will be **exactly the same** as if we define both `action(::Policy, ::Any)` and `action(::Policy, ::Belief)`.

**Comment by mykelk** [comment]
I'm okay with going with the consensus view.

**Comment by zsunberg** [comment]
Decided at the meeting that it was ok to leave the `::Belief` versions out
