### ISSUE TITLE
Which abstract types should be parameterized?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#71]
I have been thinking a lot lately about which of our types should be parameterized (see also #68). I think we should decide exactly which types should be parameterized, and with what parameters.

I can think of two reasons for parameterizing an *abstract* type: 
1. Documentation: It makes behavior clear to others, and guide development.
2. It allows functions to infer more information about types at compile time, so it can result in more efficient code, especially if it enables allocating arrays with concrete type.

However, there are also reasons against it:
a. Writing subtypes with parameters can be tricky at first (note that if the subtype *does not* have parameters, i.e. the abstract type's parameters are fixed, it is pretty easy. `MyPOMDP <: POMDP{Int,Int,Int}` is easy; `MyPolicy{T,A} <: Policy{T,A}` can be tricky)
b. If the parameters are not chosen wisely, it can be confusing to use, i.e. what should the `O` parameter in `Policy{S,A,O}` be for an MDP?
c. It can tempt people to write overly-specific code (e.g. `yourfunction{S,A,O}(Solver{S,A,O})` will not work with `type MySolver <: Solver end`).

Another important thing to keep in mind is that subtypes of unparameterized abstract types *can still be parameterized*.

My first question is "**Are there reasons for or against parametrization** that I have forgotten about?".

Here are my initial recommendations regarding which types should be parameterized:

Function | Does Zach think it should be parameterized
---|---
abstract Belief{T} <: AbstractDistribution{T} | yes?
abstract BeliefUpdater | no
abstract DiscreteDistribution{T} <: AbstractDistribution{T} | yes?
abstract Policy{T,A}^& | no?
abstract POMDP{S,A,O} | yes
abstract MDP{S,A} <: POMDP{S,A,S} | yes
abstract AbstractDistribution{T} | yes?
abstract Simulator | no
abstract Solver | no
abstract AbstractSpace{T} | yes?

^& I think `Policy{T,A}` where `T` is the input type (a belief for POMDPs), and `A` is the output type is a better parameterization than `Policy{S,A,O}`

What do you all think? Do we need to have a short meeting about this and other issues?

**Comment by mykelk** [comment]
Looks good. Go ahead and meet without me this week. We need to build consensus soon.

**Comment by zsunberg** [comment]
We settled on only parameterizing POMDP, MDP, AbstractDistribution, AbstractSpace, and DiscreteDistribution
