### ISSUE TITLE
Removing notion of Belief from problem defintion

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#76]
I'd like to resolve some of the naming details that I don't think have been finalized yet.

1. We are removing the notion of Belief from the problem definition. This means that ```create_belief(::POMDP)``` and ```initial_belief(::POMDP)``` get replaced with ```initial_state_distribution(::POMDP)```.  ```create_belief(::Updater)``` still exists. Does everyone agree?

2. It no longer makes sense to have ```convert_belief{B}(updater, initial_state_dist, belief)```, because we are converting a distribution to a Belief not a Belief to a Belief. @zsunberg proposed ```convert_to_belief{B}(...)```, but how about a shorter ```convert{B}(...)``` instead?  

Thoughts?

**Comment by zsunberg** [comment]
I agree on 1.

`convert` is already a common function in julia with a different meaning, so I don't think we should use it. Instead of `convert()`, I think we should use `adapt(updater, initial_state_dist, belief)`. I would also be ok with `transform`, but would prefer `adapt`.

**Comment by zsunberg** [comment]
@mykelk  suggested `initialize_belief(updater, state_dist, belief)' to me this morning. I am ok with that. If everyone else is, we should go with it tonight.

**Comment by zsunberg** [comment]
`initialize_belief` seems like the most likely winner so I'm just going to implement that for now.

**Comment by ebalaban** [comment]
I am ok with `initialize_belief`.

**Comment by etotheipluspi** [comment]
Both issues resolved in #78
