### ISSUE TITLE
Iterator-like function for AbstractDistribution

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#77]
In #47, we converged on the idea of having an ```iterator``` method for AbstractSpace. Does it make sense to have this method (or a method like it) for ```AbstractDistribution```? The method would return an iterable type over the discrete variables in the distribution. 

Since this is a distribution ```domain(...)``` or ```support(...)``` also make sense here. However, I do like ```iterator(...)``` since it would be consistent with what we've done in AbstractSpace (this may be a bad name from a mathematical standpoint however).

Is everyone ok with having an ```iterator(...)``` method for AbstractDistribution type?

**Comment by mykelk** [comment]
That's probably fine. For some cases (e.g., continuous spaces) iterator might not be supported.

**Comment by zsunberg** [comment]
Yeah, I think iterator is the best choice

**Comment by ebalaban** [comment]
Agree, iterator is probably the way to go.

**Comment by etotheipluspi** [comment]
Updated with #78
