### ISSUE TITLE
State not defined after loading POMDPs

### ISSUE THREAD

**Issue by rguptatx** [JuliaPOMDP/POMDPs.jl#83]
when running MDP tutorial

julia> Pkg.clone("https://github.com/sisl/POMDPs.jl")
julia> using POMDPs
julia> using POMDPDistributions
julia> type GridWorldState <: State
    x::Int64 # x position
    y::Int64 # y position
    bumped::Bool # did we bump the wall?
    done::Bool # are we in a terminal state?
end
ERROR: UndefVarError: State not defined
julia> State
ERROR: UndefVarError: State not defined

**Comment by etotheipluspi** [comment]
We recently went through an interface change, and the tutorials haven't been updated. The ```State``` abstract type is no longer part of the interface. Getting the tutorials updated is on the todo list, and I'll try to get it done by tomorrow.

**Comment by rguptatx** [comment]
do you have another estimate on when the tutorials will be updated?

**Comment by rguptatx** [comment]
alternately, is there is a way to get the older version of POMDP 
and other packages that work with the tutorial with States?

**Comment by zsunberg** [comment]
Instead of the tutorial, you could look at
https://github.com/JuliaPOMDP/POMDPModels.jl for examples. It contains 3
problem definitions that work with the new interface, albeit without much
explanation. I think it also contains some tests.

Zach

**Comment by etotheipluspi** [comment]
The tutorials have been updated. Thanks for the wait. 

As @zsunberg mentioned the tutorial implementations can also be found in POMDPModels.

**Comment by zsunberg** [comment]
Great, thanks for updating these, Max!
