### ISSUE TITLE
should there be a unified interface for vectorized representations of state?

### ISSUE THREAD

**Issue by cho3** [JuliaPOMDP/POMDPs.jl#85]
If you're using a function approximation (eg neural network) for your values (or directly learning a policy for instance), then you need a vectorized representation of your state/observation. 

Is there a need for a unified interface for this particular feature or should this be pushed off to the solvers?

If the former is true, some suggestions for what can be done:

```
vec(state)
vec(mdp, state)
feature_function = generate_feature_function(mdp)
```

The first two would be fairly easy to interpret semantically, but the last one might save some overhead (this is what I do in my ReinforcementLearning.jl package)

Thoughts?

**Comment by etotheipluspi** [comment]
I think something like this would be useful. My vote is for something that looks like the second option
```vec(mdp, state)```. 

Its not clear to me where this type of function would go. If it used exclusively with reinforcement learning, we can potentially add it to GenerativeModels.jl. However, something like this may be useful in other settings (none come to mind at the moment), so adding it to the main interface may not be a bad idea.

We can even parametrize it to work with actions and observations:
```julia
vec{S,A,O}(pomdp::POMDP{S,A,O}, S)
vec{S,A,O}(pomdp::POMDP{S,A,O}, A)
vec{S,A,O}(pomdp::POMDP{S,A,O}, O)
```

**Comment by cho3** [comment]
For the sake of discussion, the settings I could see a vectorized version of a state/action/observation in: 

* Function approximation (linear, neural network, etc...) applied to (action-) value functions, policies
* Mapping to/from real number space for something like planning or MPC
* Passing to solvers written in other languages

**Comment by zsunberg** [comment]
It seems like this would only be efficient if the user has a vector already
embedded in their state. i.e. with
```julia
type MyState
    x::Float64
    y::Float64
end
```
`vec(s)` would not be efficient because it would have to allocate a vector
every time it is called, but with
```julia
type MyStateVec
    xy::Vector{Float64}
end
```
`vec(s)` would be efficient. That is fine... it's just worth noting.

Would `vec()` be required to return a `Vector{Float64}` or should we be
more permissive, i.e. allow it to return a tuple or an iterator? I guess
other libraries probably directly access the memory, so an `Array` would be
required.

**Comment by etotheipluspi** [comment]
@zsunber another option for making ```vec``` efficient would be to pre-alocate the vector in the POMDP object if the function signature looks like ```vec(pomdp, state)```.

I think ```vec``` should return an ```Array{Float64}```, and not a tuple or an iterator. An Array over a Vector type is also preferred in case the state is represented by a matrix (an image for example).

**Comment by zsunberg** [comment]
I think `vec()` should only be a function of the state, not the state and
the POMDP. It is possible to write fast code with that. It is fine to make
it the user's responsibility to avoid writing something really slow.

Are there any cases where we would want `vec` to return an `Array{Int}` or
something else? I am thinking that since this will probably be used with
software packages that want direct access to a chunk of memory filled with
floats, we should specify that `vec` should return an `Array{Float64}` as
@etotheipluspi said.

**Comment by cho3** [comment]
What about sparse arrays? e.g. if the user is being very explicit with their features or using tile coding or some form of discretization

**Comment by zsunberg** [comment]
Either `vec()` could be specified to return an `AbstractArray{Float64}` or
we could say that users should implement `Base.sparse()` for their state
type if a sparse representation is required. I think I might slightly
prefer the latter.

**Comment by etotheipluspi** [comment]
I vote for returning ```AbstractArray{Float64}```. This gives us the flexibility of handling other array types like ```SharedArray``` in case we want to run parallel computation with Julia.

**Comment by zsunberg** [comment]
What if there are two different solvers, SolverDense that expects a dense
vector and accesses the memory directly and SolverSparse that expects a
sparse representation? Then if we only have vec() that returns an abstract
array, a problem cannot be used with both SolverDense and SolverSparse
without editing vec() in between.

Actually, there is already a solution to this, right? convert!, We should
just use convert(::Type{Array{Float64}}, ::MyState) for this, right?

**Comment by etotheipluspi** [comment]
Added this in f8b6ae930f98490e2d0672d6aae15871f1b81257

**Comment by zsunberg** [comment]
We have as of late started using a 3 argument version of `convert` for this, e.g. `convert(::Type{Vector{Float64}, s::MyState, p::MyProblem)`. There could be a problem though if both states and actions are represented by the same type. There is no way then to tell if you're converting an action or a state...

**Comment by zsunberg** [comment]
I am running into the issue mentioned above - the workaround I'm going with now is defining `convert_s`, `convert_a`, and `convert_o`, e.g. `convert_s(::Type{Int}, s::ContinuousState, dmdp::DiscretizedMDP)`

This is to be consistent in style with the `generate_*` functions. As with `generate_`, there is an alternative style with just one function and some sort of flag being passed in JuliaPOMDP/GenerativeModels#11 .

If this is adopted `convert_*` would fall back to a default implementation calling `convert`

**Comment by zsunberg** [comment]
... 3 months later... I think we need to switch to `convert_s`, `convert_a`, and `convert_o`. for the reason above. @rejuvyesh any comment as a person who has worked with other libraries?

**Comment by rejuvyesh** [comment]
I think it makes sense to have separate functions.
