### ISSUE TITLE
Observation and Reward functions with s-a-s' and s-a arguments

### ISSUE THREAD

**Issue by etotheipluspi** [JuliaPOMDP/POMDPs.jl#90]
In #25, we reached a consensus on supporting both s-a and s-a-s' observations, but it was a rather tedious decision. Most wanted s-a-s' only support, but SARSOP only works with a-s' observations, so we kept both types of functions.

There may be a more elegant way to handle this than the way we do it now. We can default the s-a-s' observation function to the a-s' one. It would look like this in POMDPs.jl

```julia
@pomdp_func observation{S,A,O}(problem::POMDP{S,A,O}, a::A, sp::S, dist)

observation{S,A,O}(problem::POMDP{S,A,O}, s::S, ac::A, sp::S, dist) = observation(problem, a, sp)
```

All the solvers would use the s-a-s' observation, but the user can choose to implement which ever one they prefer. This also plays nice with SARSOP. Personally, I prefer the s-a formulation for rewards as well, and a similar approach can be taken to use both the s-a and s-a-s' versions.

What does everyone think about this?

**Comment by zsunberg** [comment]
Does SARSOP use observation(s, a) or observation(a, sp)? I think it does
make sense to do the same thing with reward, except reward might use (s,a)
instead of (a,sp). Which one does SARSOP use? I think it's important to be
precise about this because it could be confusing

**Comment by etotheipluspi** [comment]
SARSOP does use the (a, sp) convention. We can specify this in the docs, and make clear the distinction between the observation and the reward function, i.e. (a, sp) for observation and (s, a) for reward.

**Comment by etotheipluspi** [comment]
Submitted a PR for this, please review, and let me know if there are objections. I want to get this merged, and tag this version of POMDPs.jl so we can add it to METADATA.

**Comment by etotheipluspi** [comment]
I'm going to go ahead and merge this. I know its the weekend, and not everyone may have looked this PR over, but I'd like to get this resolved before tagging the latest POMDPs.jl version.

The PR should be backwards compatible, and I tested it with all the packages. 

Feel free to re-open if you want to discuss this after the tag.
