### ISSUE TITLE
Nitpick: Docstrings should use imperative form.

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMDPs.jl#97]
We should stick to the julia policy from http://docs.julialang.org/en/release-0.4/manual/documentation/ when writing docstrings:

"The one-line sentence should use the imperative form (“Do this”, “Return that”) instead of the third person (do not write “Returns the length...”) when documenting functions."

**Comment by etotheipluspi** [comment]
This convention was adopted, closing.
